B-F Backup Sandbox 30.4.12/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Channel__c</fullName>
        <description>INFOWELDERS</description>
        <label>Channel</label>
        <picklist>
            <picklistValues>
                <fullName>On</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Sellable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wholesaler</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sub_Wholesaler</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INTEG MAINLY ON</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INTEG MAINLY OFF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ON PREMISE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OFF PREMISE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INTEGRATED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NON RETAIL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UNCLASSIFIED</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Account_Product__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Products</relationshipLabel>
        <relationshipName>Account_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <description>Brand Name</description>
        <label>Brand</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Account Products</relationshipLabel>
        <relationshipName>Account_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Product</label>
    <nameField>
        <displayFormat>AP-{0}</displayFormat>
        <label>Account Product</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

B-F Backup Sandbox 30.4.12/src/objects/Brand__c.object
<CustomObject>
    <description>Used by CRM.
NPA Rollout: Used to store Brands.</description>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

B-F Backup Sandbox 30.4.12/src/objects/Mandatory_Products__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <description>Infowelders</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Mandatory Products</relationshipLabel>
        <relationshipName>Mandatory_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Custom_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created for the Product Remediation</description>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Mandatory Products</relationshipLabel>
        <relationshipName>Mandatory_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Infowelders</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Mandatory Products</relationshipLabel>
        <relationshipName>Mandatory_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Mandatory Product</label>
    <nameField>
        <displayFormat>MP-{000000}</displayFormat>
        <label>Mandatory Products Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mandatory Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Product__c.object
<CustomObject>
    <description>NPA Rollout: Object for storing Products used in National Promotion application.
Product Remediation : Replicated all standard product fields here.</description>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Infowelders, NPA Rollout: Used to store the related Brand</description>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipName>Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <description>Created as a part of product remediation</description>
        <label>Channel</label>
        <picklist>
            <picklistValues>
                <fullName>On</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Both</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <description>NPA Rollout: Stores the product code</description>
        <label>Product Unique Key</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Promotion__c.object
<CustomObject>
    <description>Used by CRM.
NPA Rollout: Used to store Promotions.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Infowelders</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Promotions</relationshipLabel>
        <relationshipName>Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <description>INFOWELDERS</description>
        <formula>Promotion_Activity__r.Brand__r.Name</formula>
        <inlineHelpText>Brand is tied to the selected promotion activity.</inlineHelpText>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <inlineHelpText>It defaults to outlet channel unless channel is pubs then you pick on or off.</inlineHelpText>
        <label>Channel</label>
        <picklist>
            <picklistValues>
                <fullName>ON</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OFF</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Promotion_Activity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Infowelders</description>
        <label>Promotion Activity</label>
        <referenceTo>Promotion_Activity__c</referenceTo>
        <relationshipLabel>Promotions</relationshipLabel>
        <relationshipName>Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Promotion</label>
    <nameField>
        <label>Promotion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

B-F Backup Sandbox 30.4.12/src/objects/Promotion_Activity__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Infowelders</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Infowelders</description>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>Promotion Activities</relationshipLabel>
        <relationshipName>Promotion_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <label>Channel</label>
        <picklist>
            <picklistValues>
                <fullName>On</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Off</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Promotion Activity</label>
    <nameField>
        <label>Promotion Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promotion Activities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

B-F Backup Sandbox 30.4.12/src/classes/Test_AccountFactsheet.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class Test_AccountFactsheet {

    static testMethod void myUnitTest() {
    	Account Acc = new Account(Name = 'test');
    	insert Acc;
    	
    	Account Acc1 = new Account(Name = 'test1', Channel__c = 'on');
    	insert Acc1;
    	
    	Account Acc2 = new Account(Name = 'test2', Channel__c = 'off');
    	insert Acc2;
    	
        ApexPages.currentPage().getParameters().put('AccountId', acc.Id);
        Promotion_Activity__c pa = new Promotion_Activity__c(Name = 'x Secondary Placement x', Active__c = true);
        insert pa;
        
        Promotion__c promo = new Promotion__c (Account__c = acc.Id, Promotion_Activity__c = pa.ID);
        insert promo;
        
        Brand__c b = new Brand__c(Name = 'JDB');
        insert b;
        
        Product__c cp = new Product__c(Name = 'JD',Brand__c =  b.ID);
        insert cp;
        
        Mandatory_Products__c mp = new Mandatory_Products__c(Account__c = Acc.ID, Custom_Product__c = cp.ID); 
       	insert mp;
       	
       	Product__c cp1 = new Product__c(Name = 'JD',Brand__c =  b.ID);
        insert cp1;
        
        Mandatory_Products__c mp1 = new Mandatory_Products__c(Account__c = Acc.ID, Custom_Product__c = cp1.ID); 
       	insert mp1;
       	
       	Account_Product__c ap = new Account_Product__c(Account__c = Acc.ID ,Product__c=cp.ID);
       	insert ap;
       	
       	Account_Product__c ap1 = new Account_Product__c(Account__c = Acc.ID, Product__c=cp1.ID);
       	insert ap1;
       	
        AccountFactsheet af = new AccountFactsheet ();
        
        ApexPages.currentPage().getParameters().put('AccountId', acc1.Id);
        af = new AccountFactsheet ();
        
        ApexPages.currentPage().getParameters().put('AccountId', acc2.Id);
        af = new AccountFactsheet ();
    }
}