B-F Backup Sandbox 30.4.12/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Channel__c</fullName>
        <description>INFOWELDERS</description>
        <label>Channel</label>
        <picklist>
            <picklistValues>
                <fullName>On</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Sellable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wholesaler</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sub_Wholesaler</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INTEG MAINLY ON</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INTEG MAINLY OFF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ON PREMISE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OFF PREMISE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INTEGRATED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NON RETAIL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UNCLASSIFIED</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used by CRM.
NPA Rollout: Used to store the Market reference.</description>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>EUR_Outlets</fullName>
        <active>true</active>
        <description>European - Outlets</description>
        <label>EUR - Outlets</label>
    </recordTypes>
    <recordTypes>
        <fullName>Non_Sellable</fullName>
        <active>true</active>
        <description>Accounts that do not require visits and are not sold to</description>
        <label>Non-Sellable</label>
    </recordTypes>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Market__c.object
<CustomObject>
    <description>Used by CRM.
NPA Rollout: Used to store Markets at State Level.</description>
    <fields>
        <fullName>Market_Code__c</fullName>
        <description>Used to store technical code for respective markets</description>
        <externalId>true</externalId>
        <label>Market Code</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Off_Channel__c</fullName>
        <description>This field is used by the Outlet Visit page to determine what grid-layout to use in the B-F and Competitor Brands sections. This Off Channel references the value selected in the related Account.Channel__c field value.</description>
        <inlineHelpText>Used by the Outlet Visit page to determine what grid-layout to use in the B-F and Competitor Brands sections. This &quot;Off Channel&quot; references the value in the related Account.Channel__c field value.
1-Standard Layout
2-Euro Off
3-Euro On</inlineHelpText>
        <label>Off Channel</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>On_Channel__c</fullName>
        <description>This field is used by the Outlet Visit page to determine what grid-layout to use in the B-F and Competitor Brands sections. This On Channel references the value selected in the related Account.Channel__c field value.</description>
        <inlineHelpText>Used by the Outlet Visit page to determine what grid-layout to use in the B-F and Competitor Brands sections. This &quot;On Channel&quot; references the value in the related Account.Channel__c field value.
1-Standard Layout
2-Euro Off
3-Euro On</inlineHelpText>
        <label>On Channel</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

B-F Backup Sandbox 30.4.12/src/objects/Outlet_Visit__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Outlet (Account)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Outlet Visits</relationshipLabel>
        <relationshipName>Outlet_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Met_With__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Met With (Contact)</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Outlet Visits</relationshipLabel>
        <relationshipName>Outlet_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Time_Tracking__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>PARX - Jochen Schrader: Needed for a weekly report about the number of visits done by a sales rep and his possible (maximum) number of visits that can be calculated by his timetracking</description>
        <label>Time Tracking</label>
        <referenceTo>Time_Tracking__c</referenceTo>
        <relationshipLabel>Outlet Visits</relationshipLabel>
        <relationshipName>Outlet_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Visit_Date__c</fullName>
        <label>Visit Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Outlet Visit</label>
    <nameField>
        <displayFormat>OV-{00000}</displayFormat>
        <label>Outlet Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outlet Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Time_Tracking__c.object
<CustomObject>
    <description>PARX - Jochen Schrader: P00002 Germany needs to track the times for their sales reps easily to compare this to the sums of the actual times.</description>
    <fields>
        <fullName>Staff_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>PARX - Jochen Schrader: P00002 Account that is related to Staff Member</description>
        <inlineHelpText>Account that is related to Staff Member</inlineHelpText>
        <label>Staff Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Time Tracking</relationshipLabel>
        <relationshipName>Time_Tracking</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <defaultValue>Date(Year(Today()),Month(Today()),1 )</defaultValue>
        <description>PARX - Jochen Schrader: P00002 The Start Date you are working for B-F this month.</description>
        <inlineHelpText>The Start Date you are working for B-F this month.</inlineHelpText>
        <label>StartDate</label>
        <type>Date</type>
    </fields>
    <label>Time Tracking</label>
    <nameField>
        <displayFormat>T{YYYY}{MM}-{00}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Tracking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

B-F Backup Sandbox 30.4.12/src/classes/Test_onTimeTracking.cls
/**
 * Testing the trigger onTimeTracking
 * goal is to test the selection of outlet visits and the reference to the time tracking record
 *
 * @date	01/11/2012
 * @author 	Jochen Schrader
**/
@isTest
private class Test_onTimeTracking {

    static testMethod void testingTimeTrackingTriggerForConnectingOutletVisits() {
		RecordType RTNS = [select id from RecordType where sObjectType = 'Account' AND developerName = 'Non_Sellable' limit 1];
		RecordType RTEUR = [select id from RecordType where sObjectType = 'Account' AND developerName = 'EUR_Outlets' limit 1];
    	Market__c market = new Market__c(Market_Code__c = 'GER', Name = 'Germany', Off_Channel__c = '1', On_Channel__c = '1');
        insert market;
        Account accStaff = new Account(Name = 'PARX Staff account', Market__c = market.Id, RecordTypeId = RTNS.Id, Channel__c = 'On', BillingCountry = 'DE');
        insert accStaff;
        Account accOutlet = new Account(Name = 'PARX Outlet account', Market__c = market.Id, RecordTypeId = RTEUR.Id, Channel__c = 'On', BillingCountry = 'DE');
        insert accOutlet;
        Contact con = new Contact(LastName = 'Roger', AccountId = accOutlet.Id);
        insert con;
        
        Outlet_Visit__c outlet = new Outlet_Visit__c(Visit_Date__c = system.today());
	    outlet.Account__c = accOutlet.Id;
	    outlet.Met_With__c = con.Id;
	    insert outlet;
        
        test.startTest();
	        Time_Tracking__c tt = new Time_Tracking__c();
	        tt.Staff_Account__c=accStaff.id;
	        tt.StartDate__c=system.today();
	        insert tt;
	    test.stopTest();
	    outlet=[SELECT Id, Time_Tracking__c FROM Outlet_Visit__c WHERE id = :outlet.id];
	    system.assertEquals(tt.id,outlet.Time_Tracking__c);
    }
}