B-F Backup Sandbox 30.4.12/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Legacy_ID__c</fullName>
        <description>Used by CRM.
NPA Rollout: Used to store the Customer Account Number.</description>
        <externalId>true</externalId>
        <label>Legacy ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used by CRM.
NPA Rollout: Used to store the Market reference.</description>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PAS_Relevant__c</fullName>
        <description>NPA Rollout: Used to denote whether the account should be available for allocation or not.</description>
        <label>PAS Relevant</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>INFOWELDERS</description>
        <label>Supplier</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts (As Supplier)</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

B-F Backup Sandbox 30.4.12/src/objects/B_F_Contact__c.object
<CustomObject>
    <description>FDC-GD: Junction object used to associate B-F Contacts across multiple Accounts and Field Offices.
NPA Rollout: Used to store Account-User relationship.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>FDC-GD: Used by Global Directory application.
NPA Rollout: Used to refer to shipto.</description>
        <inlineHelpText>Select Account</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>B-F Contacts</relationshipLabel>
        <relationshipName>B_F_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used by Global Directory application: Related BF/Contact
NPA Rollout: Used to refer to User.</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>B_F_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>B-F Contact</label>
    <nameField>
        <displayFormat>B-F {0000}</displayFormat>
        <label>B-F Contacts Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>B-F Contacts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

B-F Backup Sandbox 30.4.12/src/objects/Brand__c.object
<CustomObject>
    <description>Used by CRM.
NPA Rollout: Used to store Brands.</description>
    <fields>
        <fullName>Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Infowelders:Used by CRM.
NPA Rollout: Used to refer to Supplier.</description>
        <label>Supplier</label>
        <referenceTo>Supplier__c</referenceTo>
        <relationshipLabel>Brands</relationshipLabel>
        <relationshipName>Brands</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Internal_Order__c.object
<CustomObject>
    <description>NPA Rollout: Object for storing Internal Orders</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>NPA Rollout: Used to store description of the Internal Order</description>
        <externalId>true</externalId>
        <label>Description</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Internal_Order_Number__c</fullName>
        <description>NPA Rollout: Used to store the Internal Order number since the Name field cannot be made unique</description>
        <externalId>true</externalId>
        <label>Internal Order Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Internal Order</label>
    <nameField>
        <label>Internal Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Internal Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

B-F Backup Sandbox 30.4.12/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Infowelders</description>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legacy_ID__c</fullName>
        <externalId>true</externalId>
        <label>Legacy ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Infowelders</description>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <description>Infowelders</description>
        <formula>Brand__r.Supplier__r.Name</formula>
        <label>Supplier</label>
        <type>Text</type>
    </fields>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Product__c.object
<CustomObject>
    <description>NPA Rollout: Object for storing Products used in National Promotion application.
Product Remediation : Replicated all standard product fields here.</description>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Infowelders, NPA Rollout: Used to store the related Brand</description>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipName>Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Product Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Legacy_ID__c</fullName>
        <description>Created as a part of product remediation</description>
        <label>Legacy ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created as a part of product remediation</description>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>ProductsCustom</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Planned_Cost__c</fullName>
        <description>NPA Rollout: Used to store Planned Cost of Products</description>
        <label>Planned Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <description>NPA Rollout: Stores the product code</description>
        <label>Product Unique Key</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <description>Created as a part of product remediation</description>
        <formula>Brand__r.Supplier__r.Name</formula>
        <label>Supplier</label>
        <type>Text</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Promotion__c.object
<CustomObject>
    <description>Used by CRM.
NPA Rollout: Used to store Promotions.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Infowelders</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Promotions</relationshipLabel>
        <relationshipName>Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brand_NPA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>NPA Rollout: Used to refer to the brand.</description>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>Promotions</relationshipLabel>
        <relationshipName>Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <description>INFOWELDERS</description>
        <formula>Promotion_Activity__r.Brand__r.Name</formula>
        <inlineHelpText>Brand is tied to the selected promotion activity.</inlineHelpText>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Internal_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>NPA Rollout: Stores the related Internal Order</description>
        <label>Internal Order</label>
        <referenceTo>Internal_Order__c</referenceTo>
        <relationshipLabel>Promotions</relationshipLabel>
        <relationshipName>Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legacy_ID__c</fullName>
        <externalId>true</externalId>
        <label>Legacy ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <formula>Account__r.Market__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Market</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Promotion_Start_Date__c</fullName>
        <description>INFOWELDERS:Used by CRM.
        NPA Rollout: Used to store the promotion start date.</description>
        <label>Promotion Start Date</label>
        <type>Date</type>
    </fields>
    <label>Promotion</label>
    <nameField>
        <label>Promotion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

B-F Backup Sandbox 30.4.12/src/objects/Promotion_Material_Item__c.object
<CustomObject>
    <description>Used by CRM.
NPA Rollout: Used to store products added to Promotions (Promotion line items).</description>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>Product_Custom__r.Brand__r.Name</formula>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legacy_ID__c</fullName>
        <externalId>true</externalId>
        <label>Legacy ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Planned_Cost__c</fullName>
        <description>NPA Rollout: Stores the planned cost of the product for this promotion</description>
        <label>Planned Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Infowelders</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Promotion Material Items</relationshipLabel>
        <relationshipName>Promotion_Material_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Promotion__c</fullName>
        <description>Infowelders: Used by CRM.
		NPA Rollout: Used to refer to Promotion.</description>
        <label>Promotion</label>
        <referenceTo>Promotion__c</referenceTo>
        <relationshipLabel>Promotion Material Items</relationshipLabel>
        <relationshipName>Promotion_Material_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Promotion Material Item</label>
    <nameField>
        <displayFormat>PMI-{YYYY}{00000}</displayFormat>
        <label>Promotion Material Item#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotion Material Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

B-F Backup Sandbox 30.4.12/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Market__c</fullName>
        <description>INFOWELDERS - These text values MUST match the Market Name records&apos; text values.
NPA Rollout: Used to store the markets a user is allocated to. Multiple values can be used separated by semi-colon.</description>
        <inlineHelpText>CRM: Market at a Country level-  such as Germany, Korea, India, Japan etc.
NPA: Market at a State level-  such as Illinois, Kentucky etc.</inlineHelpText>
        <label>Market</label>
        <picklist>
            <picklistValues>
                <fullName>ALL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Germany</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Japan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Korea</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thailand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Taiwan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>India</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canada General</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

B-F Backup Sandbox 30.4.12/src/classes/Test_NPA_CustomPromotionMaterial_Edit.cls
/******************************************************************************
Name			: Test_NPA_CustomPromotionMaterial_Edit
Description		: This is the test class for NPA_CustomPromotionMaterial_Edit

Modification Log:
-------------------------------------------------------------------------------
Developer			Date		Description
-------------------------------------------------------------------------------
Jishad P A (DC)	20-Jun-2011 Created
******************************************************************************/
@istest
private class Test_NPA_CustomPromotionMaterial_Edit{
    static testMethod void test(){
    	//Create test users
        Profile userProfile = [SELECT Id,Name FROM Profile Where Name like 'System Administrator' limit 1];
        UserRole role = [Select Name From UserRole Where Name = 'Global Administrator' Limit 1];
        List<User> userListOne = new List<User>{
        	new User(alias = 'test1', email='testuser1@b-f.com',
	            emailencodingkey='UTF-8', lastname='Test1', Market__c='Alaska;China',
	            languagelocalekey='en_US',localesidkey='en_US', 
	            profileid = userProfile.Id,timezonesidkey='America/Los_Angeles',
	            username='testuser1@b-f.com', UserRoleId=role.Id
            )};
        insert userListOne;

        System.runAs(userListOne[0]){
            // Create markets
            List<Market__c> marketList = new List<Market__c>{
                new Market__c(Name='Alaska'),new Market__c(Name='Alabama'),
                new Market__c(Name='Illinois'),new Market__c(Name='Kentucky')};
            insert marketList;
    
            // Create accounts
            Map<String,Schema.RecordTypeInfo> shiptoRTMapByName = Schema.SObjectType.Account.getRecordTypeInfosByName();
            Id shiptoRecType=null;
            if(shiptoRTMapByName.containsKey('POS Ship-To')){
                shiptoRecType = shiptoRTMapByName.get('POS Ship-To').getRecordTypeId();
            }
            
            List<ID> accIdList = new List<ID>();
            List<Account> accountList = new List<Account>{
                new Account(Name='Account1', Market__c=marketList[0].Id, RecordTypeId=shiptoRecType,
                    PAS_Relevant__c='Yes',Legacy_Id__c='ww1',ShippingStreet='street',ShippingCity='city',ShippingState='state'),
                new Account(Name='Account2', Market__c=marketList[0].Id, RecordTypeId=shiptoRecType,
                    PAS_Relevant__c='Yes',Legacy_Id__c='xx1',ShippingStreet='street',ShippingCity='city',ShippingState='state'),
                new Account(Name='Account2', Market__c=marketList[0].Id, RecordTypeId=shiptoRecType,
                    PAS_Relevant__c='Yes',Legacy_Id__c='yy1',ShippingStreet='street',ShippingCity='city',ShippingState='state'),
                new Account(Name='Account4', Market__c=marketList[0].Id, RecordTypeId=shiptoRecType,
                    PAS_Relevant__c='Yes',Legacy_Id__c='zz1',ShippingStreet='street',ShippingCity='city',ShippingState='state')};
            insert accountList;
            for(account acc : accountList){
                accIdList.add(acc.Id);
            }
            
            //Create B-F Contacts
            List<B_F_Contact__c> contactList = new List<B_F_Contact__c>{
                new B_F_Contact__c(Account__c=accountList[0].Id, User__c=userListOne[0].Id),
                new B_F_Contact__c(Account__c=accountList[1].Id, User__c=userListOne[0].Id),
                new B_F_Contact__c(Account__c=accountList[2].Id, User__c=userListOne[0].Id),
                new B_F_Contact__c(Account__c=accountList[3].Id, User__c=userListOne[0].Id)};
            insert contactList;
            
            //Create Supplier
            Supplier__c supp = new Supplier__c(Name='B-F');
            insert supp;
            
            // Create brands
            List<Brand__c> brandList = new List<Brand__c>{
                new Brand__c(Name='Brand1',Supplier__c=supp.Id),new Brand__c(Name='Brand2',Supplier__c=supp.Id)};
            insert brandList;
            
            //Create internal orders
            List<Internal_Order__c> ioList = new List<Internal_Order__c>{
                new Internal_Order__c(Name='IO1',Description__c='IO1',Internal_Order_Number__c='IO1'),
                new Internal_Order__c(Name='IO2',Description__c='IO2',Internal_Order_Number__c='IO2')};
            insert ioList;
            
            //Create products
            Id productRecTypeId=null;
            Map<String,Schema.RecordTypeInfo> productRTMapByName = Schema.SObjectType.Product__c.getRecordTypeInfosByName();
            if(productRTMapByName.containsKey('POS - US')){
                productRecTypeId = productRTMapByName.get('POS - US').getRecordTypeId();
            }
            List<Product__c> productList = new List<Product__c>{
                new Product__c(Name='Product1',RecordTypeId=productRecTypeId,Planned_Cost__c=10),
                new Product__c(Name='Product2',RecordTypeId=productRecTypeId,Planned_Cost__c=10),
                new Product__c(Name='Product3',RecordTypeId=productRecTypeId,Planned_Cost__c=10),
                new Product__c(Name='Product4',RecordTypeId=productRecTypeId,Planned_Cost__c=10)};
            insert productList;
            
            //Create promotions
            Id promotionRecTypeId=null;
            Map<String,Schema.RecordTypeInfo> promoRTMapByName = Schema.SObjectType.Promotion__c.getRecordTypeInfosByName();
            if(promoRTMapByName.containsKey('National Promotion - US')){
                promotionRecTypeId = promoRTMapByName.get('National Promotion - US').getRecordTypeId();
            }
            Date dt = system.today()+1;
            Date futureDt = system.today()+1;
            
            List<Promotion__c> promoList = new List<Promotion__c>{
                new Promotion__c(RecordTypeId=promotionRecTypeId,Promotion_Start_Date__c=dt,Brand_NPA__c=brandList[0].Id,
                Promotion_End_Date__c=dt,Freeze_Date__c=futureDt, Internal_Order__c=ioList[0].Id,Promotion_Status__c='Active',
                Promotion_Premise__c='On Premise'),
                new Promotion__c(RecordTypeId=promotionRecTypeId,Promotion_Start_Date__c=dt,Brand_NPA__c=brandList[0].Id,
                Promotion_End_Date__c=dt,Freeze_Date__c=futureDt, Internal_Order__c=ioList[1].Id,Promotion_Status__c='Active',
                Promotion_Premise__c='On Premise')};
            insert promoList;
    
            List<Promotion__c> dummyPromos = promoList;
            promolist = new List<Promotion__c>();
            
            // Get the promotions from database with formula fields
            promoList = [Select RecordTypeId,Tertile__c,Promotion_End_Date__c,Freeze_Date__c,Promotion_Start_Date__c,Fiscal_Year__c,
                                Internal_Order__r.Internal_Order_number__c,Promotion_Status__c,Brand_NPA__c,Has_Line_Items__c 
                                from promotion__c where Id in :dummyPromos];
            for(Promotion__c promo : promolist){
                promo.Promotion_Status__c = 'Active';
            }
            update promolist;
            
            // Create Promotion Material Items
            List<Promotion_Material_Item__c> pmiList = new List<Promotion_Material_Item__c>{
                new Promotion_Material_Item__c(Promotion__c=promoList[0].Id, Product_Custom__c=productList[0].Id,Status__c='0'),
                new Promotion_Material_Item__c(Promotion__c=promoList[0].Id, Product_Custom__c=productList[1].Id,Status__c='0'),
                new Promotion_Material_Item__c(Promotion__c=promoList[1].Id, Product_Custom__c=productList[0].Id,Status__c='0'),
                new Promotion_Material_Item__c(Promotion__c=promoList[1].Id, Product_Custom__c=productList[1].Id,Status__c='0')};
            insert pmiList;
    		
    		Test.startTest();
		    //Initialize the page
		    PageReference pageRefOne = Page.NPA_promotionMaterialCustomEdit;
		    Test.setCurrentPage(pageRefOne);
		    ApexPages.currentPage().getParameters().put('promotion', promolist[0].id);
		    Promotion_Material_Item__c pmi = new Promotion_Material_Item__c();
		    ApexPages.standardController stdController = new ApexPages.Standardcontroller(pmi);
		    NPA_CustomPromotionMaterial_Edit conExt = new NPA_CustomPromotionMaterial_Edit(stdController);
		    //Call controller methods
		    conExt.save();
		    conExt.cancel();
		    
		    Test.stopTest();
        }
    }
}