B-F Backup Sandbox 30.4.12/src/objects/Allocations__c.object
<CustomObject>
    <description>NPA Rollout: Object used to store Allocation information.</description>
    <fields>
        <fullName>Promotion_Material_Item__c</fullName>
        <label>Promotion Material Item</label>
        <referenceTo>Promotion_Material_Item__c</referenceTo>
        <relationshipLabel>Allocations</relationshipLabel>
        <relationshipName>Allocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Promotion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>NPA Rollout: Used to reference the related Promotion.</description>
        <label>Promotion</label>
        <referenceTo>Promotion__c</referenceTo>
        <relationshipLabel>Allocations</relationshipLabel>
        <relationshipName>Allocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Allocations</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Allocations Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Promotion__c.object
<CustomObject>
    <description>Used by CRM.
NPA Rollout: Used to store Promotions.</description>
    <label>Promotion</label>
    <nameField>
        <label>Promotion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

B-F Backup Sandbox 30.4.12/src/objects/Promotion_Material_Item__c.object
<CustomObject>
    <description>Used by CRM.
NPA Rollout: Used to store products added to Promotions (Promotion line items).</description>
    <fields>
        <fullName>Promotion__c</fullName>
        <description>Infowelders: Used by CRM.
		NPA Rollout: Used to refer to Promotion.</description>
        <label>Promotion</label>
        <referenceTo>Promotion__c</referenceTo>
        <relationshipLabel>Promotion Material Items</relationshipLabel>
        <relationshipName>Promotion_Material_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Promotion Material Item</label>
    <nameField>
        <displayFormat>PMI-{YYYY}{00000}</displayFormat>
        <label>Promotion Material Item#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotion Material Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

B-F Sandbox/trunk/src/classes/NPA_PromotionWrapper.cls
public class NPA_PromotionWrapper{
  public Promotion__c promotions {get;set;}
  public List<InnerWrapper> allocList {get;set;}
  
  public NPA_PromotionWrapper (Promotion__c promo, List<InnerWrapper> iw){
          promotions= promo;
          allocList = iw;
  }
  
  public class InnerWrapper{
      public Promotion_Material_Item__c PLI {get;set;}
      public List<Allocations__c> Allocs {get;set;}
      
      public InnerWrapper(Promotion_Material_Item__c items, List<Allocations__c> all){
          PLI = items;
          Allocs = all;
      }
  }
}