B-F Backup Sandbox 30.4.12/src/objects/Brand__c.object
<CustomObject>
    <description>Used by CRM.
NPA Rollout: Used to store Brands.</description>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Internal_Order__c.object
<CustomObject>
    <description>NPA Rollout: Object for storing Internal Orders</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>NPA Rollout: Used to store description of the Internal Order</description>
        <externalId>true</externalId>
        <label>Description</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Internal_Order_Number__c</fullName>
        <description>NPA Rollout: Used to store the Internal Order number since the Name field cannot be made unique</description>
        <externalId>true</externalId>
        <label>Internal Order Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Internal Order</label>
    <nameField>
        <label>Internal Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Internal Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Product__c.object
<CustomObject>
    <description>NPA Rollout: Object for storing Products used in National Promotion application.
Product Remediation : Replicated all standard product fields here.</description>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Infowelders, NPA Rollout: Used to store the related Brand</description>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipName>Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Product Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Planned_Cost__c</fullName>
        <description>NPA Rollout: Used to store Planned Cost of Products</description>
        <label>Planned Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <description>NPA Rollout: Stores the product code</description>
        <label>Product Unique Key</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>NPA Rollout: Used to store status of Product
0 = Active
1 = Cancelled</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Promotion__c.object
<CustomObject>
    <description>Used by CRM.
NPA Rollout: Used to store Promotions.</description>
    <fields>
        <fullName>Brand_NPA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>NPA Rollout: Used to refer to the brand.</description>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>Promotions</relationshipLabel>
        <relationshipName>Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <description>INFOWELDERS</description>
        <formula>Promotion_Activity__r.Brand__r.Name</formula>
        <inlineHelpText>Brand is tied to the selected promotion activity.</inlineHelpText>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Freeze_Date__c</fullName>
        <description>NPA Rollout: Stores the Freeze Date for the promotion</description>
        <label>Freeze Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>GTM_Channel_Description__c</fullName>
        <description>NPA Rollout: Stores the GTM Channel</description>
        <label>GTM Channel</label>
        <picklist>
            <controllingField>Promotion_Premise__c</controllingField>
            <picklistValues>
                <fullName>10 - Off-Wholesale Club</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21 - Off-Superstore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22 - Off-Conventional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24 - Off-Wine Specialty</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>25 - Off-Beer Specialty</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30 - Off-Drug</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40 - Off-Cigarette Outlet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>51 - Off-Limited/Assrtmnt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>52 - Off-Natural/Gourmet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>53 - Off-Warehouse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>54 - Off-Superette</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>55 - Off-Supermarket</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>56 - Off-Supercenter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>60 - Off-Category Killer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>70 - Off-Convenience</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>80 - Off-Mass Merch.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>90 - Off-Extended Master</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>501 - On-Fine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>502 - On-Casual Dining</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>503 - On-Theme Restaurant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>511 - On-Neighborhood</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>512 - On-Casual Nightclub</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>513 - On-Sports Bar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>514 - On-Prem Nightclub</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>515 - On-Adult Ent.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>516 - On-Irish</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>517 - On-Premium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>518 - On-Country Western</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>520 - On-Lodging</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>530 - On-Recreation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Internal_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>NPA Rollout: Stores the related Internal Order</description>
        <label>Internal Order</label>
        <referenceTo>Internal_Order__c</referenceTo>
        <relationshipLabel>Promotions</relationshipLabel>
        <relationshipName>Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Promotion_End_Date__c</fullName>
        <description>INFOWELDERS: Used by CRM.
NPA Rollout: Used to store the promotion end date.</description>
        <label>Promotion End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Promotion_Premise__c</fullName>
        <description>NPA Rollout: Stores the Premise for the Promotion</description>
        <label>Premise</label>
        <picklist>
            <picklistValues>
                <fullName>On &amp; Off Premise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Off Premise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Military</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Premise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transportation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Promotion_Start_Date__c</fullName>
        <description>INFOWELDERS:Used by CRM.
        NPA Rollout: Used to store the promotion start date.</description>
        <label>Promotion Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Promotion_Status__c</fullName>
        <description>NPA Rollout: Promotion Status to hold multiple status of National Promotion</description>
        <label>Promotion Status</label>
        <picklist>
            <picklistValues>
                <fullName>Created</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Promotion</label>
    <nameField>
        <label>Promotion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

B-F Backup Sandbox 30.4.12/src/objects/Promotion_Material_Item__c.object
<CustomObject>
    <description>Used by CRM.
NPA Rollout: Used to store products added to Promotions (Promotion line items).</description>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>Product_Custom__r.Brand__r.Name</formula>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Planned_Cost__c</fullName>
        <description>NPA Rollout: Stores the planned cost of the product for this promotion</description>
        <label>Planned Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_Custom__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>NPA Rollout: Used to store the related Product. /* API name need to be changed to Product__c after Product remediation*/</description>
        <label>Product Name</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Promotion Material Items</relationshipLabel>
        <relationshipName>Promotion_Material_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Description__c</fullName>
        <description>NPA Rollout: Used to fetch the product description</description>
        <label>Product Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Infowelders</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Promotion Material Items</relationshipLabel>
        <relationshipName>Promotion_Material_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Promotion__c</fullName>
        <description>Infowelders: Used by CRM.
		NPA Rollout: Used to refer to Promotion.</description>
        <label>Promotion</label>
        <referenceTo>Promotion__c</referenceTo>
        <relationshipLabel>Promotion Material Items</relationshipLabel>
        <relationshipName>Promotion_Material_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <description>Infowelders</description>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>NPA Rollout: Field to store the status of product for the promotion</description>
        <label>Item Status</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Unit_of_Measure__c</fullName>
        <description>NPA Rollout: Used to store the Unit of Measure for the product</description>
        <label>UoM</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Promotion Material Item</label>
    <nameField>
        <displayFormat>PMI-{YYYY}{00000}</displayFormat>
        <label>Promotion Material Item#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotion Material Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

B-F Sandbox/trunk/src/classes/Test_NPA_CustomPromotionClone.cls
/******************************************************************************
Name			: Test_NPA_CustomPromotionClone
Description		: This is the test class for NPA_CustomPromotionClone

Modification Log:
-------------------------------------------------------------------------------
Developer			Date		Description
-------------------------------------------------------------------------------
Jishad P A (DC)		20-Jun-2011 Created
******************************************************************************/
@isTest 
private class Test_NPA_CustomPromotionClone{
	static testMethod void NPA_CustomPromotionCloneTest(){
		// Create internal order
		Internal_Order__c io =    new Internal_Order__c();
		io.Name              =    '1234567';
		io.Internal_Order_Number__c=    '1234567';
		io.Description__c              =    '1234567';
		io.CurrencyIsoCode   =    'USD';
		insert io;
		
		//Create brand
		Brand__c b           =    new Brand__c();
		b.Name               =    'Jack Daniels';
		insert b;
		
		//Create product
		Product__c prod              =    new Product__c();
		prod.Name                    =    'Test Product';
		prod.Product__c              =    '123';
		prod.Planned_Cost__c         =    500;
		prod.Brand__c                =    b.Id;
		prod.Status__c               =    'Active';
		insert prod;
		
		//Create promotion
		Promotion__c p       =    new Promotion__c();
		p.Internal_Order__c  =    io.Id;
		p.Name               =    'Test Promotion';
		p.Promotion_Start_Date__c    =    Date.Today();
		p.Promotion_End_Date__c      =    Date.Today() + 5;
		p.Freeze_Date__c             =    Date.Today() + 7;
		p.CurrencyIsoCode            =    'USD';
		p.Promotion_Status__c        =    'Created';
		p.Brand_NPA__c               =    b.Id;
		p.Promotion_Premise__c       =    'Military';
		p.GTM_Channel_Description__c =    'On-Fine';
		insert p;
		
		//Create Promotion Material Item
		Promotion_Material_Item__c pmi    =    new Promotion_Material_Item__c();
		pmi.Product_Custom__c             =    prod.Id;
		pmi.Promotion__c                  =    p.Id;
		pmi.Planned_Cost__c               =    500;
		pmi.Quantity__c                   =    2;
		pmi.Status__c                     =    'Active';
		pmi.Product_Description__c        =    'This is a test product';
		pmi.Unit_of_Measure__c            =    'EA';
		insert pmi;
		
		//Initialize the page
		ApexPages.StandardController controller1 = new ApexPages.StandardController(p);
		ApexPages.currentPage().getParameters().put('id', p.id);
		NPA_CustomPromotionClone cpc1 = new NPA_CustomPromotionClone(controller1);
		PageReference pageRefOne = Page.NPA_PromoMaterialAddSearchPage;
		Test.setCurrentPage(pageRefOne);
		
		//Call controller methods
		PageReference pr    =    cpc1.custom_clone();
		PageReference pr1   =    cpc1.cancel();
		
		//Initialize page again
		ApexPages.StandardController controller2 = new ApexPages.StandardController(p);
		ApexPages.currentPage().getParameters().put('id', p.id);
		NPA_CustomPromotionClone cpc2 = new NPA_CustomPromotionClone(controller2);
		PageReference pageRefTwo = Page.NPA_PromoMaterialAddSearchPage;
		Test.setCurrentPage(pageRefTwo);
		// Call controller method
		PageReference pr2    =    cpc1.custom_clone();
	}
}