B-F Backup Sandbox 30.4.12/src/objects/Brand__c.object
<CustomObject>
    <description>Used by CRM.
NPA Rollout: Used to store Brands.</description>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Market__c.object
<CustomObject>
    <description>Used by CRM.
NPA Rollout: Used to store Markets at State Level.</description>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

B-F Backup Sandbox 30.4.12/src/objects/Promotion_Activity__c.object
<CustomObject>
    <fields>
        <fullName>Begin_Date__c</fullName>
        <description>INFOWELDERS</description>
        <label>Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Infowelders</description>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>Promotion Activities</relationshipLabel>
        <relationshipName>Promotion_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>INFOWELDERS</description>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Infowelders</description>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Promotion Activities</relationshipLabel>
        <relationshipName>Promotion_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Promotion_Type__c</fullName>
        <description>INFOWELDERS</description>
        <label>Promotion Type</label>
        <picklist>
            <picklistValues>
                <fullName>Agreement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local Promo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Theme Promo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Promo</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Promotion Activity</label>
    <nameField>
        <label>Promotion Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promotion Activities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

B-F Backup Sandbox 30.4.12/src/classes/promotionActivityGanttController.cls
public class promotionActivityGanttController {

    public promotionActivityGanttController(ApexPages.StandardController controller) {

    }


    public List<Promotion_Activity__c> PromotionActivities;
    
    public List<Promotion_Activity__c> getPromotionActivities()
    {
     getFilter();
     PromotionActivities = Database.query(Filter + ' ORDER BY Promotion_Type__c, Begin_Date__c');
     //PromotionActivities = [SELECT Name, Brand__r.Name, Market__r.Name, Begin_Date__c, End_Date__c, Promotion_Type__c FROM Promotion_Activity__c];
     return PromotionActivities;
    }
    
    public PageReference refresh() {
        getFilter();
        return null;
    }
    
    public date startDate;
    public string Filter;
    public string getFilter()
    {
        startDate = date.parse('1/1/2005');
        Filter = 'SELECT Name, Brand__r.Name, Market__r.Name, Begin_Date__c, End_Date__c, Promotion_Type__c FROM Promotion_Activity__c WHERE Begin_Date__c != :startDate';
        if(selBrand!=null&&selBrand!='ALL'){
            Filter += ' AND Brand__c = \''+selBrand+'\'';
        }
        if(selMarket!=null&&selMarket!='ALL'){
            Filter += ' AND Market__c = \''+selMarket+'\'';
        }
        system.debug(selType);
        return Filter;
    } 
    
    public string selBrand {get;set;}
    public List<SelectOption> getBrandsList() 
    {
        List<SelectOption> optionList = new List<SelectOption>();
        optionList.add(new SelectOption('ALL','ALL'));
        for(Brand__c y :[Select b.Name, b.Id From Brand__c b WHERE Id IN (SELECT Brand__c FROM Promotion_Activity__c) ORDER BY b.Name]) {
            optionList.add(new SelectOption(y.Id,y.Name));
        }
        return optionList;
    }
    
    public string selMarket {get;set;}
    public List<SelectOption> getMarketsList() 
    {
        List<SelectOption> optionList = new List<SelectOption>();
        optionList.add(new SelectOption('ALL','ALL'));
        for(Market__c y :[Select m.Name, m.Id From Market__c m WHERE Id IN (SELECT Market__c FROM Promotion_Activity__c) ORDER BY m.Name]) {
            optionList.add(new SelectOption(y.Id,y.Name));
        }
        return optionList;
    }
    
    public string selType {get;set;}

}