B-F Backup Sandbox 30.4.12/src/objects/Brand__c.object
<CustomObject>
    <description>Used by CRM.
NPA Rollout: Used to store Brands.</description>
    <fields>
        <fullName>Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Infowelders:Used by CRM.
NPA Rollout: Used to refer to Supplier.</description>
        <label>Supplier</label>
        <referenceTo>Supplier__c</referenceTo>
        <relationshipLabel>Brands</relationshipLabel>
        <relationshipName>Brands</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

B-F Backup Sandbox 30.4.12/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Infowelders</description>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <description>Infowelders</description>
        <formula>Brand__r.Supplier__r.Name</formula>
        <label>Supplier</label>
        <type>Text</type>
    </fields>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Product__c.object
<CustomObject>
    <description>NPA Rollout: Object for storing Products used in National Promotion application.
Product Remediation : Replicated all standard product fields here.</description>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Infowelders, NPA Rollout: Used to store the related Brand</description>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipName>Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <description>NPA Rollout: Stores the product code</description>
        <label>Product Unique Key</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <description>Created as a part of product remediation</description>
        <formula>Brand__r.Supplier__r.Name</formula>
        <label>Supplier</label>
        <type>Text</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Supplier__c.object
<CustomObject>
    <description>Used by CRM. 
NPA Rollout: Used to store Suppliers.</description>
    <fields>
        <fullName>Is_B_F_Brand__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box if this Supplier record is considered a B-F brand.</description>
        <inlineHelpText>Check this box if this Supplier record is considered a B-F brand.</inlineHelpText>
        <label>Is B-F Brand?</label>
        <type>Checkbox</type>
    </fields>
    <label>Supplier</label>
    <nameField>
        <label>Supplier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

B-F Sandbox/trunk/src/classes/promotionProductHelperClass.cls
public with sharing class promotionProductHelperClass {

/* Class Name : promotionProductHelperClass 
* Description: --
* Created By : --
* Created On : --

* Modification Log :  
* ----------------------------------------------------------------------------------------------------------------------------
* Developer       Date              Description
* ----------------------------------------------------------------------------------------------------------------------------
* VARUN           06-24-2011        Code for Product Remediation Check.
*                                   
*/ 
    public List<SelectOption> getrecordTypeList() {
        List<SelectOption> recordTypeList = new List<SelectOption>();
        recordTypeList.add(new SelectOption('ALL','ALL'));
        //code updated for product remediation added custom setting to enable and disable custom product code.
        //start of product remediation code
        //for(RecordType rt : [select id, name from RecordType where SobjectType='Product2'])
        for(RecordType rt :  [select id, name from RecordType where SobjectType='Product__c'])
        {
            recordTypeList.add(new SelectOption(rt.Id,rt.Name));            
        }         //end of product remediation code 

        return recordTypeList;     
    }     
    public List<SelectOption> getBFBrandsList() 
    {
        List<SelectOption> optionList = new List<SelectOption>();
        // Add a null option to force the user to make a selection. //
        optionList.add(new SelectOption('ALL','ALL'));
        for(Brand__c y :[Select r.Name, r.Id From Brand__c r where Supplier__r.Is_B_F_Brand__c = true ORDER BY r.Name]) 
        {
            optionList.add(new SelectOption(y.Id,y.Name));
        }
        return optionList;
    }     
}