B-F Backup Sandbox 30.4.12/src/objects/Brand__c.object
<CustomObject>
    <description>Used by CRM.
NPA Rollout: Used to store Brands.</description>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Market__c.object
<CustomObject>
    <description>Used by CRM.
NPA Rollout: Used to store Markets at State Level.</description>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Project_Opportunity__c.object
<CustomObject>
    <fields>
        <fullName>Achievement__c</fullName>
        <formula>Achievement_Sum__c / Ratings_Submitted__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Achievement</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Attractiveness__c</fullName>
        <formula>Attractiveness_Sum__c / Ratings_Submitted__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Attractiveness</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipName>Project_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Branded Line Extension (Full &amp; Mid Proof)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Single Serve</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multi-Serve</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NtW Mid-Proof</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NtW  Full-Proof</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Project_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X5_Yr_NPV__c</fullName>
        <defaultValue>0</defaultValue>
        <label>5 Yr NPV</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Promotion__c.object
<CustomObject>
    <description>Used by CRM.
NPA Rollout: Used to store Promotions.</description>
    <fields>
        <fullName>Brand__c</fullName>
        <description>INFOWELDERS</description>
        <formula>Promotion_Activity__r.Brand__r.Name</formula>
        <inlineHelpText>Brand is tied to the selected promotion activity.</inlineHelpText>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <formula>Account__r.Market__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Market</label>
        <type>Text</type>
    </fields>
    <label>Promotion</label>
    <nameField>
        <label>Promotion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/classes/project_prioritization.cls
public class project_prioritization {
    public Id projectRtId;
    public Id getProjectRtId()
    { 
    Map<String,Schema.RecordTypeInfo> rtMapByName  = Schema.SObjectType.Project_Opportunity__c.getRecordTypeInfosByName();
        //Id shiptoRecType;
        //Map<String,Schema.RecordTypeInfo> promoRTMap = Schema.SObjectType.Promotion__c.getRecordTypeInfosByName();
        if(rtMapByName.containsKey('PM - Evaluated')){
            projectRtId = rtMapByName.get('PM - Evaluated').getRecordTypeId();
            return projectRtId;
        } else{
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, 'Cannot find the record type specified.'));
            return null;
        }
    }   
    public PageReference refresh() {
        getFilter();
        return null;
    }
    
    public string Filter;
    public string getFilter()
    {
        getProjectRtId();
        Filter = 'SELECT Name, Brand__r.Name, Market__r.Name, Achievement__c, Attractiveness__c, X5_Yr_NPV__c, Category__c, Start_Date__c, End_Date__c FROM Project_Opportunity__c WHERE RecordTypeId = \''+projectRtId+'\'';
        if(selBrand!=null&&selBrand!='ALL'){
            Filter += ' AND Brand__c = \''+selBrand+'\'';
        }
        if(selMarket!=null&&selMarket!='ALL'){
            Filter += ' AND Market__c = \''+selMarket+'\'';
        }
        if(selCategory!=null&&selCategory!='ALL'){
            Filter += ' AND Category__c = \''+selCategory+'\'';
        }
        return Filter;
    } 
    
    public List<Project_Opportunity__c> Projects;
    public List<Project_Opportunity__c> Pipeline;
    
    public List<Project_Opportunity__c> getProjects()
    {
     getFilter();
     Projects = Database.query(Filter);
     return Projects;
    }
    
    public List<Project_Opportunity__c> getPipeline()
    {
     getFilter();
     Pipeline = Database.query(Filter + 'ORDER BY Category__c, Start_Date__c');
     return Pipeline;
    }
    
    public string selBrand {get;set;}
    public List<SelectOption> getBrandsList() 
    {
        getProjectRtId();
        List<SelectOption> optionList = new List<SelectOption>();
        optionList.add(new SelectOption('ALL','ALL'));
        for(Brand__c y :[Select b.Name, b.Id From Brand__c b WHERE Id IN (SELECT Brand__c FROM Project_Opportunity__c WHERE RecordTypeId = :projectRtId) ORDER BY b.Name]) {
            optionList.add(new SelectOption(y.Id,y.Name));
        }
        return optionList;
    }
    
    public string selMarket {get;set;}
    public List<SelectOption> getMarketsList() 
    {
        getProjectRtId();
        List<SelectOption> optionList = new List<SelectOption>();
        optionList.add(new SelectOption('ALL','ALL'));
        for(Market__c y :[Select m.Name, m.Id From Market__c m WHERE Id IN (SELECT Market__c FROM Project_Opportunity__c WHERE RecordTypeId = :projectRtId) ORDER BY m.Name]) {
            optionList.add(new SelectOption(y.Id,y.Name));
        }
        return optionList;
    }
    
    public string selCategory {get;set;}
    public List<SelectOption> getCategoryList() 
    {
        getProjectRtId();
        List<SelectOption> optionList = new List<SelectOption>();
        optionList.add(new SelectOption('ALL','ALL'));
        for(Project_Opportunity__c y :[SELECT Category__c FROM Project_Opportunity__c WHERE RecordTypeId = :projectRtId ORDER BY Category__c]) {
            Boolean found = false;
            for(Integer i=0; i< optionList.size(); i++){
                if(y.Category__c == optionList[i].getValue()){ 
                    found = true;
                    break;
                }
            }
            if (!found){
                optionList.add(new SelectOption(y.Category__c,y.Category__c));
            }
        }
        return optionList;
    }
    
}