B-F Backup Sandbox 30.4.12/src/objects/Brand__c.object
<CustomObject>
    <description>Used by CRM.
NPA Rollout: Used to store Brands.</description>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Market__c.object
<CustomObject>
    <description>Used by CRM.
NPA Rollout: Used to store Markets at State Level.</description>
    <fields>
        <fullName>Evaluator_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Evaluator 1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Markets2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Evaluator_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Evaluator 2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Markets3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Evaluator_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Evaluator 3</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Markets4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Evaluator_4__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Evaluator 4</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Markets5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Evaluator_5__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Evaluator 5</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Markets6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Evaluator_6__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Evaluator 6</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Markets7</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Evaluator_7__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Evaluator 7</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Markets8</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Evaluator_8__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Evaluator 8</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Markets9</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Project_Opportunity__c.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipName>Project_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Branded Line Extension (Full &amp; Mid Proof)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Single Serve</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multi-Serve</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NtW Mid-Proof</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NtW  Full-Proof</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Evaluator_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Evaluator 1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Evaluator_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Evaluator 2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Projects1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Evaluator_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Evaluator 3</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Projects2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Evaluator_4__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Evaluator 4</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Projects3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Evaluator_5__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Evaluator 5</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Projects4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Evaluator_6__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Evaluator 6</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Projects7</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Evaluator_7__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Evaluator 7</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Projects5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Evaluator_8__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Evaluator 8</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Projects6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Project_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/classes/Test_triggerUpdateProject.cls
@isTest
private class Test_triggerUpdateProject {
   static testMethod void test(){
        // Create a project
       Date startDate = Date.parse('01/01/2012');
       Date endDate = Date.parse('01/20/2012');
       Brand__c btest = new Brand__c(Name='Woodford Reserve');
       Market__c mtest = new Market__c(Name='testMarket', Evaluator_1__c='005300000046Egr');
       insert btest;
       insert mtest;
       Project_Opportunity__c testProject = new Project_Opportunity__c(Market__c=mtest.Id,Brand__c=btest.Id,Name='test',Category__c='Line Extension',Start_Date__c=startDate,End_Date__c=endDate);
       
       //insert project and run the trigger
       insert testProject;
       
       // See if the evaluators were imported
       Market__c selectedMarket = Database.Query('SELECT Name, Evaluator_1__c,Evaluator_2__c,Evaluator_3__c,Evaluator_4__c,Evaluator_5__c,Evaluator_6__c,Evaluator_7__c,Evaluator_8__c FROM Market__c WHERE Name = \'testMarket\'');
       System.AssertEquals('005300000046Egr', selectedMarket.Evaluator_1__c);
       //System.AssertEquals(testProject.Market__r.Name, selectedMarket.Name);
   }
}