B-F Backup Sandbox 30.4.12/src/objects/Degree_Declaration__c.object
<CustomObject>
    <description>Used within the Tuition Reimbursement Application</description>
    <fields>
        <fullName>Approximate_Completion_Date__c</fullName>
        <description>Enter Approximate Completion Date</description>
        <inlineHelpText>Enter Approximate Completion Date</inlineHelpText>
        <label>Approximate Completion Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Current_Cost_Per_Credit_Hour__c</fullName>
        <description>Enter Current Cost Per Credit Hour</description>
        <inlineHelpText>Enter Current Cost Per Credit Hour (currency will default to USD)</inlineHelpText>
        <label>Current Cost Per Credit Hour</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Degree_Type__c</fullName>
        <inlineHelpText>Select Degree Type</inlineHelpText>
        <label>Degree Type</label>
        <picklist>
            <picklistValues>
                <fullName>Undergraduate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Graduate</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>HR_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Select HR Manager</description>
        <inlineHelpText>Select HR Manager</inlineHelpText>
        <label>HR Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Degree_Declaration1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>I_have_read_the_Repayment_Agreement__c</fullName>
        <defaultValue>false</defaultValue>
        <description>By Checking this box you acknowledge that you have read the Repayment Agreement</description>
        <inlineHelpText>By Checking this box you acknowledge that you have read the Repayment Agreement</inlineHelpText>
        <label>I have read the Repayment Agreement</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Major__c</fullName>
        <description>Enter Major</description>
        <inlineHelpText>Enter Major</inlineHelpText>
        <label>Major</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select Manager</inlineHelpText>
        <label>Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Degree_Declaration2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number_of_Credit_Hours_Required__c</fullName>
        <description>Enter The Approximate Number Of Credit Hours Required To Complete This Degree</description>
        <inlineHelpText>Enter The Approximate Number Of Credit Hours Required To Complete This Degree</inlineHelpText>
        <label>Number of Credit Hours Required</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProgramAdminStatus__c</fullName>
        <defaultValue>&quot;Open&quot;</defaultValue>
        <label>ProgramAdminStatus</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reason_You_Wish_To_Pursue_This_Degree__c</fullName>
        <description>Enter The Reason You Wish To Pursue This Degree</description>
        <inlineHelpText>Enter The Reason You Wish To Pursue This Degree</inlineHelpText>
        <label>Reason You Wish To Pursue This Degree</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>School_Address__c</fullName>
        <description>Enter School Address</description>
        <inlineHelpText>Enter School Address</inlineHelpText>
        <label>School Address</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School_To_Be_Attended__c</fullName>
        <description>School To Be Attended</description>
        <inlineHelpText>Enter School To Be Attended</inlineHelpText>
        <label>School To Be Attended</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Enter Start Date</description>
        <inlineHelpText>Enter Start Date</inlineHelpText>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Degree Declaration</label>
    <nameField>
        <label>Degree</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Degree Declaration</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

B-F Backup Sandbox 30.4.12/src/objects/Tuition_Refund__c.object
<CustomObject>
    <description>Used in conjunction with Degree Declaration and Course Details objects to make up Tuition Reimbursement Application</description>
    <fields>
        <fullName>Degree_Declaration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Select Degree Declaration</description>
        <inlineHelpText>Select Degree Declaration</inlineHelpText>
        <label>Degree Declaration</label>
        <referenceTo>Degree_Declaration__c</referenceTo>
        <relationshipLabel>Tuition Refund</relationshipLabel>
        <relationshipName>Tuition_Reimbursement</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HR_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>HR Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Tuition_Refund1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Major__c</fullName>
        <description>Enter Major</description>
        <formula>Degree_Declaration__r.Major__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Enter Major</inlineHelpText>
        <label>Major</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Tuition_Refund2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProgramAdminStatus__c</fullName>
        <defaultValue>&quot;Open&quot;</defaultValue>
        <label>ProgramAdminStatus</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_of_other_tuition_assistance__c</fullName>
        <inlineHelpText>Enter the source of other tuition assistance you receive. Enter none if you do not receive any other tuition assistance.</inlineHelpText>
        <label>Source of other tuition assistance</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Tuition Refund</label>
    <nameField>
        <label>Semester</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tuition Refund</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

B-F Sandbox/trunk/src/classes/test_beforeInsertUpdatePrg_ManagerNames.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
//Test class for beforeInsertUpdatePrg_ManagerNames Trigger
private class test_beforeInsertUpdatePrg_ManagerNames {

    static testMethod void myUnitTest() {
        
        //Getting Profile Details
        Profile testProfile = [select id from profile where name='Default One App']; 

        //Creating a Test User
        User testUser = new User(alias = 'myTest', email='myTest@b-f.com', 
        emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US', 
        localesidkey='en_US', profileid = testProfile.id, 
        timezonesidkey='America/Los_Angeles', username='myTest@b-f.com@b-f.com');
        
        List<User> users = [SELECT Id FROM User WHERE IsActive = true AND profileid =:testProfile.id LIMIT 2];
        Id User1Id = users[0].Id;
        Id User2Id = users[1].Id;
 
        //Run as        
        System.runAs(testUser) {
        // The following code runs as user 'testUser' 
        System.debug('Current User: ' + UserInfo.getUserName());
        System.debug('Current Profile: ' + UserInfo.getProfileId()); }
        // Run some code that checks record sharing

        //creating a test Degree Declaration
        Degree_Declaration__c testDegreeDeclaration = new Degree_Declaration__c(
        School_To_Be_Attended__c = 'Splading University', 
        School_Address__c = 'Louisville, KY',
        Name = 'MBA',
        Major__c = 'Business Administration',
        Start_date__c = Date.parse('10/04/2011'),
        Approximate_Completion_Date__c = Date.parse('06/30/2013'),
        Number_of_Credit_Hours_Required__c = double.valueOf('48'),
        Current_Cost_per_Credit_Hour__c = double.valueOf('500'),
        Degree_Type__c = 'Graduate',
        HR_Manager__c = user2Id,
        Manager__c = user1Id,
        Reason_You_Wish_To_Pursue_This_Degree__c = 'Career Advancement',
        I_Have_Read_The_Repayment_Agreement__c = True, 
        ProgramAdminStatus__c = 'Closed');
                
        insert testDegreeDeclaration ;

        //creating a test Tuition Refund
        Tuition_Refund__c testTuitionRefund = new Tuition_Refund__c(
        Name = 'Summer 2011', 
        Degree_Declaration__c = testDegreeDeclaration.Id,
        Source_of_Other_Tuition_Assistance__c = 'None');
        
        insert testTuitionRefund ;
  
    }
}