B-F Backup Sandbox 30.4.12/src/objects/Vendor__c.object
<CustomObject>
    <customHelpPage>vendorHelp</customHelpPage>
    <description>Vendor Master</description>
    <fields>
        <fullName>Country_LAND1__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>AD - Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AE - Utd.Arab.Emir.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AF - Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AG - Antigua&amp;Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AI - Anguilla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL - Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AM - Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AN - Dutch Antilles</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO - Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AQ - Antarctica</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR - Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS - Samoa,American</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AT - Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AU - Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AW - Aruba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ - Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BA - Bosnia-Herz.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BB - Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BD - Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BE - Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BF - Burkina-Faso</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BG - Bulgaria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BH - Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BI - Burundi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BJ - Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BM - Bermuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BN - Brunei Dar-es-S</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BO - Bolivia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BR - Brazil</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BS - Bahamas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US - USA</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Vendor Request</label>
    <nameField>
        <displayFormat>VENDOR-{0000}</displayFormat>
        <label>Vendor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Request</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/classes/vendorClass.cls
public with sharing class vendorClass {
  private final Vendor__c vendor;
  public String countryID {get;set;} 
  public String reqTrueFalse {get;set;}
  public String selectedCountry {get;set;} 
  String defVal = 'US - USA';
        
  public vendorClass(ApexPages.StandardController vendorController) {
    this.vendor = (Vendor__c)vendorController.getRecord();
  }
  
  public List<SelectOption> getCountries() {
    List<SelectOption> options = new List<SelectOption>();
    Schema.DescribeFieldResult fieldResult = Vendor__c.Country_LAND1__c.getDescribe();
    List<Schema.PicklistEntry> countryList = fieldResult.getPicklistValues();
        
    for( Schema.PicklistEntry c : countryList) {
      options.add(new SelectOption(c.getLabel(), c.getValue()));
    }         
    return options;
  } 

  public PageReference autoRun() {
    countryID = defVal; //ApexPages.currentPage().getParameters().get('ddlCountry');
    RequiredFields();
    return null;
  }

  //public void returnCountry() {
  public PageReference returnCountry() {
  	countryID = selectedCountry; 
  	//countryID = ApexPages.currentPage().getParameters().put('country',selectedCountry);   
    RequiredFields();
    return null;
    
    //PageReference pageRef = Page.vendorRequestForm;
    //pageRef.getParameters().put('Country__c',selectedCountry);
    //pageRef.setRedirect(true);
    //return pageRef;
  }
  
  public void RequiredFields() {
    if (countryID == defVal) {
      this.reqTrueFalse = 'true';
    }   
    else {
      this.reqTrueFalse = 'false';
    }
  }      
}