B-F Sandbox Full-Backup/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Channel__c</fullName>
        <description>INFOWELDERS</description>
        <label>Channel</label>
        <picklist>
            <picklistValues>
                <fullName>On</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Sellable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wholesaler</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sub_Wholesaler</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INTEG MAINLY ON</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INTEG MAINLY OFF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ON PREMISE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OFF PREMISE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INTEGRATED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NON RETAIL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UNCLASSIFIED</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used by CRM.
NPA Rollout: Used to store the Market reference.</description>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>INFOWELDERS</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Former</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Potential</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Telesales</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>EUR_Outlets</fullName>
        <active>true</active>
        <description>European - Outlets</description>
        <label>EUR - Outlets</label>
    </recordTypes>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Market__c.object
<CustomObject>
    <description>Used by CRM.
NPA Rollout: Used to store Markets at State Level.</description>
    <fields>
        <fullName>Market_Code__c</fullName>
        <description>Used to store technical code for respective markets</description>
        <externalId>true</externalId>
        <label>Market Code</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Off_Channel__c</fullName>
        <description>This field is used by the Outlet Visit page to determine what grid-layout to use in the B-F and Competitor Brands sections. This Off Channel references the value selected in the related Account.Channel__c field value.</description>
        <inlineHelpText>Used by the Outlet Visit page to determine what grid-layout to use in the B-F and Competitor Brands sections. This &quot;Off Channel&quot; references the value in the related Account.Channel__c field value.
1-Standard Layout
2-Euro Off
3-Euro On</inlineHelpText>
        <label>Off Channel</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>On_Channel__c</fullName>
        <description>This field is used by the Outlet Visit page to determine what grid-layout to use in the B-F and Competitor Brands sections. This On Channel references the value selected in the related Account.Channel__c field value.</description>
        <inlineHelpText>Used by the Outlet Visit page to determine what grid-layout to use in the B-F and Competitor Brands sections. This &quot;On Channel&quot; references the value in the related Account.Channel__c field value.
1-Standard Layout
2-Euro Off
3-Euro On</inlineHelpText>
        <label>On Channel</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Outlet_Visit__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Outlet (Account)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Outlet Visits</relationshipLabel>
        <relationshipName>Outlet_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Visit__c</fullName>
        <defaultValue>false</defaultValue>
        <description>P00001  - Created by PARX to improve reporting on Last Visits</description>
        <label>Last Visit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Met_With__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Met With (Contact)</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Outlet Visits</relationshipLabel>
        <relationshipName>Outlet_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Next_to_Last_Visit__c</fullName>
        <defaultValue>false</defaultValue>
        <description>P00001  - Created by PARX to improve reporting on Last Visits</description>
        <label>Next to Last Visit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Visit_Date__c</fullName>
        <label>Visit Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Outlet Visit</label>
    <nameField>
        <displayFormat>OV-{00000}</displayFormat>
        <label>Outlet Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outlet Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

B-F Sandbox/trunk/src/classes/Test_Outlet_Visit_Helper.cls
/**
 *Trigger on all events
 *Conditions: 
 *	+Account RecordType: EUR_Outlets (or "DEU_Outlets")
 *	+Status__c is 'Complete'
 *
 * We refresh always all the rows of the account to make sure everything is fine for every event.
 * We sort the retrieved records from the Account by Visit_Date__c. The last Visit_Date__c record gets the 
 * Last_Visit__c true. The next gets the field Next_to_Last_Visit__c true and Last_Visit__c to false
 * and all other records are set back to false.
 * 			
 * @date	28.11.2011
 * @author 	Christophe Vidal
**/
@isTest
private class Test_Outlet_Visit_Helper {

    static testMethod void TestSettingOfLastVisit() {
    	RecordType RT = [select id from RecordType where sObjectType = 'Account' AND developerName = 'EUR_Outlets' limit 1];
    	Market__c market = new Market__c(Market_Code__c = 'GER', Name = 'Germany', Off_Channel__c = '1', On_Channel__c = '1');
        insert market;
        Account acc = new Account(Name = 'PARX', Market__c = market.Id, RecordTypeId = RT.Id, Channel__c = 'On', BillingCountry = 'DE');
        insert acc;
        Contact con = new Contact(LastName = 'Roger', AccountId = acc.Id);
        insert con;
        
        test.startTest();
	        Outlet_Visit__c outlet = new Outlet_Visit__c(Visit_Date__c = system.today());
	        outlet.Account__c = acc.Id;
	        outlet.Met_With__c = con.Id;
	        insert outlet;
	        system.assertEquals(false, outlet.Last_Visit__c);
	        system.assertEquals(false, outlet.Next_to_Last_Visit__c);
	        
	        Outlet_Visit_Helper.hasAlreadyRun = false;
	        outlet.Status__c = 'Complete';
	        update outlet;
	        outlet = [select Last_Visit__c, Next_to_Last_Visit__c from Outlet_Visit__c where Id =: outlet.Id];
	        system.assertEquals(true, outlet.Last_Visit__c);
	        system.assertEquals(false, outlet.Next_to_Last_Visit__c);
	        
	        Outlet_Visit_Helper.hasAlreadyRun = false;
	        Outlet_Visit__c outlet2 = new Outlet_Visit__c(Visit_Date__c = system.today().addMonths(1));
	        outlet2.Account__c = acc.Id;
	        outlet2.Met_With__c = con.Id;
	        outlet2.Status__c = 'Complete';
	        insert outlet2;
	        outlet = [select Last_Visit__c, Next_to_Last_Visit__c from Outlet_Visit__c where Id =: outlet.Id];
	        outlet2 = [select Last_Visit__c, Next_to_Last_Visit__c from Outlet_Visit__c where Id =: outlet2.Id];
	        system.assertEquals(false, outlet.Last_Visit__c);
	        system.assertEquals(true, outlet.Next_to_Last_Visit__c);
	        system.assertEquals(true, outlet2.Last_Visit__c);
	        system.assertEquals(false, outlet2.Next_to_Last_Visit__c);
	        
	        Outlet_Visit_Helper.hasAlreadyRun = false;
	        Outlet_Visit__c outlet3 = new Outlet_Visit__c(Visit_Date__c = system.today().addMonths(2));
	        outlet3.Account__c = acc.Id;
	        outlet3.Met_With__c = con.Id;
	        outlet3.Status__c = 'Complete';
	        insert outlet3;
	        outlet = [select Last_Visit__c, Next_to_Last_Visit__c from Outlet_Visit__c where Id =: outlet.Id];
	        outlet2 = [select Last_Visit__c, Next_to_Last_Visit__c from Outlet_Visit__c where Id =: outlet2.Id];
	        outlet3 = [select Last_Visit__c, Next_to_Last_Visit__c from Outlet_Visit__c where Id =: outlet3.Id];
	        system.assertEquals(false, outlet.Last_Visit__c);
	        system.assertEquals(false, outlet.Next_to_Last_Visit__c);
	        system.assertEquals(false, outlet2.Last_Visit__c);
	        system.assertEquals(true, outlet2.Next_to_Last_Visit__c);
	        system.assertEquals(true, outlet3.Last_Visit__c);
	        system.assertEquals(false, outlet3.Next_to_Last_Visit__c);
	        
	        Outlet_Visit_Helper.hasAlreadyRun = false;
	        delete outlet2;
	        outlet = [select Last_Visit__c, Next_to_Last_Visit__c from Outlet_Visit__c where Id =: outlet.Id];
	        outlet3 = [select Last_Visit__c, Next_to_Last_Visit__c from Outlet_Visit__c where Id =: outlet3.Id];
	        system.assertEquals(false, outlet.Last_Visit__c);
	        system.assertEquals(true, outlet.Next_to_Last_Visit__c);
	        system.assertEquals(true, outlet3.Last_Visit__c);
	        system.assertEquals(false, outlet3.Next_to_Last_Visit__c);
        test.stopTest();
    }
}