B-F Sandbox Full-Backup/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Group_Promotion__c</fullName>
        <label>Group Promotion</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used by CRM.
NPA Rollout: Used to store the Market reference.</description>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Group_Promotion_Item__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Group_Promotion_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Group_Promotion__c</fullName>
        <label>Deal</label>
        <referenceTo>Group_Promotions__c</referenceTo>
        <relationshipLabel>Deal Items</relationshipLabel>
        <relationshipName>Group_Promotion_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Deal Item</label>
    <nameField>
        <displayFormat>GPI-{0}</displayFormat>
        <label>Group Promotion Item  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Group_Promotions__c.object
<CustomObject>
    <description>Group Promotion (Banner Group)</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Group_Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>Deal-{0}</displayFormat>
        <label>Deal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Market__c.object
<CustomObject>
    <description>Used by CRM.
NPA Rollout: Used to store Markets at State Level.</description>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/classes/DealItem_Redirect_Controller.cls
public with sharing class DealItem_Redirect_Controller {
	Group_Promotion_Item__c oi;
	
	public DealItem_Redirect_Controller(ApexPages.StandardController controller) {
		this.oi = (Group_Promotion_Item__c)controller.getRecord();
		this.oi = [SELECT Group_Promotion__c, Group_Promotion__r.Account__c, Group_Promotion__r.RecordTypeId, Group_Promotion__r.Account__r.Market__r.Name FROM Group_Promotion_Item__c WHERE Id =:oi.Id];
	}
	
	public PageReference Redirect() {
		PageReference ref = Page.dealItem;
		ref.getParameters().put('Id', oi.Group_Promotion__c);
		return ref;
	}
}