B-F Sandbox Full-Backup/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <description>FDC-GD</description>
        <inlineHelpText>Enter Comments</inlineHelpText>
        <label>Comments</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used by CRM.
NPA Rollout: Used to store the Market reference.</description>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Market__c.object
<CustomObject>
    <description>Used by CRM.
NPA Rollout: Used to store Markets at State Level.</description>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Product_Launch__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Product Launch</relationshipLabel>
        <relationshipName>Product_Launch</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Survey_Date__c</fullName>
        <label>Survey Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Week__c</fullName>
        <label>Visits</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Product Launch</label>
    <nameField>
        <displayFormat>PL-{0}</displayFormat>
        <label>Product Launch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Launch</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

B-F Backup Sandbox 30.4.12/src/objects/Product_Launch_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Counter__c</fullName>
        <label>Counter</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Launch__c</fullName>
        <label>Product Launch</label>
        <referenceTo>Product_Launch__c</referenceTo>
        <relationshipLabel>Product Launch Details</relationshipLabel>
        <relationshipName>Product_Launch_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Survey_Date__c</fullName>
        <label>Survey Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Week__c</fullName>
        <label>Week</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <label>Product Launch Detail</label>
    <nameField>
        <displayFormat>PLD-{0}</displayFormat>
        <label>Product Launch Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Launch Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <description>Additional Information if any can be entered here.</description>
        <inlineHelpText>Enter Additional Information here</inlineHelpText>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <description>INFOWELDERS - These text values MUST match the Market Name records&apos; text values.
NPA Rollout: Used to store the markets a user is allocated to. Multiple values can be used separated by semi-colon.</description>
        <inlineHelpText>CRM: Market at a Country level-  such as Germany, Korea, India, Japan etc.
NPA: Market at a State level-  such as Illinois, Kentucky etc.</inlineHelpText>
        <label>Market</label>
        <picklist>
            <picklistValues>
                <fullName>ALL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Germany</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Japan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Korea</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thailand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Taiwan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>India</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canada General</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

B-F Sandbox/trunk/src/classes/Test_Product_Launch.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class Test_Product_Launch {

    static testMethod void myUnitTest() {
        // TO DO: implement unit test
        
        //Getting Profile Details
 Profile testProfile = [select id from profile where name='Standard User']; 
 
 

 
 //Creating a Test User
 User testUser = new User(alias = 'myTest', email='myTest@b-f.com', 
            emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US', 
            localesidkey='en_US', profileid = testProfile.id, 
            timezonesidkey='America/Los_Angeles', username='myTest@b-f.com@b-f.com',market__c = 'China');
 
//Run as        
 System.runAs(testUser) {
           // The following code runs as user 'testUser' 
           System.debug('Current User: ' + UserInfo.getUserName());
           System.debug('Current Profile: ' + UserInfo.getProfileId()); }
           // Run some code that checks record sharing
        


//Create an Account

Account testAccount = new Account (name = 'myBar');

insert testAccount;


Product_Launch__c testProductLaunch = new Product_Launch__c (comments__c = 'test', Account__c = testAccount.id);

insert testProductLaunch; 

Product_Launch_detail__c testProductLaunchDetail = [SELECT Id, Counter__c, week__c,Survey_Date__c FROM Product_Launch_Detail__c where Product_Launch__c =:testProductLaunch.id];

system.debug(testProductLaunchDetail);

update testProductLaunchDetail;

Product_Launch_detail__c testProductLaunchDetail2 = new Product_Launch_detail__c(Product_Launch__c = testProductLaunch.id );

insert testProductLaunchDetail2;

delete testProductLaunchDetail;


        
    }
}