B-F Sandbox Full-Backup/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>INFOWELDERS</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Former</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Potential</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Telesales</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subgroup__c</fullName>
        <description>INFOWELDERS</description>
        <label>Subgroup</label>
        <picklist>
            <controllingField>Group__c</controllingField>
            <picklistValues>
                <fullName>Adult Entertainment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agency/Vendor Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Res.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Authentic Bar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Basic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beach Club</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beer Bar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cabacra Bar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cafe/Deli</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Casino / Gambling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Casual Dining</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Casual Night Club / Roadhouse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caterer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chinese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coffee Shop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conventional Liquor Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Country Western</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CVS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Darts Bar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Day</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Depart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dinning Bar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disco</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disco Club</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discount Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duty Free</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ethnic Res.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event/ Live Bar</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>INFOWELDERS</description>
        <label>Supplier</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts (As Supplier)</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Account_Brand__c.object
<CustomObject>
    <description>INFOWELDERS - Brands Related to this Account</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>INFOWELDERS</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Brands</relationshipLabel>
        <relationshipName>Account_Brands</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>INFOWELDERS</description>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>Account Brands</relationshipLabel>
        <relationshipName>Account_Brands</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Goal__c</fullName>
        <description>INFOWELDERS</description>
        <label>Goal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <formula>Brand__r.Supplier__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Supplier</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>of_Forecast__c</fullName>
        <formula>Depletion_Actuals__c / Forecast__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>% of Forecast</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>of_Goal__c</fullName>
        <description>INFOWELDERS</description>
        <formula>Depletion_Actuals__c / Goal__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>% of Goal</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <label>Account Brand</label>
    <nameField>
        <displayFormat>AB-{0000000}</displayFormat>
        <label>Account Brands Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Brands</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

B-F Backup Sandbox 30.4.12/src/objects/Brand__c.object
<CustomObject>
    <description>Used by CRM.
NPA Rollout: Used to store Brands.</description>
    <fields>
        <fullName>Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Infowelders:Used by CRM.
NPA Rollout: Used to refer to Supplier.</description>
        <label>Supplier</label>
        <referenceTo>Supplier__c</referenceTo>
        <relationshipLabel>Brands</relationshipLabel>
        <relationshipName>Brands</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

B-F Backup Sandbox 30.4.12/src/objects/Key_Task__c.object
<CustomObject>
    <fields>
        <fullName>Outlet_Visit__c</fullName>
        <label>Outlet Visit</label>
        <referenceTo>Outlet_Visit__c</referenceTo>
        <relationshipLabel>Key Tasks</relationshipLabel>
        <relationshipName>Key_Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Key Task</label>
    <nameField>
        <label>Key Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Key Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

B-F Backup Sandbox 30.4.12/src/objects/Mandatory_Products__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <description>Infowelders</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Mandatory Products</relationshipLabel>
        <relationshipName>Mandatory_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Mandatory Product</label>
    <nameField>
        <displayFormat>MP-{000000}</displayFormat>
        <label>Mandatory Products Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mandatory Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Outlet_Visit__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Outlet (Account)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Outlet Visits</relationshipLabel>
        <relationshipName>Outlet_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Visit_Comments__c</fullName>
        <label>Visit Comments</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Outlet Visit</label>
    <nameField>
        <displayFormat>OV-{00000}</displayFormat>
        <label>Outlet Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outlet Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Product__c.object
<CustomObject>
    <description>NPA Rollout: Object for storing Products used in National Promotion application.
Product Remediation : Replicated all standard product fields here.</description>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Infowelders, NPA Rollout: Used to store the related Brand</description>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipName>Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>NPA Rollout: Used to store status of Product
0 = Active
1 = Cancelled</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Promotion__c.object
<CustomObject>
    <description>Used by CRM.
NPA Rollout: Used to store Promotions.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Infowelders</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Promotions</relationshipLabel>
        <relationshipName>Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <description>INFOWELDERS</description>
        <formula>Promotion_Activity__r.Brand__r.Name</formula>
        <inlineHelpText>Brand is tied to the selected promotion activity.</inlineHelpText>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Promotion_Activity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Infowelders</description>
        <label>Promotion Activity</label>
        <referenceTo>Promotion_Activity__c</referenceTo>
        <relationshipLabel>Promotions</relationshipLabel>
        <relationshipName>Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Promotion</label>
    <nameField>
        <label>Promotion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Promotion_Activity__c.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Infowelders</description>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>Promotion Activities</relationshipLabel>
        <relationshipName>Promotion_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Preliminary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Live</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Promotion Activity</label>
    <nameField>
        <label>Promotion Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promotion Activities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

B-F Sandbox/trunk/src/classes/AccountFactsheet.cls
public without sharing class AccountFactsheet {

    /** Button on Account should present a Factsheet.
    * Visual Force Page to show the most relevant information for one Account on max. 2 DIN A4 pages
    * Relevant objects are:
    * - Account (Address, Contact Names...)
    * - last visit comments 
    * - Account Brand
    * - Mandatory Products 
    * - Promotions (Sum of Promotion Totals: Total Gross Profit, Total Promotion Cost (r), Total Brand Profit (f)
    * - Promotion Activities with the same Subgroup (active and included between start and end date.)
    **/
    
    public Account account{get;set;} 
    public list<Contact> contact{get;set;}
    public list<Outlet_Visit__c> Outlet_Visit{get;set;}
    public list<Account_Brand__c> Account_Brand{get;set;}
    public list<Mandatory_Products__c> Mandatory_Products{get;set;}
    public String Currenc {get;set;} 
    public Double Total_Margin{get;set;}
    public Double Total_Promotion_Cost{get;set;}
    public Double Total_Brand_Profit{get;set;}
    public list<Promotion_Activity__c> Promotion_Activity{get;set;}
    public list<Key_Task__c> Key_Task{get;set;}
     
    public AccountFactsheet () {
        String AccountId = ApexPages.currentPage().getParameters().get('AccountId');
        if(AccountId != null && AccountId.length() >=15 && AccountId.substring(0,3) == '001') {
            account = [select Name, BillingStreet, BillingPostalCode, BillingCity, BillingCountry, Subgroup__c, Phone, Fax  from Account where Id =:AccountId];
            contact = new list<Contact>([select salutation, LastName, FirstName, Email from Contact where AccountId =: account.Id]);
            Outlet_Visit = new list<Outlet_Visit__c>([select Visit_Comments__c, LastModifiedDate from Outlet_Visit__c where Status__c = 'Complete' AND Account__c =: AccountId order by LastModifiedDate desc]);
            Account_Brand = new list<Account_Brand__c>([select of_Forecast__c, of_Goal__c, Goal__c, Brand__r.Name, Supplier__c, Goal_Gauge__c from Account_Brand__c where Account__c =: AccountId order by Brand__r.Name asc]);
            Mandatory_Products = new list<Mandatory_Products__c>([select Custom_Product__r.Name, Product_Status__c from Mandatory_Products__c where Account__c =: AccountId]);
            Total_Margin = Total_Promotion_Cost = Total_Brand_Profit = 0;
            list<Id> PromotionActivityIds = new list<Id>();
            for(Promotion__c promo:[select CurrencyIsoCode, Total_Margin__c, Total_Promotion_Cost__c, Total_Brand_Profit__c, Promotion_Activity__c  from Promotion__c where Account__c =: AccountId]) {
                Total_Margin += promo.Total_Margin__c;
                Total_Promotion_Cost += promo.Total_Promotion_Cost__c;
                Total_Brand_Profit += promo.Total_Brand_Profit__c;
                Currenc = promo.CurrencyIsoCode;
                PromotionActivityIds.add(promo.Promotion_Activity__c);
            }
            Promotion_Activity = new list<Promotion_Activity__c>([select Name, Description__c from Promotion_Activity__c where Id NOT IN: PromotionActivityIds AND Begin_Date__c <=: system.today() AND End_Date__c >=: system.today() and Active__c = true AND Subgroup_Germany__c =: account.Subgroup__c ]);
            Key_Task = new list<Key_Task__c>([select Name, Outlet_Visit__r.Visit_Date__c from Key_Task__c where Outlet_Visit__c IN: Outlet_Visit limit 3]);
        }
    }
}