B-F Sandbox Full-Backup/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Australia/Wombat Use</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used by CRM.
NPA Rollout: Used to store the Market reference.</description>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>INFOWELDERS</description>
        <label>Supplier</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts (As Supplier)</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Account_Wholesaler__c.object
<CustomObject>
    <description>Wholesales Junction Object</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Wholesalers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Checked is active</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Wholesaler__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Wholesaler</label>
        <referenceTo>Wholesaler__c</referenceTo>
        <relationshipName>Wholesaler</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Wholesaler</label>
    <nameField>
        <displayFormat>WHSL-{0}</displayFormat>
        <label>Account Wholesaler</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Wholesalers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

B-F Backup Sandbox 30.4.12/src/objects/Brand__c.object
<CustomObject>
    <description>Used by CRM.
NPA Rollout: Used to store Brands.</description>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Checked is active.</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Spirit_Type__c</fullName>
        <description>Infowelders</description>
        <label>Spirit Type</label>
        <picklist>
            <picklistValues>
                <fullName>Bourbon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canadian / Blend</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scotch / Irish</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Liquers / Cordials</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rum / Gin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tequila</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vodka</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wine</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Infowelders:Used by CRM.
NPA Rollout: Used to refer to Supplier.</description>
        <label>Supplier</label>
        <referenceTo>Supplier__c</referenceTo>
        <relationshipLabel>Brands</relationshipLabel>
        <relationshipName>Brands</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>ORD-{0}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <recordTypes>
        <fullName>New</fullName>
        <active>true</active>
        <description>New</description>
        <label>New</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Order_Item__c.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BF - Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>Order_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>Order_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BF - Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>Order_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wholesaler__c</fullName>
        <description>Wholesaler (Link to the Wholesaler Product) Object</description>
        <formula>Order__r.Wholesaler_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Wholesaler (Link to the Wholesaler Product) Object</inlineHelpText>
        <label>ECC - Wholesaler</label>
        <type>Text</type>
    </fields>
    <label>Order Item</label>
    <nameField>
        <displayFormat>ORD_ITM-{0}</displayFormat>
        <label>Order Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <recordTypes>
        <fullName>New</fullName>
        <active>true</active>
        <description>New</description>
        <label>New</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Product__c.object
<CustomObject>
    <description>NPA Rollout: Object for storing Products used in National Promotion application.
Product Remediation : Replicated all standard product fields here.</description>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Infowelders, NPA Rollout: Used to store the related Brand</description>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipName>Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Product Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created as a part of product remediation</description>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>ProductsCustom</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pricing_Reference_Material__c</fullName>
        <label>Price Ref Material</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductCode__c</fullName>
        <description>NPA Rollout: Used to store the product code of the POS item.</description>
        <externalId>true</externalId>
        <label>Product Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <description>NPA Rollout: Stores the product code</description>
        <label>Product Unique Key</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <description>Created as a part of product remediation</description>
        <formula>Brand__r.Supplier__r.Name</formula>
        <label>Supplier</label>
        <type>Text</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Supplier__c.object
<CustomObject>
    <description>Used by CRM. 
NPA Rollout: Used to store Suppliers.</description>
    <fields>
        <fullName>Is_B_F_Brand__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box if this Supplier record is considered a B-F brand.</description>
        <inlineHelpText>Check this box if this Supplier record is considered a B-F brand.</inlineHelpText>
        <label>Is B-F Brand?</label>
        <type>Checkbox</type>
    </fields>
    <label>Supplier</label>
    <nameField>
        <label>Supplier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Market__c</fullName>
        <description>INFOWELDERS - These text values MUST match the Market Name records&apos; text values.
NPA Rollout: Used to store the markets a user is allocated to. Multiple values can be used separated by semi-colon.</description>
        <inlineHelpText>CRM: Market at a Country level-  such as Germany, Korea, India, Japan etc.
NPA: Market at a State level-  such as Illinois, Kentucky etc.</inlineHelpText>
        <label>Market</label>
        <picklist>
            <picklistValues>
                <fullName>ALL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Germany</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Japan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Korea</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thailand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Taiwan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>India</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canada General</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Wholesaler__c.object
<CustomObject>
    <description>Australia Wholesaler Object</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Wholesalers</relationshipLabel>
        <relationshipName>Wholesalers1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Checked is active</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Wholesalers</relationshipLabel>
        <relationshipName>Wholesalers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SAP_Number__c</fullName>
        <externalId>true</externalId>
        <label>SAP Number</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Wholesaler</label>
    <nameField>
        <label>Wholesaler</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wholesalers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Wholesaler_Product__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Wholesaler Products</relationshipLabel>
        <relationshipName>Wholesaler_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wholesaler__c</fullName>
        <description>This the Account Wholesaler &quot;Key&quot; number</description>
        <inlineHelpText>This the Account Wholesaler &quot;Key&quot; number</inlineHelpText>
        <label>Wholesaler</label>
        <referenceTo>Wholesaler__c</referenceTo>
        <relationshipLabel>Wholesaler Product&apos;s</relationshipLabel>
        <relationshipName>Wholesaler_Product_s</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Wholesaler Product</label>
    <nameField>
        <label>Wholesaler Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wholesaler Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

B-F Sandbox/trunk/src/classes/Test_orderItem_Contoller.cls
/* Class Name : Test_OrderItem_Controller
* Description: Test class to test the order item controller
* Created By : Tass Tsakiridis
* Created On : 17th April 2012
*
* Modification Log :  
* ----------------------------------------------------------------------------------------------------------------------------
* Developer       Date              Description
* ----------------------------------------------------------------------------------------------------------------------------
*/ 
@isTest
private class Test_orderItem_Contoller {
	static testMethod void orderItem_Controller_Coverage() {
        INFW_TestHelper helper = new INFW_TestHelper();
        User u1 = helper.createUser();
        Profile[] p1 = [select id from Profile where Name = 'System Administrator' LIMIT 1];
        //Profile[] p1 = [SELECT Id FROM Profile WHERE Name = 'AUD-Customer Service (Platform)'];        
        u1.ProfileID = p1[0].id;      
        u1.Market__c = 'Australia';
        insert u1;		
        
		// SOQL Query for Order & Order_Item Record Type Data
		RecordType p_rt = [SELECT r.Name, r.Id FROM RecordType r WHERE r.Name = 'Wet Goods' AND SObjectType = 'Product__c'];       
        RecordType o_rt = [SELECT r.Name, r.Id FROM RecordType r WHERE  r.Name = 'New' AND SObjectType = 'Order__c'];
        RecordType oi_rt = [SELECT r.Name, r.Id FROM RecordType r WHERE r.Name = 'New' AND SObjectType = 'Order_Item__c'];
        
        // Test Data for Supplier
        Supplier__c s = new Supplier__c();
        s.Name = 'test Supplier';
        s.Is_B_F_Brand__c = true;
        insert s;
        
        // Test Data for Brand
        Brand__c b = new Brand__c();
        b.Supplier__c = s.Id;
        b.Spirit_Type__c = 'Bourbon';
        b.Name = 'Jazza Daniels';
        insert b;
        
		// Test Data for Market
		List<Market__c> markets = [SELECT Id FROM Market__c WHERE Name = 'Australia'];

	
		List<Product__c> pList = new List<Product__c>();
		
		for(integer x = 0; x < 3; x++) {
			Product__c p = new Product__c();
			p.Name = 'TestOrderProduct_' + x;
			p.IsActive__c = true;
			p.RecordTypeId = p_rt.Id;
			p.Market__c = markets[0].Id;
			p.Brand__c = b.Id;
			p.Description__c = p.Name;
			p.ProductCode__c = 'LEG-' + x;
			p.Pricing_Reference_Material__c = 'prm0001';
			pList.add(p);
		}
		insert pList;
		
        
        system.runas(u1) {
	        Account a = new Account();
        	a.Name = 'Test Account';
        	a.Market__c = markets[0].Id;
        	System.debug('[testOrderItemController] market: ' + a.Market__c);
        	insert a;
        	 
        	 Contact c = new Contact();
        	 c.AccountId = a.Id;
        	 c.FirstName = 'Test';
        	 c.LastName = 'Contact';
        	 insert c;
        	 
        	 Wholesaler__c w = new Wholesaler__c();
        	 w.Name = 'Test Wholesaler';
        	 w.Account__c = a.Id;
        	 w.SAP_Number__c = 'ECC1234';
        	 w.Is_Active__c = true;
        	 insert w;
        	 
        	 Price_Tolerance__c pt = new Price_Tolerance__c();
        	 pt.Max_PA_Per_Case__c = 10;
        	 pt.PRM_Units_Per_Case__c = 12;
        	 pt.Price_Ref_Material__c = 'prm0001';
        	 pt.Banner_Partner__c = 'bp001';
        	 insert pt;
        	 
        	 Account_Wholesaler__c aw = new Account_Wholesaler__c();
        	 aw.Account__c = a.Id;
        	 aw.Wholesaler__c = w.Id;
        	 aw.Wholesaler_Account_Number__c = 'WAN-1234';
        	 aw.Wholesaler_Account_Name__c = 'Test Account for Test W/Saler';
        	 aw.Banner_Partner__c = pt.Banner_Partner__c;
        	 insert aw;

        	 Wholesaler_Product__c wp1 = new Wholesaler_Product__c();
        	 wp1.Name = 'wp_Product_0';
        	 wp1.SAP_Material_Number__c = 'SAPMN001';
        	 wp1.Wholesaler__c = w.Id;
        	 wp1.Product__c = pList[0].Id;
        	 insert wp1;
        	 
        	 Wholesaler_Product__c wp2 = new Wholesaler_Product__c();
        	 wp2.Name = 'wp_Product_2';
        	 wp2.SAP_Material_Number__c = '';
        	 wp2.Wholesaler__c = w.Id;
        	 wp2.Product__c = plist[2].Id;
        	 insert wp2;
        	 
        	 Order__c ord = new Order__c();
        	 ord.Account__c = a.Id;
        	 ord.RecordTypeId = o_rt.Id;
        	 ord.Contact__c = c.Id;
        	 ord.Order_Type__c = 'In-Direct';
        	 ord.Status__c = 'New';
        	 ord.Wholesalers__c = aw.Id;
        	 insert ord;
        	 
        	 Order_Item__c oi1 = new Order_Item__c();
        	 oi1.Order__c = ord.Id;
        	 oi1.Product__c = pList[0].Id;
        	 oi1.Carton__c = 1;
        	 insert oi1;
        	 
        	 
        	 ApexPages.currentPage().getParameters().put('Id', ord.Id);
        	 test.startTest();
        	 
        	 ApexPages.Standardcontroller sc = new ApexPages.Standardcontroller(ord);
        	 OrderItem_Controller controller = new OrderItem_Controller(sc);
        	 controller.myOrder = ord;
        	 
        	 List<SelectOption> myBrandsList = controller.getBFBrandsList();
        	 System.debug('number of brands in list: ' + myBrandsList.size());
        	 
			 controller.bfBrandValue = b.Id;
			 controller.filterAction();
			 System.debug('prodselection.size; ' + controller.ProdSelection.size());
			 //System.assert(controller.ProdSelection.size() == 10);			
			 
			 controller.ProductNameTextValue = 'TestOrderProduct';
			 controller.filterAction();
			 
			 controller.ProductCodeTextValue = 'LEG';
			 controller.filterAction();
			 
			 controller.DescriptionTextValue = 'TestOrder';
			 controller.filterAction();
			 
			 controller.bfBrandTextValue = 'Jazza';
			 controller.filterAction();
			 //System.assert(controller.ProdSelection.size() == 10);
			 
			 // Test lineItemWrapper class
			 OrderItem_Controller.lineItemWrapper liw = new OrderItem_Controller.lineItemWrapper();
			 OrderItem_Controller.lineItemWrapper liw1 = new OrderItem_Controller.lineItemWrapper(ord, null, pList[0]);
			 System.assert(liw1.carton == 0);
			 System.assert(liw1.unit == 0);
			 System.assert(liw1.discount == 0);
			 System.assert(liw1.bonusCarton == 0);
			 System.assert(liw1.bonusUnit == 0);
			 
			 controller.ProdSelection.clear();
			 List<OrderItem_Controller.productWrapper> pwList = new List<OrderItem_Controller.productWrapper>();
		     OrderItem_Controller.productWrapper pw = new OrderItem_Controller.productWrapper(pList[0]);
		     OrderItem_Controller.productWrapper pw1 = new OrderItem_Controller.productWrapper(pList[1]);
		     pwList.add(pw);
		     
		     controller.ProdSelection.add(pw);
		     controller.ProdSelection.add(pw1);
			 controller.addProducts();
			 System.debug('[test_oictrl] myorderitems.size: ' + controller.myOrderItems.size());
			 
			 //System.assert(controller.myOrderItems.size() == 1);
			 
			 //controller.filterAction();
			 controller.BuildLineItems();
			 //System.assert(controller.myOrderItems.size() == 11);

			 controller.myOrderItems.clear();
			 
			 OrderItem_Controller.lineItemWrapper liw2 = new OrderItem_Controller.lineItemWrapper(ord, null, pList[1]);
			 controller.myOrderItems.add(liw2);
			 
			 liw1.selected = true;
			 liw1.orderItem.Wholesaler_Product__c = wp1.Id;
			 controller.myOrderItems.add(liw1);

			 controller.removeOrderItems();
			 	//System.assert(controller.myOrderItems.size() == 9);			 	

			 liw.orderItem.Carton__c = 1;			 
			 controller.saveAction();
			 if (ApexPages.getMessages().size() > 0) {
			 	System.debug('Error saving order ' + ord.Id + ' [' + ord.Name + ']');
			 } else {
			 	//List<Order_Item__c> items = [SELECT Id FROM Order_Item__c WHERE Order__c = :ord.Id];
			 	//System.assert(items.size() == controller.myOrderItems.size());
			 } 

			 plist[2].Pricing_Reference_Material__c = 'prm002';
			 OrderItem_Controller.lineItemWrapper liw3 = new OrderItem_Controller.lineItemWrapper(ord, null, plist[2]);		
			 controller.myOrderItems.add(liw3);
			 controller.saveAction();
			 
			 //liw.orderItem.Carton__c = 1;
			 //liw.orderItem.Unit__c = 1;
			 //liw.orderItem.Carton_Bonus__c = 1;
			 //controller.myOrderItems.clear();
			 //controller.myOrderItems.add(liw);
			 //controller.saveAction();
			 
			 controller.myOrder = ord;
	   		 controller.BuildLineItems();
	   		 	 
	   	     
	   		 	 
			 controller.close();
			 controller.saveAndClose();
        	 test.stopTest();
        }
	}
}