B-F Sandbox Full-Backup/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>INFOWELDERS</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Former</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Potential</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Telesales</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>CAD_Outlets</fullName>
        <active>true</active>
        <description>Canada Account Record Layout</description>
        <label>CAD - Outlets</label>
    </recordTypes>
    <recordTypes>
        <fullName>EUR_Outlets</fullName>
        <active>true</active>
        <description>European - Outlets</description>
        <label>EUR - Outlets</label>
    </recordTypes>
    <recordTypes>
        <fullName>Outlets</fullName>
        <active>true</active>
        <description>Japan Outlet customers</description>
        <label>Outlets</label>
    </recordTypes>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Outlet_Visit__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Outlet (Account)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Outlet Visits</relationshipLabel>
        <relationshipName>Outlet_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Visit__c</fullName>
        <defaultValue>false</defaultValue>
        <description>P00001  - Created by PARX to improve reporting on Last Visits</description>
        <label>Last Visit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Next_to_Last_Visit__c</fullName>
        <defaultValue>false</defaultValue>
        <description>P00001  - Created by PARX to improve reporting on Last Visits</description>
        <label>Next to Last Visit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Visit_Date__c</fullName>
        <label>Visit Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Outlet Visit</label>
    <nameField>
        <displayFormat>OV-{00000}</displayFormat>
        <label>Outlet Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outlet Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

B-F Sandbox/trunk/src/classes/Outlet_Visit_Helper.cls
public class Outlet_Visit_Helper {
    public static boolean hasAlreadyRun = false;
    
    public static void main(set<Id> AccountIds) {
        /**
         *Trigger on all events
         *Conditions: 
         *  +Account RecordType: EUR_Outlets (or "DEU_Outlets")
         *  +Status__c is 'Complete'
         *
         * We refresh always all the rows of the account to make sure everything is fine for every event.
         * We sort the retrieved records from the Account by Visit_Date__c. The last Visit_Date__c record gets the 
         * Last_Visit__c true. The next gets the field Next_to_Last_Visit__c true and Last_Visit__c to false
         * and all other records are set back to false.
         *          
         * @date    28.11.2011
         * @author  Christophe Vidal
        **/
        map<Id, list<Outlet_Visit__c>> Outlets_Visit = new map<Id, list<Outlet_Visit__c>>();
		system.debug('Account IDs: '+AccountIds);
// Commented by Sandeep Gadicherla 2/13 - 	for(Outlet_Visit__c OV:[select Account__c, Last_Visit__c, Next_to_Last_Visit__c from Outlet_Visit__c where Status__c = 'Complete' AND Account__c IN: AccountIds AND (Account__r.RecordType.developerName = 'EUR_Outlets' OR Account__r.RecordType.developerName = 'DEU_Outlets' OR Account__r.RecordType.developerName = 'CAD_Outlets') order by Visit_Date__c desc]) {
        for(Outlet_Visit__c OV:[select Account__c, Last_Visit__c, Next_to_Last_Visit__c, Visit_Date__c from Outlet_Visit__c where Status__c = 'Complete' AND Account__c IN: AccountIds AND (Account__r.RecordType.developerName = 'EUR_Outlets' OR Account__r.RecordType.developerName = 'DEU_Outlets' OR Account__r.RecordType.developerName = 'CAD_Outlets') order by Visit_Date__c desc]) {    
            if(!Outlets_Visit.containsKey(OV.Account__c))
                Outlets_Visit.put(OV.Account__c, new list<Outlet_Visit__c>());
            Outlets_Visit.get(OV.Account__c).add(OV);
        }
        system.debug('outlets visits for last visit: ' + Outlets_Visit);
        
        if(!Outlets_Visit.isEmpty()) {
            Integer i = 0;
            for(Id AccountId:Outlets_Visit.keySet()) {
            //  if(Outlets_Visit.containsKey(OV.Account__c)) {
                    i = 0;
                    system.debug('------------ BEFORE: Account '+AccountID+' has following items: '+Outlets_Visit.get(AccountId));
                    for(Outlet_Visit__c OVHelper:Outlets_Visit.get(AccountId)) {
                        if(i == 0) {
                            //first element
                            OVHelper.Last_Visit__c = true;
                            OVHelper.Next_to_Last_Visit__c = false;
                        }
                        else if(i == 1) {
                            //second element
                            OVHelper.Last_Visit__c = false;
                            OVHelper.Next_to_Last_Visit__c = true;
                        }
                        else {
                            //for the other elements, we set all checkboxes to false 
                            OVHelper.Last_Visit__c = false;
                            OVHelper.Next_to_Last_Visit__c = false;
                        }
                        i++;
                    }
                    system.debug('------------ AFTER: Account '+AccountID+' has following items: '+Outlets_Visit.get(AccountId));
            //  } 
            }
            list<Outlet_Visit__c> Outlets_Visit_2_Update = new list<Outlet_Visit__c>();
            for(list<Outlet_Visit__c> OV:Outlets_Visit.values()) {
                Outlets_Visit_2_Update.addAll(OV);
            }
            if(!Outlets_Visit_2_Update.isEmpty()) {
                update Outlets_Visit_2_Update;
            }
        }
    }

}