B-F Sandbox Full-Backup/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used by CRM.
NPA Rollout: Used to store the Market reference.</description>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Objectives__c</fullName>
        <description>Objectives for Upcoming Outlet Visits</description>
        <inlineHelpText>Enter objectives for upcoming outlet visits</inlineHelpText>
        <label>Objectives</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Market__c.object
<CustomObject>
    <description>Used by CRM.
NPA Rollout: Used to store Markets at State Level.</description>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Market__c</fullName>
        <description>INFOWELDERS - These text values MUST match the Market Name records&apos; text values.
NPA Rollout: Used to store the markets a user is allocated to. Multiple values can be used separated by semi-colon.</description>
        <inlineHelpText>CRM: Market at a Country level-  such as Germany, Korea, India, Japan etc.
NPA: Market at a State level-  such as Illinois, Kentucky etc.</inlineHelpText>
        <label>Market</label>
        <picklist>
            <picklistValues>
                <fullName>ALL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Germany</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Japan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Korea</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thailand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Taiwan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>India</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canada General</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

B-F Sandbox/trunk/src/classes/Test_EventCopyObjectives.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class Test_EventCopyObjectives {

    static testMethod void myUnitTest() {
        // TO DO: implement unit test
        INFW_TestHelper helper = new INFW_TestHelper();
        User u1 = helper.createUser();
        insert u1;
                
        Market__c m = new Market__c();
        m.Name = 'Test Market'; 
        insert m;
                           
        
        test.starttest();
        	system.runas(u1) {
        		Account a = new Account();
        		a.Name = 'Test Account';
        		a.Market__c = m.Id;
        		insert a;
        
        		Event e = new Event();
        		e.DurationInMinutes = 60;
        		e.ActivityDateTime = date.today();
        		e.WhatId = a.Id;
        		e.Objectives__c = 'Test Objectives';
        		insert e;
        	}          
        test.stoptest();
    }
}