B-F Sandbox Full-Backup/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Australia/Wombat Use</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used by CRM.
NPA Rollout: Used to store the Market reference.</description>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Account_Wholesaler__c.object
<CustomObject>
    <description>Wholesales Junction Object</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Wholesalers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Checked is active</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Legacy_Code__c</fullName>
        <label>Legacy Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Wholesaler_Account_Name__c</fullName>
        <description>Wholesales Account Name</description>
        <inlineHelpText>This is the Wholesalers (Account Name) for this retailer - Used for the (Cross-Reference) Conversion</inlineHelpText>
        <label>Wholesaler Account Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Wholesaler_Account_Number__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>This is the Wholesalers (Account Number) for this retailer - Used for the (Cross-Reference) Conversion</inlineHelpText>
        <label>Wholesaler Account Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Wholesaler__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Wholesaler</label>
        <referenceTo>Wholesaler__c</referenceTo>
        <relationshipName>Wholesaler</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Wholesaler</label>
    <nameField>
        <displayFormat>WHSL-{0}</displayFormat>
        <label>Account Wholesaler</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Wholesalers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Group_Promotion_Item__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Group_Promotion_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legacy_Code__c</fullName>
        <label>Legacy Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reference_Material_Group_Number__c</fullName>
        <formula>Reference_Material_Group__r.Reference_Material_Group_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Reference Material Group Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reference_Material_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference Material Group</description>
        <label>Reference Material Group</label>
        <referenceTo>Reference_Material_Group__c</referenceTo>
        <relationshipLabel>Deal Items</relationshipLabel>
        <relationshipName>Group_Promotion_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deal Item</label>
    <nameField>
        <displayFormat>GPI-{0}</displayFormat>
        <label>Group Promotion Item  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Group_Promotions__c.object
<CustomObject>
    <description>Group Promotion (Banner Group)</description>
    <fields>
        <fullName>Account_Wholesaler__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account Wholesaler</description>
        <inlineHelpText>Account Wholesaler</inlineHelpText>
        <label>Account Wholesaler</label>
        <referenceTo>Account_Wholesaler__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Group_Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Activity_Code__c</fullName>
        <label>Activity Code</label>
        <picklist>
            <controllingField>Application__c</controllingField>
            <picklistValues>
                <fullName>Catalogue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Price Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pouring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incentives</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ranging</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Xmas Catalogue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advertising</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cocktail Listings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Secondary Display</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Uniforms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Printing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Signage</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <picklist>
            <controllingField>Deal_Method__c</controllingField>
            <picklistValues>
                <fullName>On Retailer&apos;s Invoice - Rate per Case On</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Retailers Invoice - Rate per Case Off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rebate Customer - Lump Sum On</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rebate Customer - Lump Sum Off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rebate Group - Lump Sum On</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rebate Group - Lump Sum Off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rebate Third Party - Lump Sum On</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rebate Third Party - Lump Sum Off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rebate Customer - Rate per Case On</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rebate Customer - Rate per Case Off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rebate Group - Rate Per Case On</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rebate Group - Rate Per Case Off</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Deal_Channel__c</fullName>
        <description>Vistex - Tactic</description>
        <inlineHelpText>Vistex - Tactic</inlineHelpText>
        <label>Deal Channel</label>
        <picklist>
            <picklistValues>
                <fullName>ON</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OFF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integrated</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Legacy_Code__c</fullName>
        <label>Legacy Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Wholesaler__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the individual wholesaler shed (ie, ALM NSW)</inlineHelpText>
        <label>Wholesaler</label>
        <referenceTo>Wholesaler__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Group_Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>Deal-{0}</displayFormat>
        <label>Deal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Reference_Material_Group__c.object
<CustomObject>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Legacy_Code__c</fullName>
        <label>Legacy Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reference_Material_Group_Number__c</fullName>
        <description>Reference Material Group Number</description>
        <externalId>true</externalId>
        <label>Reference Material Group Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Reference Material Group</label>
    <nameField>
        <label>Reference Material Group Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reference Material Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Market__c</fullName>
        <description>INFOWELDERS - These text values MUST match the Market Name records&apos; text values.
NPA Rollout: Used to store the markets a user is allocated to. Multiple values can be used separated by semi-colon.</description>
        <inlineHelpText>CRM: Market at a Country level-  such as Germany, Korea, India, Japan etc.
NPA: Market at a State level-  such as Illinois, Kentucky etc.</inlineHelpText>
        <label>Market</label>
        <picklist>
            <picklistValues>
                <fullName>ALL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Germany</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Japan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Korea</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thailand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Taiwan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>India</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canada General</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Wholesaler__c.object
<CustomObject>
    <description>Australia Wholesaler Object</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Wholesalers</relationshipLabel>
        <relationshipName>Wholesalers1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Checked is active</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Legacy_Code__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>Do we need this field? It&apos;s not coming from ECC will this be loaded from Possum</inlineHelpText>
        <label>Legacy Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Wholesalers</relationshipLabel>
        <relationshipName>Wholesalers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SAP_Number__c</fullName>
        <externalId>true</externalId>
        <label>SAP Number</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Wholesaler</label>
    <nameField>
        <label>Wholesaler</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wholesalers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/classes/Test_DealItem_Controller.cls
/* Class Name : Test_DealItem_Controller
* Description: Test class to test the deal item controller
* Created By : Tass Tsakiridis
* Created On : 2nd May 2012
*
* Modification Log :  
* ----------------------------------------------------------------------------------------------------------------------------
* Developer       Date              Description
* ----------------------------------------------------------------------------------------------------------------------------
*/ 
@isTest
private class Test_DealItem_Controller {
	static testMethod void unitTest1() {
        INFW_TestHelper helper = new INFW_TestHelper();
        User u1 = helper.createUser();
        Profile[] p1 = [select id from Profile where Name = 'System Administrator' LIMIT 1];
        //Profile[] p1 = [SELECT Id FROM Profile WHERE Name = 'AUD-Customer Service (Platform)'];        
        u1.ProfileID = p1[0].id;      
        u1.Market__c = 'Australia';
        insert u1;		
        
		// SOQL Query for Order & Order_Item Record Type Data
		RecordType p_rt = [SELECT r.Name, r.Id FROM RecordType r WHERE r.Name = 'Outlet Deal' AND SObjectType = 'Group_Promotions__c'];       
        RecordType o_rt = [SELECT r.Name, r.Id FROM RecordType r WHERE  r.Name = 'Group Deal' AND SObjectType = 'Group_Promotions__c'];
        
        
		// Test Data for Market
		List<Market__c> markets = [SELECT Id FROM Market__c WHERE Name = 'Australia'];

		List<Reference_Material_Group__c> pList = new List<Reference_Material_Group__c>();
		
		for(integer x = 0; x < 3; x++) {
			Reference_Material_Group__c p = new Reference_Material_Group__c();
			p.Name = 'TestOrderProduct_' + x;
			p.Is_Active__c = true;
			p.Legacy_Code__c = 'LEG00' + x;
			p.Reference_Material_Group_Number__c = 'mat00' + x;
			pList.add(p);
		}
		insert pList;
		
        
        system.runas(u1) {
	        Account a = new Account();
        	a.Name = 'Test Account';
        	a.Market__c = markets[0].Id;
        	insert a;
        	         	 
        	 Wholesaler__c w = new Wholesaler__c();
        	 w.Name = 'Test Wholesaler';
        	 w.Account__c = a.Id;
        	 w.SAP_Number__c = 'ECC1234';
        	 w.Is_Active__c = true;
        	 insert w;
        	 
        	 Account_Wholesaler__c aw = new Account_Wholesaler__c();
        	 aw.Account__c = a.Id;
        	 aw.Wholesaler__c = w.Id;
        	 aw.Wholesaler_Account_Number__c = 'WAN-1234';
        	 aw.Wholesaler_Account_Name__c = 'Test Account for Test W/Saler';
        	 insert aw;

        	 
        	 Group_Promotions__c deal = new Group_Promotions__c();
        	 deal.Account__c = a.Id;
        	 deal.RecordTypeId = p_rt.Id;
        	 deal.Wholesaler__c = w.Id;
        	 deal.Account_Wholesaler__c = aw.Id;
        	 deal.Activity_Code__c = 'Catalogue';
        	 deal.Application__c = 'On Retailers Invoice - Rate per Case On';
        	 deal.Deal_Channel__c = 'ON';
        	 deal.Deal_Method__c = 'Rate Per Case';
        	 deal.Activity_Comment__c = 'test controller';
        	 deal.Buy_Period_Start_Date__c = Date.today();
        	 deal.Buy_Period_End_Date__c = Date.today();
        	 insert deal;
        	 
        	 Group_Promotion_Item__c oi1 = new Group_Promotion_Item__c();
        	 oi1.Group_Promotion__c = deal.Id;
        	 oi1.Reference_Material_Group__c = pList[0].Id;
        	 oi1.Discount_Amount__c = 1.5;
        	 insert oi1;
        	 
        	 
        	 ApexPages.currentPage().getParameters().put('Id', deal.Id);
        	 test.startTest();
        	 
        	 ApexPages.Standardcontroller sc = new ApexPages.Standardcontroller(deal);
        	 DealItem_Controller controller = new DealItem_Controller(sc);
        	 controller.myDeal = deal;
        	 
			 
			 // Test lineItemWrapper class
			 DealItem_Controller.lineItemWrapper liw = new DealItem_Controller.lineItemWrapper();
			 
			 controller.addLine();
			 System.debug('[test_oictrl] myorderitems.size: ' + controller.myDealItems.size());
			 
			 //System.assert(controller.myOrderItems.size() == 1);
			 
			 //controller.filterAction();
			 controller.BuildLineItems();
			 //System.assert(controller.myOrderItems.size() == 11);

			 controller.myDealItems.clear();
			 
			 //OrderItem_Controller.lineItemWrapper liw2 = new OrderItem_Controller.lineItemWrapper(deal, null, pList[1]);
			 //controller.myDealItems.add(liw2);
			 
			 //liw1.selected = true;
			 //controller.myDealItems.add(liw1);

			 controller.removeDealItems();
			 	//System.assert(controller.myOrderItems.size() == 9);			 	

			 controller.saveAction();
			 if (ApexPages.getMessages().size() > 0) {
			 	System.debug('Error saving order ' + deal.Id + ' [' + deal.Name + ']');
			 } else {
			 } 

			 
			 controller.myDeal = deal;
	   		 controller.BuildLineItems();
	   		 	 
			 controller.close();
			 controller.saveAndClose();
        	 test.stopTest();
        }
	}
}