B-F Sandbox Full-Backup/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Channel__c</fullName>
        <description>INFOWELDERS</description>
        <label>Channel</label>
        <picklist>
            <picklistValues>
                <fullName>On</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Sellable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wholesaler</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sub_Wholesaler</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INTEG MAINLY ON</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INTEG MAINLY OFF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ON PREMISE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OFF PREMISE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INTEGRATED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NON RETAIL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UNCLASSIFIED</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>EUR_Outlets</fullName>
        <active>true</active>
        <description>European - Outlets</description>
        <label>EUR - Outlets</label>
    </recordTypes>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Account_Brand__c.object
<CustomObject>
    <description>INFOWELDERS - Brands Related to this Account</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>INFOWELDERS</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Brands</relationshipLabel>
        <relationshipName>Account_Brands</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>INFOWELDERS</description>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>Account Brands</relationshipLabel>
        <relationshipName>Account_Brands</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Depletion_Actuals__c</fullName>
        <description>INFOWELDERS - Depletion actuals for this brand at this outlet for this fiscal year as calculated based on depletion records</description>
        <inlineHelpText>Depletion actuals for this brand at this outlet for this fiscal year</inlineHelpText>
        <label>Depletion Actuals</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Required_Brand__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Mandatory Brand</label>
        <type>Checkbox</type>
    </fields>
    <label>Account Brand</label>
    <nameField>
        <displayFormat>AB-{0000000}</displayFormat>
        <label>Account Brands Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Brands</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Account_Product__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Products</relationshipLabel>
        <relationshipName>Account_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Available__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Available</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Bottle_Price_Special__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bottle Price Special</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Bottle_Price__c</fullName>
        <label>Bottle Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <description>Brand Name</description>
        <label>Brand</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Double_Price_Special__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Double Price Special</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Double_Price__c</fullName>
        <label>Double Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Drink_Price_Special__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Drink Price Special</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Drink_Price__c</fullName>
        <description>Drink Price</description>
        <label>Drink Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Account Products</relationshipLabel>
        <relationshipName>Account_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shelf__c</fullName>
        <label>Shelf</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Account Product</label>
    <nameField>
        <displayFormat>AP-{0}</displayFormat>
        <label>Account Product</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

B-F Backup Sandbox 30.4.12/src/objects/Mandatory_Products__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <description>Infowelders</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Mandatory Products</relationshipLabel>
        <relationshipName>Mandatory_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Custom_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created for the Product Remediation</description>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Mandatory Products</relationshipLabel>
        <relationshipName>Mandatory_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Status__c</fullName>
        <description>Infowelders</description>
        <label>Product Status</label>
        <picklist>
            <picklistValues>
                <fullName>Mandatory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Optional</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Infowelders</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Mandatory Products</relationshipLabel>
        <relationshipName>Mandatory_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Mandatory Product</label>
    <nameField>
        <displayFormat>MP-{000000}</displayFormat>
        <label>Mandatory Products Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mandatory Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Outlet_Visit__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Outlet (Account)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Outlet Visits</relationshipLabel>
        <relationshipName>Outlet_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Outlet Visit</label>
    <nameField>
        <displayFormat>OV-{00000}</displayFormat>
        <label>Outlet Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outlet Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

B-F Backup Sandbox 30.4.12/src/objects/Outlet_Visit_Item__c.object
<CustomObject>
    <fields>
        <fullName>Available__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Infowelders</description>
        <label>Available</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Bottle_Price_Special__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bottle Price Special</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Bottle_Price__c</fullName>
        <label>Bottle Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>Custom_Product__r.Brand__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <formula>TEXT(Outlet_Visit__r.Venue__r.Channel__c)</formula>
        <label>Channel</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Custom_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created for Product Remediation process</description>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Outlet Visit Items</relationshipLabel>
        <relationshipName>Outlet_Visit_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Double_Price_Special__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Double Price Special</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Double_Price__c</fullName>
        <label>Double Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Drink_Price_Special__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Drink Price Special</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Drink_Price__c</fullName>
        <label>Drink Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Facing__c</fullName>
        <description>Infowelders</description>
        <label>Facing</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Outlet_Visit__c</fullName>
        <label>Outlet Visit</label>
        <referenceTo>Outlet_Visit__c</referenceTo>
        <relationshipLabel>Outlet Visit Items</relationshipLabel>
        <relationshipName>Outlet_Visit_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Outlet Visit Items</relationshipLabel>
        <relationshipName>Outlet_Visit_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Outlet Visit Item</label>
    <nameField>
        <label>Outlet Visit Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Outlet Visit Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

B-F Backup Sandbox 30.4.12/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Infowelders</description>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <label>Channel</label>
        <picklist>
            <picklistValues>
                <fullName>On</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Both</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Product__c.object
<CustomObject>
    <description>NPA Rollout: Object for storing Products used in National Promotion application.
Product Remediation : Replicated all standard product fields here.</description>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Infowelders, NPA Rollout: Used to store the related Brand</description>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipName>Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <description>Created as a part of product remediation</description>
        <label>Channel</label>
        <picklist>
            <picklistValues>
                <fullName>On</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Both</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <description>NPA Rollout: Stores the product code</description>
        <label>Product Unique Key</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

B-F Sandbox/trunk/src/classes/Outlet_Visit_Item_Helper.cls
public with sharing class Outlet_Visit_Item_Helper {
	private static final String DEU_ACCOUNT_RECORDTYPE='DEU_Outlets';
	private static final String EUR_ACCOUNT_RECORDTYPE='EUR_Outlets';
	
	public static boolean runIt = false;
    public static void main(list<Id> ovi_Ids, list<Id> deletedIds) {
    	   /**
		     * we run the trigger on Outlet Visit Item to update the brand depletion actuals.
		     *Conditions: 
		     *  +Account RecordType: EUR_Outlets (or "DEU_Outlets")
		     *  +onUpdate, Brand or Facing or Channel (Account) has changed
		     *
		     * On delete, we have to get the event from the on Outlet Visit trigger because there is no event in the outlet Visit Item
		     * We refresh always all the records of the account to make sure everything is fine for every event.
		     * If the Channel is on, then Depletion actuals is 1 else it's the sum of the facing grouped by brand.
		     * If the brand does not exist, it has to be created, else it has to be updated (the Depletion Actual).
		     * 
		     * We care also about the mandatory product (Custom Object from the Account): if a Product is mandatory,
		     * then the account brand becomes also mandatory.
		     *
		     * @date    30.11.2011
		     * @author  Christophe Vidal
		    */
		list<Id> RTIds = new list<Id>();
        for(RecordType rt:[select id from RecordType where sObjectType = 'Account' AND (developerName = :EUR_ACCOUNT_RECORDTYPE OR developerName = :DEU_ACCOUNT_RECORDTYPE)]) {
            RTIds.add(rt.Id);
        }
    	map<Id, Outlet_Visit_Item__c> ovi_Map = new map<Id, Outlet_Visit_Item__c>([select Outlet_Visit__r.Account__c from Outlet_Visit_Item__c where Id IN: ovi_Ids AND Outlet_Visit__r.Account__r.RecordTypeId IN: RTIds]);
        list<Id> AccountIds = new list<Id>();
        for(Outlet_Visit_Item__c ovi:ovi_Map.values()) {
            AccountIds.add(ovi.Outlet_Visit__r.Account__c);
        }
        map<Id, map<Id, Account_Brand__c>> AccountBrand_Map = new map<Id, map<Id, Account_Brand__c>>();
        for(Account_Brand__c AB:[select Account__c, Account__r.Channel__c, Brand__c, Depletion_Actuals__c from Account_Brand__c where Account__c IN: AccountIds]) {
            AB.Depletion_Actuals__c = 0;
            AB.Required_Brand__c = false;
            if(!AccountBrand_Map.containsKey(AB.Account__c)) {
                AccountBrand_Map.put(AB.Account__c, new map<Id, Account_Brand__c>());
            }
            if(!AccountBrand_Map.get(AB.Account__c).containsKey(AB.Brand__c)) {
                AccountBrand_Map.get(AB.Account__c).put(AB.Brand__c,AB);
            }
        }
        map<Id, map<Id, Mandatory_Products__c>> MandatoryProduct_Map = new map<Id, map<Id, Mandatory_Products__c>>();
        for(Mandatory_Products__c MP:[select Account__c, Custom_Product__r.Brand__c from Mandatory_Products__c where Account__c IN: AccountIds AND Product_Status__c = 'Mandatory']) {
            if(!MandatoryProduct_Map.containsKey(MP.Account__c)) {
                MandatoryProduct_Map.put(MP.Account__c, new map<Id, Mandatory_Products__c>());
            }
            if(!MandatoryProduct_Map.get(MP.Account__c).containsKey(MP.Custom_Product__c)) {
                MandatoryProduct_Map.get(MP.Account__c).put(MP.Custom_Product__r.Brand__c,MP);
            }
        }
        
        
        //we get the full map of the account without forgetting to remove the deleted ovi.
        ovi_Map = new map<Id, Outlet_Visit_Item__c>([select Custom_Product__r.Brand__c, facing__c, Outlet_Visit__r.Account__c from Outlet_Visit_Item__c where Outlet_Visit__r.Account__c IN: AccountIds AND Id NOT IN: deletedIds]);
        
        for(Outlet_Visit_Item__c ovi:ovi_Map.values()) {
            if(AccountBrand_Map.containsKey(ovi.Outlet_Visit__r.Account__c) && AccountBrand_Map.get(ovi.Outlet_Visit__r.Account__c).containsKey(ovi.Custom_Product__r.Brand__c)) {
                //we have just to update the existing Account Brand.
                Account_Brand__c AB = AccountBrand_Map.get(ovi.Outlet_Visit__r.Account__c).get(ovi.Custom_Product__r.Brand__c);
                if(AB.Account__r.Channel__c == 'on') {
                    AB.Depletion_Actuals__c = 1;
                }
                else {
                    //channel is off
                    if(AB.Depletion_Actuals__c==null)
                        AB.Depletion_Actuals__c = 0;
                    AB.Depletion_Actuals__c += ovi.Facing__c!=null?ovi.Facing__c:0;
                }
                if(MandatoryProduct_Map.containsKey(ovi.Outlet_Visit__r.Account__c) && MandatoryProduct_Map.get(ovi.Outlet_Visit__r.Account__c).containsKey(ovi.Custom_Product__r.Brand__c))
                    AB.Required_Brand__c = true;
                AccountBrand_Map.get(ovi.Outlet_Visit__r.Account__c).put(ovi.Custom_Product__r.Brand__c, AB);
            }
            else {
                //we have to create a new brand
                Account_Brand__c AB = new Account_Brand__c();
                AB.Account__c = ovi.Outlet_Visit__r.Account__c;
                AB.Brand__c = ovi.Custom_Product__r.Brand__c;
                if(AB.Account__r.Channel__c == 'on') {
                    AB.Depletion_Actuals__c = 1;
                }
                else {
                    //channel is off
                    AB.Depletion_Actuals__c = ovi.Facing__c;
                }
                if(!AccountBrand_Map.containsKey(AB.Account__c)) {
                    AccountBrand_Map.put(AB.Account__c, new map<Id, Account_Brand__c>());
                }
                if(MandatoryProduct_Map.containsKey(ovi.Outlet_Visit__r.Account__c) && MandatoryProduct_Map.get(ovi.Outlet_Visit__r.Account__c).containsKey(ovi.Custom_Product__r.Brand__c))
                    AB.Required_Brand__c = true;
                AccountBrand_Map.get(AB.Account__c).put(AB.Brand__c,AB);
            }  
        }
        list<Account_Brand__c> Account_Brands = new list<Account_Brand__c>();
        for(map<Id, Account_Brand__c> helper1:AccountBrand_Map.values()) {
            for(Account_Brand__c AB:helper1.values()) {
                Account_Brands.add(AB);
            }
        }
        if(!Account_Brands.isEmpty()) {
            upsert Account_Brands;
        }
    }
    
    public static void map_to_Account_Products(list<Id> ovi_Ids, list<Id> deletedIds) {
    	   /**
		     * we run the trigger on Outlet Visit Item to update the account products.
		     *Conditions: 
		     *  +none
		     *
		     * We want to map all necessary information from the selected outlet visit item to a account product 
		     * (custom object) for more refined product information.
		     * If the account product does not exist, it has to be created, else it has to be updated with information
		     * from the outlet visit item.
		     * 
		     * @date    21.12.2011
		     * @author  Michael Mickiewicz
		    */
		
        //we get the full map from the account without forgetting to remove the deleted ovi.
        map<ID, Outlet_Visit_Item__c> ovi_Map = new map<Id, Outlet_Visit_Item__c>([select Available__c, Bottle_Price__c, Bottle_Price_Special__c, Brand__c, Double_Price__c, Double_Price_Special__c, Drink_Price__c, Drink_Price_Special__c, Facing__c, Product__r.ID, Shelf__c, Outlet_Visit__r.Account__c, Outlet_Visit__r.Name, Outlet_Visit__r.Last_Visit_Date__c from Outlet_Visit_Item__c where Available__c = true AND ID IN: ovi_Ids AND Id NOT IN: deletedIds]);
        set<ID> productIDs = new set<ID>();
        
        for(Outlet_Visit_Item__c ovi : ovi_Map.values()) {
        	if(!productIDs.contains(ovi.Product__r.ID))
        		productIDs.add(ovi.Product__r.ID);	    
        }
        
        //Request all existing account products to complete the lefting records
        map<ID, Account_Product__c> ac_Map = new map<ID, Account_Product__c>([Select Available__c, Bottle_Price__c, Bottle_Price_Special__c, Brand__c, Double_Price__c, Double_Price_Special__c, Drink_Price__c, Drink_Price_Special__c, Facings__c, Product__c, Shelf__c, Account__c, 	Last_Outlet_Visit_Number__c, Last_Outlet_Visit_Date__c From Account_Product__c Where Product__c IN: productIDs]);
        list<Account_Product__c> newAccountProducts = new list<Account_Product__c>();
        
        //Iterate and map all outlet visit items to account products
        for(Outlet_Visit_Item__c ovi : ovi_Map.values()) {
        	Boolean isMapped = false;
			for(Account_Product__c ac : ac_Map.values())
				if(ovi.Product__c == ac.Product__c) {
        			ac.Available__c = ovi.Available__c;
					ac.Bottle_Price__c = ovi.Bottle_Price__c;
					//ac.Bottle_Price_Special__c = ovi.Bottle_Price_Special__c;
					ac.Brand__c = ovi.Brand__c;
					ac.Double_Price__c = ovi.Double_Price__c;
					//ac.Double_Price_Special__c = ovi.Double_Price_Special__c;
					ac.Drink_Price__c = ovi.Drink_Price__c;
					//ac.Drink_Price_Special__c = ovi.Drink_Price_Special__c;
					ac.Facings__c = ovi.Facing__c;
					ac.Last_Outlet_Visit_Number__c = ovi.Outlet_Visit__r.Name;
					ac.Last_Outlet_Visit_Date__c = ovi.Outlet_Visit__r.Last_Visit_Date__c;
					ac.Shelf__c = ovi.Shelf__c;
            		ac.Account__c = ovi.Outlet_Visit__r.Account__c;	
					isMapped = true;
				}
				
				//If a account product is not mapped, it do not exists. So create it and map all values.
				if(!isMapped) {
					Account_Product__c ac = new Account_Product__c();
					ac.Available__c = ovi.Available__c;
					ac.Bottle_Price__c = ovi.Bottle_Price__c;
					//ac.Bottle_Price_Special__c = ovi.Bottle_Price_Special__c;
					ac.Brand__c = ovi.Brand__c;
					ac.Double_Price__c = ovi.Double_Price__c;
					//ac.Double_Price_Special__c = ovi.Double_Price_Special__c;
					ac.Drink_Price__c = ovi.Drink_Price__c;
					//ac.Drink_Price_Special__c = ovi.Drink_Price_Special__c;
					ac.Facings__c = ovi.Facing__c;
					ac.Last_Outlet_Visit_Number__c = ovi.Outlet_Visit__r.Name;
					ac.Last_Outlet_Visit_Date__c = ovi.Outlet_Visit__r.Last_Visit_Date__c;
					ac.Product__c = ovi.Product__c;
					ac.Shelf__c = ovi.Shelf__c;
            		ac.Account__c = ovi.Outlet_Visit__r.Account__c;	
            		newAccountProducts.add(ac);
				}
        }
        
        if(!ac_Map.values().isEmpty()) {
            upsert ac_Map.values();
        }
        if(newAccountProducts.size() > 0){
        	insert newAccountProducts;
        }
    }
}