B-F Sandbox Full-Backup/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Australia/Wombat Use</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used by CRM.
NPA Rollout: Used to store the Market reference.</description>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Account_Wholesaler__c.object
<CustomObject>
    <description>Wholesales Junction Object</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Wholesalers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Checked is active</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Wholesaler_Account_Name__c</fullName>
        <description>Wholesales Account Name</description>
        <inlineHelpText>This is the Wholesalers (Account Name) for this retailer - Used for the (Cross-Reference) Conversion</inlineHelpText>
        <label>Wholesaler Account Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Wholesaler_Account_Number__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>This is the Wholesalers (Account Number) for this retailer - Used for the (Cross-Reference) Conversion</inlineHelpText>
        <label>Wholesaler Account Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Wholesaler__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Wholesaler</label>
        <referenceTo>Wholesaler__c</referenceTo>
        <relationshipName>Wholesaler</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Wholesaler</label>
    <nameField>
        <displayFormat>WHSL-{0}</displayFormat>
        <label>Account Wholesaler</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Wholesalers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Application__c.object
<CustomObject>
    <description>Force.com Application(s) that is either proposed or slated to be developed on the the Force.com platform</description>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Banner_Groups__c.object
<CustomObject>
    <label>Banner Group</label>
    <nameField>
        <label>Banner Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Banner Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Group_Promotions__c.object
<CustomObject>
    <description>Group Promotion (Banner Group)</description>
    <fields>
        <fullName>Account_Wholesaler__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account Wholesaler</description>
        <inlineHelpText>Account Wholesaler</inlineHelpText>
        <label>Account Wholesaler</label>
        <referenceTo>Account_Wholesaler__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Group_Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Activity_Code__c</fullName>
        <label>Activity Code</label>
        <picklist>
            <controllingField>Application__c</controllingField>
            <picklistValues>
                <fullName>Catalogue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Price Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pouring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incentives</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ranging</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Xmas Catalogue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advertising</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cocktail Listings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Secondary Display</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Uniforms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Printing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Signage</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Activity_Comment__c</fullName>
        <label>Activity Comment</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <picklist>
            <controllingField>Deal_Method__c</controllingField>
            <picklistValues>
                <fullName>On Retailer&apos;s Invoice - Rate per Case On</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Retailers Invoice - Rate per Case Off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rebate Customer - Lump Sum On</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rebate Customer - Lump Sum Off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rebate Group - Lump Sum On</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rebate Group - Lump Sum Off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rebate Third Party - Lump Sum On</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rebate Third Party - Lump Sum Off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rebate Customer - Rate per Case On</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rebate Customer - Rate per Case Off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rebate Group - Rate Per Case On</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rebate Group - Rate Per Case Off</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Buy_Period_End_Date__c</fullName>
        <description>Buy Period End Date</description>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Buy_Period_Start_Date__c</fullName>
        <description>The period that the Account can purchase the product.</description>
        <inlineHelpText>The period that the Account can purchase the product.</inlineHelpText>
        <label>Buy Period Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deal_Channel__c</fullName>
        <description>Vistex - Tactic</description>
        <inlineHelpText>Vistex - Tactic</inlineHelpText>
        <label>Deal Channel</label>
        <picklist>
            <picklistValues>
                <fullName>ON</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OFF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integrated</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Deal_Method__c</fullName>
        <label>Deal Method</label>
        <picklist>
            <controllingField>Deal_Channel__c</controllingField>
            <picklistValues>
                <fullName>Rate Per Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lump Sum</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rate per Case Off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lump Sum Off</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Wholesaler__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the individual wholesaler shed (ie, ALM NSW)</inlineHelpText>
        <label>Wholesaler</label>
        <referenceTo>Wholesaler__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Group_Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>Deal-{0}</displayFormat>
        <label>Deal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Market__c.object
<CustomObject>
    <description>Used by CRM.
NPA Rollout: Used to store Markets at State Level.</description>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Market__c</fullName>
        <description>INFOWELDERS - These text values MUST match the Market Name records&apos; text values.
NPA Rollout: Used to store the markets a user is allocated to. Multiple values can be used separated by semi-colon.</description>
        <inlineHelpText>CRM: Market at a Country level-  such as Germany, Korea, India, Japan etc.
NPA: Market at a State level-  such as Illinois, Kentucky etc.</inlineHelpText>
        <label>Market</label>
        <picklist>
            <picklistValues>
                <fullName>ALL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Germany</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Japan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Korea</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thailand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Taiwan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>India</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canada General</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Wholesaler__c.object
<CustomObject>
    <description>Australia Wholesaler Object</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Wholesalers</relationshipLabel>
        <relationshipName>Wholesalers1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Checked is active</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Wholesalers</relationshipLabel>
        <relationshipName>Wholesalers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SAP_Number__c</fullName>
        <externalId>true</externalId>
        <label>SAP Number</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Wholesaler</label>
    <nameField>
        <label>Wholesaler</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wholesalers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/classes/Test_beforeInsertUpdateDeal.cls
/* Class Name : Test_OrderItem_Controller
* Description: Test class to test the order item controller
* Created By : Tass Tsakiridis
* Created On : 17th April 2012
*
* Modification Log :  
* ----------------------------------------------------------------------------------------------------------------------------
* Developer       Date              Description
* ----------------------------------------------------------------------------------------------------------------------------
*/ 
@isTest
private class Test_beforeInsertUpdateDeal {
	static testMethod void UnitTest1() {
        INFW_TestHelper helper = new INFW_TestHelper();
        User u1 = helper.createUser();
        Profile[] p1 = [select id from Profile where Name = 'System Administrator' LIMIT 1];
        //Profile[] p1 = [SELECT Id FROM Profile WHERE Name = 'AUD-Customer Service (Platform)'];        
        u1.ProfileID = p1[0].id;      
        u1.Market__c = 'Australia';
        insert u1;		
        
        List<RecordType> recordTypes = [SELECT Id FROM RecordType WHERE Name = 'Outlet Deal' AND SObjectType = 'Group_Promotions__c']; 
		// Test Data for Market
		List<Market__c> markets = [SELECT Id FROM Market__c WHERE Name = 'Australia'];
	
        System.runas(u1) {
        	Account a = new Account();
        	a.Name = 'Test Account';
        	a.Market__c = markets[0].Id;
        	insert a;
        	
        	Wholesaler__c w = new Wholesaler__c();
        	w.Name = 'Test Wholesaler';
        	w.Account__c = a.Id;
        	w.SAP_Number__c = 'ECC1234';
        	w.Is_Active__c = true;
        	insert w;
        	
        	Account_Wholesaler__c aw = new Account_Wholesaler__c();
        	aw.Account__c = a.Id;
        	aw.Wholesaler__c = w.Id;
        	aw.Wholesaler_Account_Number__c = 'WAN-1234';
        	aw.Wholesaler_Account_Name__c = 'Test Account for Test W/Saler';
        	insert aw;

			Banner_Groups__c bg = new Banner_Groups__c();
			bg.Name = 'Test Banner Group';
			insert bg;
			         	
        	Group_Promotions__c deal = new Group_Promotions__c();
        	if (recordTypes.size() > 0) {
        		deal.RecordTypeId = recordTypes[0].Id;        		
        	}
 			deal.Account__c = a.Id;
 			deal.Wholesaler__c = w.Id;       	
 			deal.Account_Wholesaler__c = aw.Id;
 			deal.Buy_Period_Start_Date__c = Date.today();
 			deal.Buy_Period_End_Date__c = Date.today();
        	deal.Deal_Channel__c = 'ON';
        	deal.Deal_Method__c = 'Rate Per Case';
        	deal.Application__c = 'On Retailers Invoce - Rate per Case On';
        	deal.Activity_Code__c = 'Price Support';
        	deal.Activity_Comment__c = 'test trigger';
        	insert deal;
        	
        }
	}
}