B-F Sandbox Full-Backup/src/objects/Account_Wholesaler__c.object
<CustomObject>
    <description>Wholesales Junction Object</description>
    <fields>
        <fullName>AccountNumber__c</fullName>
        <formula>Account__r.AccountNumber</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>ECC Account Number</inlineHelpText>
        <label>Account Number (SAP)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Wholesalers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wholesaler_Name__c</fullName>
        <formula>Wholesaler__r.Wholesaler_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Wholesaler Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Wholesaler__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Wholesaler</label>
        <referenceTo>Wholesaler__c</referenceTo>
        <relationshipName>Wholesaler</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Wholesaler</label>
    <nameField>
        <displayFormat>WHSL-{0}</displayFormat>
        <label>Account Wholesaler</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Wholesalers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Group_Promotion_Item__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Group_Promotion_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Condition_Types__c</fullName>
        <label>Condition Types</label>
        <picklist>
            <picklistValues>
                <fullName>Bonus Quantity	ZB30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Compliance Off Premise $	ZB15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Compliance Off Premise %	ZB16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Compliance On Premise $	ZB17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Compliance On Premise %	ZB18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eligible Banner / Mgmt Grp	ZB05</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eligible Distributor Banner	ZB05</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eligible Distributor	ZB06</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eligible Group    ZB05</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exclusion Material	ZB71</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exclusion Retailer	ZB72</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA Off Premise $	ZB11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA Off Premise %	ZB12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA On Premise $	ZB13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA On Premise %	ZB14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Route to Mkt - Recovery $	ZB23</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Route to Mkt - Recovery %	ZB24</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visibility Off Premise $	ZB19</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visibility Off Premise %	ZB20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visibility On Premise $	ZB21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visibility On Premise %	ZB22</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Discount_Amount__c</fullName>
        <description>Discount Amount per Case</description>
        <inlineHelpText>Discount Amount per Case</inlineHelpText>
        <label>Discount per Case</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Group_Promotion__c</fullName>
        <label>Deal</label>
        <referenceTo>Group_Promotions__c</referenceTo>
        <relationshipLabel>Deal Items</relationshipLabel>
        <relationshipName>Group_Promotion_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ongoing__c</fullName>
        <defaultValue>8.25</defaultValue>
        <description>Ongoing Per - Case</description>
        <inlineHelpText>Ongoing Per Case</inlineHelpText>
        <label>Ongoing</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Price_Vision_Type__c</fullName>
        <label>Price Vision Type</label>
        <picklist>
            <picklistValues>
                <fullName>Everyday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maximum</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Promotion</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Price_Vision__c</fullName>
        <label>Price Vision</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Reference_Material_Group_Number__c</fullName>
        <formula>Reference_Material_Group__r.Reference_Material_Group_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Reference Material Group Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reference_Material_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference Material Group</description>
        <label>Reference Material Group</label>
        <referenceTo>Reference_Material_Group__c</referenceTo>
        <relationshipLabel>Deal Items</relationshipLabel>
        <relationshipName>Group_Promotion_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deal Item</label>
    <nameField>
        <displayFormat>GPI-{0}</displayFormat>
        <label>Group Promotion Item  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Group_Promotions__c.object
<CustomObject>
    <description>Group Promotion (Banner Group)</description>
    <fields>
        <fullName>AccountName__c</fullName>
        <formula>Account__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AccountName</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AccountNumber__c</fullName>
        <formula>Account__r.AccountNumber</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AccountNumber</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Wholesaler__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account Wholesaler</description>
        <inlineHelpText>Account Wholesaler</inlineHelpText>
        <label>Account Wholesaler</label>
        <referenceTo>Account_Wholesaler__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Group_Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Banner_Group_Name__c</fullName>
        <formula>Banner_Group__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Banner Group Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Banner_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Banner Group</label>
        <referenceTo>Banner_Groups__c</referenceTo>
        <relationshipName>Group_Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Buy_Period_Start_Date__c</fullName>
        <description>The period that the Account can purchase the product.</description>
        <inlineHelpText>The period that the Account can purchase the product.</inlineHelpText>
        <label>Buy Period Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deal_Display_Helper_Type__c</fullName>
        <formula>IF(  ISPICKVAL(Deal_Method__c, &apos;Rate Per Case&apos; ) ||  ISPICKVAL(Deal_Method__c, &apos;Rate per Case Off&apos; ), &apos;Rate per Case&apos;, &apos;Lump Sum&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Deal Display Helper Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deal_Method__c</fullName>
        <label>Deal Method</label>
        <picklist>
            <controllingField>Deal_Channel__c</controllingField>
            <picklistValues>
                <fullName>Rate Per Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lump Sum</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rate per Case Off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lump Sum Off</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Deal_Type__c</fullName>
        <label>Deal Type</label>
        <picklist>
            <picklistValues>
                <fullName>Ongoing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Promotion</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RecordTypeName__c</fullName>
        <formula>$RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>RecordTypeName</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Initial</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Wholesaler_Name__c</fullName>
        <formula>IF( $RecordType.Name == &apos;Group Deal&apos;,  Wholesaler__r.Name,  Account_Wholesaler__r.Wholesaler__r.Name )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Wholesaler Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Wholesaler__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the individual wholesaler shed (ie, ALM NSW)</inlineHelpText>
        <label>Wholesaler</label>
        <referenceTo>Wholesaler__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Group_Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>Deal-{0}</displayFormat>
        <label>Deal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Reference_Material_Group__c.object
<CustomObject>
    <fields>
        <fullName>Reference_Material_Group_Number__c</fullName>
        <description>Reference Material Group Number</description>
        <externalId>true</externalId>
        <label>Reference Material Group Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Reference Material Group</label>
    <nameField>
        <label>Reference Material Group Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reference Material Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Wholesaler__c.object
<CustomObject>
    <description>Australia Wholesaler Object</description>
    <fields>
        <fullName>AccountNumber__c</fullName>
        <formula>Account__r.AccountNumber</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AccountNumber</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Wholesalers</relationshipLabel>
        <relationshipName>Wholesalers1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wholesaler_Name__c</fullName>
        <description>Wholesaler Name</description>
        <inlineHelpText>Do we need this anymore....</inlineHelpText>
        <label>Wholesaler Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Wholesaler</label>
    <nameField>
        <label>Wholesaler</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wholesalers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/classes/DealItem_Controller.cls
/* Class Name : DealItem_Controller
* Description: --
* Created By : --
* Created On : --
*
* Modification Log :  
* ----------------------------------------------------------------------------------------------------------------------------
* Developer          Date              Description
* ----------------------------------------------------------------------------------------------------------------------------
* Tass Tsakiridis    1st May 2012      Initial Coding
*
*/ 
public with sharing class DealItem_Controller {
	private String sortDirection = 'ASC';
	private String sortExp = 'name';
	
	public Group_Promotions__c myDeal { get; set; }
	public string bfBrandValue {get;set;} 
	public string ProductNameTextValue {get;set;}
	public string ProductCodeTextValue {get;set;}      
	public string bfBrandTextValue {get;set;}
	public string DescriptionTextValue {get;set;}   
 	public List<lineItemWrapper> myDealItems {get;set;}
	//Intial ProdSelection with Strucure <wrapper>  
    //public List<materialGroupWrapper> MaterialGroupSelection {get;set;}  
    public String sortExpression {
    	get { 
    		return sortExp;
    	}
    	set {
    		if (value == sortExp) {
    			sortDirection = (sortDirection == 'ASC') ? 'DESC' : 'ASC';
    		} else {
    			sortDirection = 'ASC';
    		}
    		sortExp = value;
    	}
    }
    
	public Group_Promotion_Item__c  myDealItem;
		
	//Custom Wrapper class for LineItem    
    public class lineItemWrapper {
        public Group_Promotion_Item__c dealItem {get; set;}
    	public boolean selected {get; set;}
    	public Id materialGroup {
    		get {
    			if (dealItem == null) { 
    				return null; 
    			} else {
    				return dealItem.Reference_Material_Group__c;
    			}
    		}
    	}
    	public double discountAmount { 
    		get {
    			if (dealItem == null) { 
    				return 0;
    			} else {
    				return dealItem.Discount_Amount__c;
    			}
    		}
    	}
    	public double priceVision {
    		get {
    			if (dealItem == null) {
    				return 0;
    			} else {
    				return dealItem.Price_Vision__c;
    			}
    		}
    	}
    	public string priceVisionType {
    		get {
    			if (dealItem == null) {
    				return '';
    			} else {
    				return dealItem.Price_Vision_Type__c;
    			}
    		}
    	}
    	public double ongoingDiscount {
    		get {
    			if (dealItem == null) {
    				return 0;
    			} else {
    				return dealItem.OnGoing__c;
    			}
    		}
    	}
    	public string conditionTypes {
    		get {
    			if (dealItem == null) {
    				return '';
    			} else {
    				return dealItem.Condition_Types__c;
    			}
    		}
    	}
      
      	void Init() {
			selected = false;
			dealItem = new Group_Promotion_Item__c();
      	}
//I need to exstend this....    
		public lineItemWrapper () {
			Init();
		}
    	public lineItemWrapper (Group_Promotions__c o, Group_Promotion_Item__c oi, Reference_Material_Group__c a){
    		Init();
    		
    		dealItem = oi;
    		if (oi == null) {
    			dealItem = new Group_Promotion_Item__c();
    			List<RecordType> recordTypes = [SELECT Name FROM RecordType WHERE Id =:o.RecordTypeId];
  				dealItem.RecordTypeId = [SELECT Id FROM RecordType WHERE SObjectType = 'Group_Promotion_Item__c' AND Name =:(recordTypes[0].Name + ' Item')][0].Id;
    			dealItem.Group_Promotion__c = o.Id;
    			if (a != null) {
    				dealItem.Reference_Material_Group__c = a.Id;
    			}
    		}
    	}
    }  
	//End lineItemWrapper
	
	/*
	//Custom Wrapper class for the Product List    
    public class materialGroupWrapper {
	    public Reference_Material_Group__c materialGroup {get; set;}
    	public boolean selected {get; set;}
    	public List<lineItemWrapper> myDealItems { get; set; } 
               
		//Tass - What is the code below doing?
    	public materialGroupWrapper(Reference_Material_Group__c a) {
    		// This code is acting as the constructor for the wrapperP class.
            materialGroup = a;
            selected=false;
        }
    }    
	//End productWrapper
	*/
	
   	public DealItem_Controller (ApexPages.StandardController controller) {
        this.myDeal = (Group_Promotions__c)controller.getRecord();
        this.myDeal = [SELECT Name, RecordTypeId, RecordTypeName__c, Deal_Type__c, Deal_Method__c, Deal_Display_Helper_Type__c, Buy_Period_Start_Date__c, Account__c, AccountName__c, AccountNumber__c, Banner_Group__c, Banner_Group_Name__c, Status__c, Account_Wholesaler__c, Wholesaler__c, Wholesaler_Name__c FROM Group_Promotions__c WHERE Id =:this.myDeal.Id];
	    
      
      	//Building my list of items
      	buildDealItems();
    }   
	//End of Declaration Stuff    
    
 	//For Closing the Page link back to Order Item   
    public PageReference close(){
        return new PageReference('/'+myDeal.id);
    }      
	public PageReference saveAndClose() {
		saveAction();
		return close();
	}
	public PageReference addLine() {
		myDealItems.add(new lineItemWrapper(this.myDeal, null, null));
		return null;
	}
	
	public PageReference saveAction(){  
        Savepoint sp = Database.setSavepoint();     
        
		// Not Sure why they use a Try Block - Ask Shroyer
		// Answer: A try block is to catch any exceptions that may occur and cater for them without breaking the page        
        try{
        	if (myDealItems.size() > 0) {
        		Group_Promotion_Item__c di;
        		List<Group_Promotion_Item__c> items = new List<Group_Promotion_Item__c>();
        		for(lineItemWrapper item: myDealItems) {
        			if (item.dealItem.Reference_Material_Group__c != null) {
        				items.add(item.dealItem);        				
        			}
        		}
        		
        		if (items.size() > 0) {
        			insert items;    
        		}        		
	
	            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM, 'number of items to insert: ' + items.size()));
        	}
            
            
        }catch(System.DmlException insertDmlexp){
        	Database.rollback(sp);
            for (Integer i = 0; i < insertDmlexp.getNumDml(); i++) {
            	ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, insertDmlexp.getDmlMessage(i)));
            }
        }  
        
        return null;
    }    
    
    public PageReference BuildLineItems() {
    	// Use this function only for test method as buildOrderItems is private. Will remove after test method completes
    	buildDealItems();
    	return null;
    }

	//Get Deal Items
	void buildDealItems() {
	
	 	if (myDealItems == null) {
	 		myDealItems = new List<lineItemWrapper>();
	 	}
	 	
		for(Group_Promotion_Item__c oi: [SELECT p.Reference_Material_Group__c, Reference_Material_Group_Number__c, p.Ongoing__c, p.Discount_Amount__c, p.Price_Vision__c, p.Price_Vision_Type__c, p.RecordTypeId FROM Group_Promotion_Item__c p WHERE p.Group_Promotion__c =: this.myDeal.Id]) {
			this.myDealItems.add(new lineItemWrapper(this.myDeal, oi, null));							
		}
	}


	public PageReference removeDealItems(){
		if (this.myDealItems == null) { return null; }
		
		integer numberOfItems = this.myDealItems.size();

		try {
			for(integer i = numberOfItems - 1; i >= 0; i--) {
				lineItemWrapper wr = this.myDealItems.get(i);
				if (wr.selected == true) {
					if (wr.dealItem.Id != null) { delete wr.dealItem; }
						
					this.myDealItems.remove(i);					
				}
			}  
			
		} catch(System.DMLException ex) {
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, ex.getMessage()));
		}		

        return null;
    }        

}