B-F Sandbox Full-Backup/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Channel__c</fullName>
        <description>INFOWELDERS</description>
        <label>Channel</label>
        <picklist>
            <picklistValues>
                <fullName>On</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Sellable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wholesaler</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sub_Wholesaler</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INTEG MAINLY ON</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INTEG MAINLY OFF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ON PREMISE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OFF PREMISE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INTEGRATED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NON RETAIL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UNCLASSIFIED</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used by CRM.
NPA Rollout: Used to store the Market reference.</description>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>INFOWELDERS</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Former</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Potential</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Telesales</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Substitution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Temporary substitution of the account owner to allow further work as a other sales rep on outlet visits</description>
        <label>Substitution</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>EUR_Outlets</fullName>
        <active>true</active>
        <description>European - Outlets</description>
        <label>EUR - Outlets</label>
    </recordTypes>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Market__c.object
<CustomObject>
    <description>Used by CRM.
NPA Rollout: Used to store Markets at State Level.</description>
    <fields>
        <fullName>Market_Code__c</fullName>
        <description>Used to store technical code for respective markets</description>
        <externalId>true</externalId>
        <label>Market Code</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Off_Channel__c</fullName>
        <description>This field is used by the Outlet Visit page to determine what grid-layout to use in the B-F and Competitor Brands sections. This Off Channel references the value selected in the related Account.Channel__c field value.</description>
        <inlineHelpText>Used by the Outlet Visit page to determine what grid-layout to use in the B-F and Competitor Brands sections. This &quot;Off Channel&quot; references the value in the related Account.Channel__c field value.
1-Standard Layout
2-Euro Off
3-Euro On</inlineHelpText>
        <label>Off Channel</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>On_Channel__c</fullName>
        <description>This field is used by the Outlet Visit page to determine what grid-layout to use in the B-F and Competitor Brands sections. This On Channel references the value selected in the related Account.Channel__c field value.</description>
        <inlineHelpText>Used by the Outlet Visit page to determine what grid-layout to use in the B-F and Competitor Brands sections. This &quot;On Channel&quot; references the value in the related Account.Channel__c field value.
1-Standard Layout
2-Euro Off
3-Euro On</inlineHelpText>
        <label>On Channel</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Outlet_Visit__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Outlet (Account)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Outlet Visits</relationshipLabel>
        <relationshipName>Outlet_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Visit__c</fullName>
        <defaultValue>false</defaultValue>
        <description>P00001  - Created by PARX to improve reporting on Last Visits</description>
        <label>Last Visit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Met_With__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Met With (Contact)</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Outlet Visits</relationshipLabel>
        <relationshipName>Outlet_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Next_to_Last_Visit__c</fullName>
        <defaultValue>false</defaultValue>
        <description>P00001  - Created by PARX to improve reporting on Last Visits</description>
        <label>Next to Last Visit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Visit_Date__c</fullName>
        <label>Visit Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Outlet Visit</label>
    <nameField>
        <displayFormat>OV-{00000}</displayFormat>
        <label>Outlet Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outlet Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Market__c</fullName>
        <description>INFOWELDERS - These text values MUST match the Market Name records&apos; text values.
NPA Rollout: Used to store the markets a user is allocated to. Multiple values can be used separated by semi-colon.</description>
        <inlineHelpText>CRM: Market at a Country level-  such as Germany, Korea, India, Japan etc.
NPA: Market at a State level-  such as Illinois, Kentucky etc.</inlineHelpText>
        <label>Market</label>
        <picklist>
            <picklistValues>
                <fullName>ALL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Germany</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Japan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Korea</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thailand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Taiwan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>India</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canada General</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

B-F Sandbox Full-Backup/src/classes/SubstitutionTest.cls
/**
  * Unit test
  *
  * If a sales rep. must be temporarily replaced, the represenatative
  * needs read permission on the last outlet visit, to continue the
  * recording of further outlet visits till the appropriate field is 
  * not clear. 
  *      
  * @date    04/24/2012
  * @author  Michael Mickiewicz
  **/
@isTest
private class SubstitutionTest {

    static testMethod void myUnitTest() {
    	Account acc;
    	Contact con;
    	
        Profile p = [Select ID From Profile Where Name = 'DEU_LEVEL_TWO' limit 1];
        User u = [Select ID From User Where ProfileID =: p.ID AND ID <> :UserInfo.getUserId() AND isActive = true limit 1];
        User u1 = [Select ID From User Where ProfileID =: p.ID AND ID <> :UserInfo.getUserId() AND isActive = true AND ID <> :u.ID limit 1];
        
        Date visit_date = Date.newInstance( system.today().year(), system.today().month()-2, system.today().day());
        Outlet_Visit__c outlet;
        
        test.startTest();
	        system.runas(u) {
	        	RecordType RT = [select id from RecordType where sObjectType = 'Account' AND developerName = 'EUR_Outlets' limit 1];
    			Market__c market = new Market__c(Market_Code__c = 'GER', Name = 'Germany', Off_Channel__c = '1', On_Channel__c = '1');
        		insert market;
        		acc = new Account(Name = 'PARX', Market__c = market.Id, RecordTypeId = RT.Id, Channel__c = 'On', BillingCountry = 'DE');
        		insert acc;
        		con = new Contact(LastName = 'Roger', AccountId = acc.Id);
        		insert con;
	        	
	        	outlet = new Outlet_Visit__c(Visit_Date__c = visit_date);
	        	outlet.Account__c = acc.Id;
	        	outlet.Met_With__c = con.Id;
	        	insert outlet;
	        	system.assertEquals(false, outlet.Last_Visit__c);
	        	system.assertEquals(false, outlet.Next_to_Last_Visit__c);
	        	
	        	Outlet_Visit_Helper.hasAlreadyRun = false;
	        	outlet.Status__c = 'Complete';
	        	update outlet;
	        	outlet = [select Last_Visit__c, Next_to_Last_Visit__c from Outlet_Visit__c where Id =: outlet.Id];
	        	system.assertEquals(true, outlet.Last_Visit__c);
	        	system.assertEquals(false, outlet.Next_to_Last_Visit__c);
	        	
	        	acc.substitution__c = u.ID;
        		update acc;
	        }
	        
        	system.runas(u1) {
	        	system.debug('BEFORE: '+visit_date);
	        	visit_date = Date.newInstance( system.today().year(), system.today().month()-1, system.today().day());
	        	system.debug('AFTER: '+visit_date);
	        	Outlet_Visit_Helper.hasAlreadyRun = false;
	        	Outlet_Visit__c outlet2 = new Outlet_Visit__c(Visit_Date__c = visit_date, Account__c = acc.Id, Met_With__c = con.Id);
	        	outlet2.Status__c = 'Complete';
	        	insert outlet2;
	        	outlet = [select Last_Visit__c, Next_to_Last_Visit__c, Visit_Date__c from Outlet_Visit__c where Id =: outlet.Id];
	        	outlet2 = [select Last_Visit__c, Next_to_Last_Visit__c, Visit_Date__c from Outlet_Visit__c where Id =: outlet2.Id];
	        	system.debug(outlet.ID+': '+outlet.Visit_Date__c);
	        	system.debug(outlet2.ID+': '+outlet2.Visit_Date__c);
	        	system.assertEquals(false, outlet.Last_Visit__c);
	        	system.assertEquals(true, outlet.Next_to_Last_Visit__c);
	        	system.assertEquals(true, outlet2.Last_Visit__c);
	        	system.assertEquals(false, outlet2.Next_to_Last_Visit__c);
        	}
        		
        	system.runas(u1) {
	        	system.debug('BEFORE: '+visit_date);
	        	visit_date = Date.newInstance( system.today().year(), system.today().month()-1, system.today().day());
	        	system.debug('AFTER: '+visit_date);
	        	Outlet_Visit_Helper.hasAlreadyRun = false;
	        	Outlet_Visit__c outlet3 = new Outlet_Visit__c(Visit_Date__c = visit_date, Account__c = acc.Id, Met_With__c = con.Id);
	        	outlet3.Status__c = 'Complete';
	        	insert outlet3;
	        	
	        	acc.substitution__c = null;
        		update acc;
        	}	
        	
        	system.runas(u) {
	        	system.debug('BEFORE: '+visit_date);
	        	visit_date = Date.newInstance( system.today().year(), system.today().month()-1, system.today().day());
	        	system.debug('AFTER: '+visit_date);
	        	Outlet_Visit_Helper.hasAlreadyRun = false;
	        	Outlet_Visit__c outlet4 = new Outlet_Visit__c(Visit_Date__c = visit_date, Account__c = acc.Id, Met_With__c = con.Id);
	        	outlet4.Status__c = 'Complete';
	        	insert outlet4;
        	}	
        test.stopTest();
    }
}