B-F Sandbox Full-Backup/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Banner_Group__c</fullName>
        <description>Account Customer Group</description>
        <label>Banner Group</label>
        <picklist>
            <picklistValues>
                <fullName>1ST CHOICE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5 STAR CELLARS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9-11 GROUP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A.L.M.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACCOR HOTELS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AIRLINES/AIRPOR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AJC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALBION PARK CEL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALDI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALH GROUP LTD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALL SEASONS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALM GOLD CLUBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALPHA SERVICE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMATOS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANSETT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASHOK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUR FOODWORKS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AVS CATERING</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BARGAINS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAR-GAINS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BASIX LIQUOR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BIG BARGAIN GRP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BLUE HILLS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BONUS LIQUOR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BOOTLEG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BOOZE BROS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BOSS GROUP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BOTTLEMART ADV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BOTTLEMART BUY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BOTTLEMART EXPR</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Account_Wholesaler__c.object
<CustomObject>
    <description>Wholesales Junction Object</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Wholesalers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Banner_Partner__c</fullName>
        <label>Banner Partner</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Wholesaler__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Wholesaler</label>
        <referenceTo>Wholesaler__c</referenceTo>
        <relationshipName>Wholesaler</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Wholesaler</label>
    <nameField>
        <displayFormat>WHSL-{0}</displayFormat>
        <label>Account Wholesaler</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Wholesalers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Banner_Group_Wholesaler_Junction__c.object
<CustomObject>
    <fields>
        <fullName>Banner_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Banner Group</label>
        <referenceTo>Banner_Groups__c</referenceTo>
        <relationshipLabel>Banner Group Wholesalers Junction</relationshipLabel>
        <relationshipName>Banner_Group_Wholesalers_Junction</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wholesaler__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Wholesaler</label>
        <referenceTo>Wholesaler__c</referenceTo>
        <relationshipLabel>Banner Group Wholesalers Junction</relationshipLabel>
        <relationshipName>Banner_Group_Wholesalers_Junction</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Banner Group Wholesaler Junction</label>
    <nameField>
        <label>Banner Group Wholesaler Junction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Banner Group Wholesalers Junction</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Wholesaler__c.object
<CustomObject>
    <description>Australia Wholesaler Object</description>
    <label>Wholesaler</label>
    <nameField>
        <label>Wholesaler</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wholesalers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Wholesaler_Banner_Group_Index__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>Wholesaler__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Wholesaler</label>
        <referenceTo>Wholesaler__c</referenceTo>
        <relationshipLabel>Wholesalers</relationshipLabel>
        <relationshipName>Wholesalers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Wholesaler Banner Group Index</label>
    <nameField>
        <displayFormat>WBG-{0}</displayFormat>
        <label>Wholesaler Banner Groups Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wholesaler Banner Group Indexes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

B-F Sandbox/trunk/src/classes/Build_Rep_WholesalerBannerGroup_Index.cls
public with sharing class Build_Rep_WholesalerBannerGroup_Index {
	public void BuildIndex(string repUserName) {
		List<Banner_Group_Wholesaler_Junction__c> bwList = [SELECT Id FROM Banner_Group_Wholesaler_Junction__c];
		delete bwList;
		
		string soql = 'SELECT Id, Name, Banner_Group__c, (SELECT Id, Name, Wholesaler__c, Banner_Partner__c FROM Account_Wholesaler__c) FROM Account';
		if (repUserName != null && repUserName.length() > 0) {
			List<User> users = [SELECT Id FROM User WHERE UserName =:repUserName];
			if (users != null && users.size() > 0) {
				soql += ' WHERE OwnerId = \'' + users[0].Id + '\'';				
			}
		}
		
		soql += ' ORDER BY OwnerId';
		List<Account> accounts = Database.query(soql);

		Set<String> combinations = null;		
		List<Banner_Group_Wholesaler_Junction__c> banList = new List<Banner_Group_Wholesaler_Junction__c>();
		Map<Id, Set<String>> uniqueKeys = new Map<Id, Set<String>>();		
		String uniqueKey = '';
		boolean keyFound = false;
		
		for(Account a: accounts) {
			if (a.Wholesalers__r != null) {
				for(Account_Wholesaler__c aw: a.Wholesalers__r) {
					keyFound = false;
					uniqueKey = aw.Wholesaler__c + '-' + aw.Banner_Partner__c;
					combinations = uniqueKeys.get(a.OwnerId);
					if (combinations == null || combinations.size() == 0) {
						combinations = new Set<String>();
					}
					if (!combinations.contains(uniqueKey)) {
						combinations.add(uniqueKey);
						uniqueKeys.put(a.OwnerId, combinations);
						
						Banner_Group_Wholesaler_Junction__c iObj = new Banner_Group_Wholesaler_Junction__c();
						iObj.Banner_Group__c = aw.Banner_Partner__c;
						iObj.Wholesaler__c = aw.Wholesaler__c; 
						iObj.OwnerId = a.OwnerId;
						banList.add(iObj);						
					}
				}
			}
		}
		
		if (banList.size() > 0) {
			insert banList;
		}
	}
}