B-F Sandbox Full-Backup/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Channel__c</fullName>
        <description>INFOWELDERS</description>
        <label>Channel</label>
        <picklist>
            <picklistValues>
                <fullName>On</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Sellable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wholesaler</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sub_Wholesaler</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INTEG MAINLY ON</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INTEG MAINLY OFF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ON PREMISE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OFF PREMISE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INTEGRATED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NON RETAIL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UNCLASSIFIED</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used by CRM.
NPA Rollout: Used to store the Market reference.</description>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>EUR_Outlets</fullName>
        <active>true</active>
        <description>European - Outlets</description>
        <label>EUR - Outlets</label>
    </recordTypes>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Account_Brand__c.object
<CustomObject>
    <description>INFOWELDERS - Brands Related to this Account</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>INFOWELDERS</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Brands</relationshipLabel>
        <relationshipName>Account_Brands</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>INFOWELDERS</description>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>Account Brands</relationshipLabel>
        <relationshipName>Account_Brands</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Depletion_Actuals__c</fullName>
        <description>INFOWELDERS - Depletion actuals for this brand at this outlet for this fiscal year as calculated based on depletion records</description>
        <inlineHelpText>Depletion actuals for this brand at this outlet for this fiscal year</inlineHelpText>
        <label>Depletion Actuals</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Account Brand</label>
    <nameField>
        <displayFormat>AB-{0000000}</displayFormat>
        <label>Account Brands Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Brands</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

B-F Backup Sandbox 30.4.12/src/objects/Brand__c.object
<CustomObject>
    <description>Used by CRM.
NPA Rollout: Used to store Brands.</description>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Market__c.object
<CustomObject>
    <description>Used by CRM.
NPA Rollout: Used to store Markets at State Level.</description>
    <fields>
        <fullName>Market_Code__c</fullName>
        <description>Used to store technical code for respective markets</description>
        <externalId>true</externalId>
        <label>Market Code</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Off_Channel__c</fullName>
        <description>This field is used by the Outlet Visit page to determine what grid-layout to use in the B-F and Competitor Brands sections. This Off Channel references the value selected in the related Account.Channel__c field value.</description>
        <inlineHelpText>Used by the Outlet Visit page to determine what grid-layout to use in the B-F and Competitor Brands sections. This &quot;Off Channel&quot; references the value in the related Account.Channel__c field value.
1-Standard Layout
2-Euro Off
3-Euro On</inlineHelpText>
        <label>Off Channel</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>On_Channel__c</fullName>
        <description>This field is used by the Outlet Visit page to determine what grid-layout to use in the B-F and Competitor Brands sections. This On Channel references the value selected in the related Account.Channel__c field value.</description>
        <inlineHelpText>Used by the Outlet Visit page to determine what grid-layout to use in the B-F and Competitor Brands sections. This &quot;On Channel&quot; references the value in the related Account.Channel__c field value.
1-Standard Layout
2-Euro Off
3-Euro On</inlineHelpText>
        <label>On Channel</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Outlet_Visit__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Outlet (Account)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Outlet Visits</relationshipLabel>
        <relationshipName>Outlet_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Met_With__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Met With (Contact)</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Outlet Visits</relationshipLabel>
        <relationshipName>Outlet_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Visit_Date__c</fullName>
        <label>Visit Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Outlet Visit</label>
    <nameField>
        <displayFormat>OV-{00000}</displayFormat>
        <label>Outlet Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outlet Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

B-F Backup Sandbox 30.4.12/src/objects/Outlet_Visit_Item__c.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>Custom_Product__r.Brand__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <formula>TEXT(Outlet_Visit__r.Venue__r.Channel__c)</formula>
        <label>Channel</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Custom_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created for Product Remediation process</description>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Outlet Visit Items</relationshipLabel>
        <relationshipName>Outlet_Visit_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Facing__c</fullName>
        <description>Infowelders</description>
        <label>Facing</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Outlet_Visit__c</fullName>
        <label>Outlet Visit</label>
        <referenceTo>Outlet_Visit__c</referenceTo>
        <relationshipLabel>Outlet Visit Items</relationshipLabel>
        <relationshipName>Outlet_Visit_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Outlet Visit Items</relationshipLabel>
        <relationshipName>Outlet_Visit_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Outlet Visit Item</label>
    <nameField>
        <label>Outlet Visit Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Outlet Visit Items</pluralLabel>
    <recordTypes>
        <fullName>Germany</fullName>
        <active>true</active>
        <label>Germany</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

B-F Backup Sandbox 30.4.12/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Infowelders</description>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <label>Channel</label>
        <picklist>
            <picklistValues>
                <fullName>On</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Both</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Infowelders</description>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Product__c.object
<CustomObject>
    <description>NPA Rollout: Object for storing Products used in National Promotion application.
Product Remediation : Replicated all standard product fields here.</description>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Infowelders, NPA Rollout: Used to store the related Brand</description>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipName>Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <description>Created as a part of product remediation</description>
        <label>Channel</label>
        <picklist>
            <picklistValues>
                <fullName>On</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Both</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created as a part of product remediation</description>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>ProductsCustom</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <description>NPA Rollout: Stores the product code</description>
        <label>Product Unique Key</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

B-F Sandbox/trunk/src/classes/Test_Outlet_Visit_Item_Helper.cls
@isTest
private class Test_Outlet_Visit_Item_Helper {
    /**
     * we run the trigger on Outlet Visit Item to update the brand depletion actuals.
     *Conditions: 
     *  +Account RecordType: EUR_Outlets (or "DEU_Outlets")
     *  +onUpdate, Brand or Facing or Channel (Account) has changed
     *
     * On delete, we have to get the event from the on Outlet Visit trigger because there is no event in the outlet Visit Item
     * We refresh always all the records of the account to make sure everything is fine for every event.
     * If the Channel is on, then Depletion actuals is 1 else it's the sum of the facing grouped by brand.
     * If the brand does not exist, it has to be created, else it has to be updated (the Depletion Actual).
     *   
     * @date    30.11.2011
     * @author  Christophe Vidal
    */
    static testMethod void myUnitTest() {
        RecordType RT = [select id from RecordType where sObjectType = 'Account' AND developerName = 'EUR_Outlets' limit 1];
        Market__c market = new Market__c(Market_Code__c = 'GER', Name = 'Germany', Off_Channel__c = '1', On_Channel__c = '1');
        insert market;
        Account acc = new Account(Name = 'PARX', Market__c = market.Id, RecordTypeId = RT.Id, Channel__c = 'Off', BillingCountry = 'DE');
        insert acc;
        Contact con = new Contact(LastName = 'Roger', AccountId = acc.Id);
        insert con;
        
        Outlet_Visit__c outlet = new Outlet_Visit__c(Visit_Date__c = system.today());
        outlet.Account__c = acc.Id;
        outlet.Met_With__c = con.Id;
        insert outlet;
        
        //brand: we choose an already existing brand: Jack Daniel's
        Product__c Product = [select id from Product__c where Brand__r.Name = 'Jack Daniel\'s' limit 1];
        Product__c Product2 = [select id from Product__c where Brand__r.Name = 'Herradura' limit 1];
        
        test.startTest();
            Outlet_Visit_Item__c OVI = new Outlet_Visit_Item__c();
            OVI.Outlet_Visit__c = outlet.Id;
            OVI.Facing__c = 10;
            OVI.Custom_Product__c = Product.Id;
            insert OVI;
            list<Account_Brand__c> AccountBrand = new list<Account_Brand__c>([select id, Depletion_Actuals__c from Account_Brand__c where Account__c =: acc.Id AND Brand__r.Name = 'Jack Daniel\'s']);
            system.assertEquals(10, AccountBrand.get(0).Depletion_Actuals__c);
            
            AccountBrand.get(0).Depletion_Actuals__c = null;
            update AccountBrand;
            Outlet_Visit_Item__c OVI2 = new Outlet_Visit_Item__c();
            OVI2.Outlet_Visit__c = outlet.Id;
            OVI2.Facing__c = 20;
            OVI2.Custom_Product__c = Product.Id;
            insert OVI2;
            AccountBrand = new list<Account_Brand__c>([select id, Depletion_Actuals__c from Account_Brand__c where Account__c =: acc.Id AND Brand__r.Name = 'Jack Daniel\'s']);
            system.assertEquals(30, AccountBrand.get(0).Depletion_Actuals__c);
            
            acc.Channel__c = 'On';
            update acc;
            
            AccountBrand.get(0).Depletion_Actuals__c = null;
            update AccountBrand;
            Outlet_Visit_Item__c OVI3 = new Outlet_Visit_Item__c();
            OVI3.Outlet_Visit__c = outlet.Id;
            OVI3.Facing__c = 20;
            OVI3.Custom_Product__c = Product2.Id;
            insert OVI3;
            AccountBrand = new list<Account_Brand__c>([select id, Depletion_Actuals__c from Account_Brand__c where Account__c =: acc.Id AND Brand__r.Name = 'Jack Daniel\'s']);
            system.assertEquals(1, AccountBrand.get(0).Depletion_Actuals__c);
            AccountBrand = new list<Account_Brand__c>([select id, Depletion_Actuals__c from Account_Brand__c where Account__c =: acc.Id AND Brand__r.Name = 'Herradura']);
            system.assertEquals(1, AccountBrand.get(0).Depletion_Actuals__c);
            
            
            AccountBrand = new list<Account_Brand__c>([select id, Depletion_Actuals__c from Account_Brand__c where Account__c =: acc.Id AND Brand__r.Name = 'Jack Daniel\'s']);
            system.assertEquals(1, AccountBrand.get(0).Depletion_Actuals__c);
            delete outlet;
            AccountBrand = new list<Account_Brand__c>([select id, Depletion_Actuals__c from Account_Brand__c where Account__c =: acc.Id AND Brand__r.Name = 'Jack Daniel\'s']);
            system.assertEquals(0, AccountBrand.get(0).Depletion_Actuals__c);
        test.stopTest();
    }
}