B-F Sandbox Full-Backup/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used by CRM.
NPA Rollout: Used to store the Market reference.</description>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Market__c.object
<CustomObject>
    <description>Used by CRM.
NPA Rollout: Used to store Markets at State Level.</description>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Promotion__c.object
<CustomObject>
    <description>Used by CRM.
NPA Rollout: Used to store Promotions.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Infowelders</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Promotions</relationshipLabel>
        <relationshipName>Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <formula>Account__r.Market__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Market</label>
        <type>Text</type>
    </fields>
    <label>Promotion</label>
    <nameField>
        <label>Promotion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

B-F Backup Sandbox 30.4.12/src/objects/Promotion_Material_Item__c.object
<CustomObject>
    <description>Used by CRM.
NPA Rollout: Used to store products added to Promotions (Promotion line items).</description>
    <fields>
        <fullName>Promotion__c</fullName>
        <description>Infowelders: Used by CRM.
		NPA Rollout: Used to refer to Promotion.</description>
        <label>Promotion</label>
        <referenceTo>Promotion__c</referenceTo>
        <relationshipLabel>Promotion Material Items</relationshipLabel>
        <relationshipName>Promotion_Material_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Promotion Material Item</label>
    <nameField>
        <displayFormat>PMI-{YYYY}{00000}</displayFormat>
        <label>Promotion Material Item#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotion Material Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/classes/promotionMaterialItemRedirect_Controller.cls
public with sharing class promotionMaterialItemRedirect_Controller {
	Promotion_Material_Item__c pm;
  
	public promotionMaterialItemRedirect_Controller (ApexPages.StandardController controller)
	{
		this.pm = (Promotion_Material_Item__c)controller.getRecord();
		pm = [Select Promotion__r.RecordTypeId, Promotion__r.Account__r.Market__r.Name, Promotion__c From Promotion_Material_Item__c p where Id=:pm.Id];
	}
    
	public PageReference Redirect()
	{
		String recordtypname = '';
		recordtypname = [select Id from RecordType where Name = 'National Promotion - US'][0].Id;
		if(recordtypname.equalsIgnoreCase(pm.Promotion__r.RecordTypeId)){
			PageReference p = Page.NPA_promotionMaterialCustomEdit;
			p.getParameters().put('id',pm.Id);
			p.getParameters().put('promotion','/'+pm.Promotion__c);
			p.setRedirect(true);
			return p;
		}
		else {
			PageReference ref = Page.promotionMaterialItem;
			if(pm.Promotion__r.Account__c!=null && pm.Promotion__r.Account__r.Market__r.Name.contains('Germany')) {
				ref = Page.promotionMaterialItem_deu;	
			}
			
			ref.getParameters().put('id',pm.Promotion__c);
			return ref;
		}
	}
}