B-F Sandbox Full-Backup/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Group_Promotion__c</fullName>
        <label>Group Promotion</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Australia/Wombat Use</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used by CRM.
NPA Rollout: Used to store the Market reference.</description>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Account_Wholesaler__c.object
<CustomObject>
    <description>Wholesales Junction Object</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Wholesalers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Checked is active</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Legacy_Code__c</fullName>
        <label>Legacy Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Wholesaler__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Wholesaler</label>
        <referenceTo>Wholesaler__c</referenceTo>
        <relationshipName>Wholesaler</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Wholesaler</label>
    <nameField>
        <displayFormat>WHSL-{0}</displayFormat>
        <label>Account Wholesaler</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Wholesalers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

B-F Backup Sandbox 30.4.12/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Legacy_Code__c</fullName>
        <label>Legacy Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Group_Promotion_Item__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Group_Promotion_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Discount_Amount__c</fullName>
        <description>Discount Amount per Case</description>
        <inlineHelpText>Discount Amount per Case</inlineHelpText>
        <label>Discount per Case</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Group_Promotion__c</fullName>
        <label>Deal</label>
        <referenceTo>Group_Promotions__c</referenceTo>
        <relationshipLabel>Deal Items</relationshipLabel>
        <relationshipName>Group_Promotion_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Legacy_Code__c</fullName>
        <label>Legacy Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reference_Material_Group_Number__c</fullName>
        <formula>Reference_Material_Group__r.Reference_Material_Group_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Reference Material Group Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reference_Material_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference Material Group</description>
        <label>Reference Material Group</label>
        <referenceTo>Reference_Material_Group__c</referenceTo>
        <relationshipLabel>Deal Items</relationshipLabel>
        <relationshipName>Group_Promotion_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deal Item</label>
    <nameField>
        <displayFormat>GPI-{0}</displayFormat>
        <label>Group Promotion Item  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Group_Promotions__c.object
<CustomObject>
    <description>Group Promotion (Banner Group)</description>
    <fields>
        <fullName>Account_Wholesaler__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account Wholesaler</description>
        <inlineHelpText>Account Wholesaler</inlineHelpText>
        <label>Account Wholesaler</label>
        <referenceTo>Account_Wholesaler__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Group_Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legacy_Code__c</fullName>
        <label>Legacy Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Wholesaler__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the individual wholesaler shed (ie, ALM NSW)</inlineHelpText>
        <label>Wholesaler</label>
        <referenceTo>Wholesaler__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Group_Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>Deal-{0}</displayFormat>
        <label>Deal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Market__c.object
<CustomObject>
    <description>Used by CRM.
NPA Rollout: Used to store Markets at State Level.</description>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Reference_Material_Group__c.object
<CustomObject>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Legacy_Code__c</fullName>
        <label>Legacy Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reference_Material_Group_Number__c</fullName>
        <description>Reference Material Group Number</description>
        <externalId>true</externalId>
        <label>Reference Material Group Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Reference Material Group</label>
    <nameField>
        <label>Reference Material Group Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reference Material Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Market__c</fullName>
        <description>INFOWELDERS - These text values MUST match the Market Name records&apos; text values.
NPA Rollout: Used to store the markets a user is allocated to. Multiple values can be used separated by semi-colon.</description>
        <inlineHelpText>CRM: Market at a Country level-  such as Germany, Korea, India, Japan etc.
NPA: Market at a State level-  such as Illinois, Kentucky etc.</inlineHelpText>
        <label>Market</label>
        <picklist>
            <picklistValues>
                <fullName>ALL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Germany</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Japan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Korea</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thailand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Taiwan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>India</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canada General</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Wholesaler__c.object
<CustomObject>
    <description>Australia Wholesaler Object</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Wholesalers</relationshipLabel>
        <relationshipName>Wholesalers1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Checked is active</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Legacy_Code__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>Do we need this field? It&apos;s not coming from ECC will this be loaded from Possum</inlineHelpText>
        <label>Legacy Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Wholesalers</relationshipLabel>
        <relationshipName>Wholesalers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Wholesaler</label>
    <nameField>
        <label>Wholesaler</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wholesalers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/classes/Test_DealItem_Redirect_Controller.cls
@isTest
private class Test_DealItem_Redirect_Controller {
	static testMethod void unitTest1() {
        INFW_TestHelper helper = new INFW_TestHelper();
        User u1 = helper.createUser();
        Profile []p1 = [select id from Profile where Name = 'System Administrator' LIMIT 1];        
        u1.ProfileID = p1[0].id;      
        insert u1;		
        		
		RecordType p_rt = [SELECT r.Name, r.Id FROM RecordType r WHERE r.Name = 'Outlet Deal' AND SObjectType = 'Group_Promotions__c'];       
        RecordType o_rt = [SELECT r.Name, r.Id FROM RecordType r WHERE  r.Name = 'Group Deal' AND SObjectType = 'Group_Promotions__c'];

		List<Market__c> markets = [SELECT Id FROM Market__c WHERE Name = 'Australia'];
	
		Account a = new Account();
		a.Name = 'test account';
		a.Market__c = markets[0].Id;
		insert a;
		
		Contact c = new Contact();
		c.AccountId = a.Id;
		c.FirstName = 'test';
		c.LastName = 'contact';
		insert c;
		
		Wholesaler__c wsaler = new Wholesaler__c();
		wsaler.Name = 'test Wholesaler';
		wsaler.Account__c = a.Id;
		wsaler.Is_Active__c = true;
		wsaler.Market__c = markets[0].Id;
		insert wsaler;
		
		Account_Wholesaler__c aw = new Account_Wholesaler__c();
		aw.Account__c = a.Id;
		aw.Wholesaler__c = wsaler.Id;
		insert aw; 
						
		Reference_Material_Group__c m1 = new Reference_Material_Group__c();
		m1.Is_Active__c = true;
		m1.Legacy_Code__c = 'LEG001';
		m1.Reference_Material_Group_Number__c = 'mat001';
		insert m1;
		
		Reference_Material_Group__c m2 = new Reference_Material_Group__c();
		m2.Is_Active__c = true;
		m2.Legacy_Code__c = 'LEG002';
		m2.Reference_Material_Group_Number__c = 'mat002';
		insert m2;

		System.runAs(u1) {
			Group_Promotions__c o = new Group_Promotions__c();
			o.Account__c = a.Id;
			o.Wholesaler__c = wsaler.Id;
			o.RecordTypeId = o_rt.Id;
			insert o;
			
			Group_Promotion_Item__c oi1 = new Group_Promotion_Item__c();
			oi1.Group_Promotion__c = o.Id;
			oi1.Reference_Material_Group__c = m1.Id;
			oi1.RecordTypeId = [SELECT Id FROM RecordType WHERE Name = 'Outlet Deal Item' AND SObjectType = 'Group_Promotion_Item__c'][0].Id;
			oi1.Discount_Amount__c = 1.5;
			insert oi1;
			
		    PageReference pageRef = Page.dealItem;
		    Test.SetCurrentpage(pageRef);
		    ApexPages.StandardController stdCon = new ApexPages.StandardController(oi1);
		    DealItem_Redirect_Controller oictrl = new DealItem_Redirect_Controller(stdCon);
		    oictrl.Redirect();
		    
		    stdCon = new ApexPages.StandardController(oi1);
		    oictrl = new DealItem_Redirect_Controller(stdCon);
		    oictrl.Redirect();
		}
	}

}