B-F Sandbox Full-Backup/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used by CRM.
NPA Rollout: Used to store the Market reference.</description>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>INFOWELDERS</description>
        <label>Supplier</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts (As Supplier)</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

B-F Backup Sandbox 30.4.12/src/objects/Brand__c.object
<CustomObject>
    <description>Used by CRM.
NPA Rollout: Used to store Brands.</description>
    <fields>
        <fullName>Brand_Code__c</fullName>
        <description>INFOWELDERS: Used by CRM.
NPA Rollout: Used to store the Brand code.</description>
        <externalId>true</externalId>
        <inlineHelpText>Brand Major code</inlineHelpText>
        <label>Brand Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Infowelders:Used by CRM.
NPA Rollout: Used to refer to Supplier.</description>
        <label>Supplier</label>
        <referenceTo>Supplier__c</referenceTo>
        <relationshipLabel>Brands</relationshipLabel>
        <relationshipName>Brands</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

B-F Backup Sandbox 30.4.12/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Brand_Code__c</fullName>
        <description>INFOWELDERS</description>
        <label>Brand Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Infowelders</description>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case_Multiplier__c</fullName>
        <description>INFOWELDERS</description>
        <label>Case Multiplier</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Competes_On_Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>INFOWELDERS - Brand that a competitor product competes against.</description>
        <label>Competes On (Brand)</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>Products (Competes On (Brand))</relationshipLabel>
        <relationshipName>Products1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Infowelders</description>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <description>Infowelders</description>
        <inlineHelpText>This sort order will specify in which order products are listed in outlet visit screens.</inlineHelpText>
        <label>Sort Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <description>Infowelders</description>
        <formula>Brand__r.Supplier__r.Name</formula>
        <label>Supplier</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_Cost__c</fullName>
        <description>Infowelders</description>
        <label>Unit Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>VAT__c</fullName>
        <description>INFOWELDERS</description>
        <inlineHelpText>VAT for this product in this  market. Do not enter a value if VAT does not apply.</inlineHelpText>
        <label>VAT</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Product__c.object
<CustomObject>
    <description>NPA Rollout: Object for storing Products used in National Promotion application.
Product Remediation : Replicated all standard product fields here.</description>
    <fields>
        <fullName>Brand_Code__c</fullName>
        <description>INFOWELDERS</description>
        <label>Brand Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Infowelders, NPA Rollout: Used to store the related Brand</description>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipName>Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case_Multiplier__c</fullName>
        <description>Created as a part of product remediation</description>
        <label>Case Multiplier</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Competes_On_Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>INFOWELDERS - Brand that a competitor product competes against.</description>
        <label>Competes On (Brand)</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipName>ProductCompete</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Product Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Family__c</fullName>
        <label>Product Family</label>
        <picklist>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created as a part of product remediation</description>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>ProductsCustom</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductCode__c</fullName>
        <description>NPA Rollout: Used to store the product code of the POS item.</description>
        <externalId>true</externalId>
        <label>Product Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <description>NPA Rollout: Stores the product code</description>
        <label>Product Unique Key</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <description>Created as a part of product remediation</description>
        <inlineHelpText>This sort order will specify in which order products are listed in outlet visit screens.</inlineHelpText>
        <label>Sort Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <description>Created as a part of product remediation</description>
        <formula>Brand__r.Supplier__r.Name</formula>
        <label>Supplier</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_Cost__c</fullName>
        <description>**Not Used** NPA Rollout:</description>
        <label>Unit/Actual Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>VAT__c</fullName>
        <description>Created as a part of product remediation</description>
        <inlineHelpText>VAT for this product in this  market. Do not enter a value if VAT does not apply.</inlineHelpText>
        <label>VAT</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Promotion__c.object
<CustomObject>
    <description>Used by CRM.
NPA Rollout: Used to store Promotions.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Infowelders</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Promotions</relationshipLabel>
        <relationshipName>Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brand_Code__c</fullName>
        <formula>Brand_NPA__r.Brand_Code__c</formula>
        <label>Brand Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <description>INFOWELDERS</description>
        <formula>Promotion_Activity__r.Brand__r.Name</formula>
        <inlineHelpText>Brand is tied to the selected promotion activity.</inlineHelpText>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <formula>Account__r.Market__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Market</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Promotion_Activity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Infowelders</description>
        <label>Promotion Activity</label>
        <referenceTo>Promotion_Activity__c</referenceTo>
        <relationshipLabel>Promotions</relationshipLabel>
        <relationshipName>Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Promotion</label>
    <nameField>
        <label>Promotion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Promotion_Activity__c.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Infowelders</description>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>Promotion Activities</relationshipLabel>
        <relationshipName>Promotion_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Infowelders</description>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Infowelders</description>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Promotion Activities</relationshipLabel>
        <relationshipName>Promotion_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Promotion_Goal__c</fullName>
        <defaultValue>0</defaultValue>
        <description>PARX - Jochen Schrader - P00013: Number of Promotions each Sales Rep should do with this Promotion Activity and the selected Subgroup. Groups are calculated automatically</description>
        <inlineHelpText>Number of Promotions each Sales Rep should do with this Promotion Activity and the selected Subgroup</inlineHelpText>
        <label>Promotion Goal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Promotion Activity</label>
    <nameField>
        <label>Promotion Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promotion Activities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

B-F Backup Sandbox 30.4.12/src/objects/Promotion_Goal__c.object
<CustomObject>
    <fields>
        <fullName>Market__c</fullName>
        <formula>Promotion__r.Market__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Market</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>INFOWELDERS</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Promotion Goals</relationshipLabel>
        <relationshipName>Promotion_Goals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Promotion__c</fullName>
        <description>Infowelders</description>
        <label>Promotion</label>
        <referenceTo>Promotion__c</referenceTo>
        <relationshipLabel>Promotion Goals</relationshipLabel>
        <relationshipName>Promotion_Goals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Promotion Goal</label>
    <nameField>
        <displayFormat>PG-{YYYY}{000000}</displayFormat>
        <label>Promotion Goal#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotion Goals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

B-F Sandbox/trunk/src/classes/promotionProductSelection_Controller.cls
public with sharing class promotionProductSelection_Controller {


/* Class Name : promotionProductSelection_Controller
* Description: --
* Created By : --
* Created On : --

* Modification Log :  
* ----------------------------------------------------------------------------------------------------------------------------
* Developer       Date              Description
* ----------------------------------------------------------------------------------------------------------------------------
* VARUN           06-13-2011        Code for Product Remediation Check.
*                                   
*/ 

    
    //Product Remediation Product2 changed to Product__c
    public List<Product__c> ProdSelection {get;set;}
    public string RecordTypeValue {get;set;}
    public string bfBrandValue {get;set;}
    Public ID  MyId {get;set;}

    
    public string ProductNameTextValue {get;set;}
    /*public string ProductCodeTextValue {get;set;}      
    public string bfBrandTextValue {get;set;}
    public string DescriptionTextValue {get;set;}*/
    
    public string productID {get;set;}
    public string productName {get;set;}
        
    ID marketID;
    
    promotionProductHelperClass helper;
    Promotion__c pm;
    public string pageType {get;set;}
    public promotionProductSelection_Controller (ApexPages.StandardController controller)
    {
        this.pm = (Promotion__c)controller.getRecord();
        try{
            Promotion__c myP = [Select Name, Brand__c, Promotion_Activity__r.Brand__c, Account__r.Market__c, Recordtype.name from Promotion__c where Id =: pm.Id];
            bfBrandValue = myP.Promotion_Activity__r.Brand__c;
            marketID = myP.Account__r.Market__c;
            map<string, Schema.recordtypeinfo> maprecordtypenames = Schema.SObjectType.Promotion_Goal__c.getRecordTypeInfosByName();

            MyID = maprecordtypenames.get(myP.recordtype.name).RecordTypeid;
        }catch(exception e){}
        pageType = ApexPages.currentPage().getParameters().get('type');
        helper = new promotionProductHelperClass();         
        buildProdSelection();
    }
    public List<SelectOption> getrecordTypeList() {

        return helper.getrecordTypeList();     
    }     
    public List<SelectOption> getBFBrandsList() 
    {
        return helper.getBFBrandsList();
    }       
    public PageReference filterAction(){
        buildProdSelection();
        return null;
    }     
    public PageReference addProducts(){
        //Apexpages.addMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM, ''));

        return null;
    }           
    void buildProdSelection()
    {    
        //code modified for the Product Remediation. Custom setting is used to enable and disable custom product code.
        string myQueryString = '';
        
        //product remediation code start
            myQueryString = 'Select p.VAT__c, p.Unit_Cost__c, p.Supplier__c, p.Sort_Order__c, p.RecordTypeId, p.ProductCode__c, p.Name, p.Market__c, p.IsActive__c, p.Id, p.Family__c, p.Description__c, p.CurrencyIsoCode, p.Competes_On_Brand__c, p.Case_Multiplier__c, p.Brand__c, p.Brand__r.Name, p.Brand_Code__c From Product__c p where p.IsActive__c=true';
        //product remediation code end
        myQueryString = myQueryString + (marketID!=null?' and p.Market__c=\''+marketID+'\'':'');
        /*if(RecordTypeValue!=null && RecordTypeValue!='ALL')
        {
            myQueryString+=' and p.RecordTypeId=\''+String.escapeSingleQuotes(RecordTypeValue.trim())+'\'';
        }*/
        
        myQueryString+=' and p.RecordType.Name=\'Wet Goods\'';        
        
        
        if(bfBrandValue!=null && bfBrandValue!='ALL')
        {
            myQueryString+=' and p.Brand__c=\''+String.escapeSingleQuotes(bfBrandValue.trim())+'\'';
        }        
        if(ProductNameTextValue!=null && ProductNameTextValue!='')
        {
            myQueryString+=' and (p.Name like \'%'+String.escapeSingleQuotes(ProductNameTextValue.trim())+'%\'';
           //Product Remediation code starts
            myQueryString+=' or p.ProductCode__c like \'%'+String.escapeSingleQuotes(ProductNameTextValue.trim())+'%\'';
            myQueryString+=' or p.Brand__r.Name like \'%'+String.escapeSingleQuotes(ProductNameTextValue.trim())+'%\'';
            myQueryString+=' or p.Description__c like \'%'+String.escapeSingleQuotes(ProductNameTextValue.trim())+'%\')';            
        }
        /*if(ProductCodeTextValue!=null && ProductCodeTextValue!='')
        {
            myQueryString+=' and p.ProductCode like \'%'+String.escapeSingleQuotes(ProductCodeTextValue.trim())+'%\'';
        }    
        if(bfBrandTextValue!=null && bfBrandTextValue!='')
        {
            myQueryString+=' and p.Brand__r.Name like \'%'+String.escapeSingleQuotes(bfBrandTextValue.trim())+'%\'';
        }    
        if(DescriptionTextValue!=null && DescriptionTextValue!='')
        {
            myQueryString+=' and p.Description like \'%'+String.escapeSingleQuotes(DescriptionTextValue.trim())+'%\'';
        }     */
        myQueryString+=' and p.Brand__r.Supplier__r.Is_B_F_Brand__c = true';
        myQueryString+=' ORDER BY p.Sort_Order__c';                                  
        system.debug(myQueryString);
        ProdSelection = new List<Product__c>();
        for(Product__c productList : Database.query(myQueryString))
            {
            ProdSelection.add(productList);
            }

    }
}