B-F Sandbox Full-Backup/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used by CRM.
NPA Rollout: Used to store the Market reference.</description>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>INFOWELDERS</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Former</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Potential</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Telesales</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>INFOWELDERS</description>
        <label>Supplier</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts (As Supplier)</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

B-F Backup Sandbox 30.4.12/src/objects/Brand__c.object
<CustomObject>
    <description>Used by CRM.
NPA Rollout: Used to store Brands.</description>
    <fields>
        <fullName>Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Infowelders:Used by CRM.
NPA Rollout: Used to refer to Supplier.</description>
        <label>Supplier</label>
        <referenceTo>Supplier__c</referenceTo>
        <relationshipLabel>Brands</relationshipLabel>
        <relationshipName>Brands</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>AccountNumber__c</fullName>
        <formula>Account__r.AccountNumber</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AccountNumber</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Name__c</fullName>
        <formula>Account__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Banner_Partner__c</fullName>
        <formula>Wholesalers__r.Banner_Partner__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Banner Partner</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Date__c</fullName>
        <defaultValue>today()</defaultValue>
        <label>Order Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RecordTypeName__c</fullName>
        <formula>$RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>RecordTypeName</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Process Order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Service</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Wholesaler_Account_Name__c</fullName>
        <formula>Wholesalers__r.Wholesaler_Account_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Wholesaler Customer Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Wholesaler_Code__c</fullName>
        <description>This field is need for the trigger</description>
        <formula>Wholesalers__r.Wholesaler__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This field is need for the trigger</inlineHelpText>
        <label>Wholesaler_Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Wholesaler_Customer_Number__c</fullName>
        <description>This is the &quot;Customer&quot; number that will be sent to the Wholesaler.</description>
        <formula>Wholesalers__r.Wholesaler_Account_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This is the &quot;Customer&quot; number that will be sent to the Wholesaler.</inlineHelpText>
        <label>Wholesaler Customer Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Wholesaler_Name__c</fullName>
        <formula>Wholesalers__r.Wholesaler_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Wholesaler Name (ECC)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Wholesalers__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Wholesaler - Look Up</label>
        <referenceTo>Account_Wholesaler__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>ORD-{0}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <recordTypes>
        <fullName>New</fullName>
        <active>true</active>
        <description>New</description>
        <label>New</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Order_Item__c.object
<CustomObject>
    <fields>
        <fullName>Banner_Partner__c</fullName>
        <formula>Order__r.Banner_Partner__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Banner Partner</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BF - Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>Order_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Carton_Bonus__c</fullName>
        <inlineHelpText>Case - (Bonus)</inlineHelpText>
        <label>Carton (Bonus)</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Carton__c</fullName>
        <description>Case</description>
        <inlineHelpText>Case</inlineHelpText>
        <label>Carton</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Discount__c</fullName>
        <inlineHelpText>Create a validation rule, has to be greater than the discount or less/equal to the tolerance</inlineHelpText>
        <label>Discount - ($)</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>Order_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BF - Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>Order_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecordTypeName__c</fullName>
        <formula>$RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>RecordTypeName</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_Bonus__c</fullName>
        <inlineHelpText>Bottles - (Bonus)</inlineHelpText>
        <label>Unit (Bonus)</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit__c</fullName>
        <inlineHelpText>Bottle</inlineHelpText>
        <label>Unit</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Order Item</label>
    <nameField>
        <displayFormat>ORD_ITM-{0}</displayFormat>
        <label>Order Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <recordTypes>
        <fullName>New</fullName>
        <active>true</active>
        <description>New</description>
        <label>New</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Product__c.object
<CustomObject>
    <description>NPA Rollout: Object for storing Products used in National Promotion application.
Product Remediation : Replicated all standard product fields here.</description>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Infowelders, NPA Rollout: Used to store the related Brand</description>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipName>Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created as a part of product remediation</description>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>ProductsCustom</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <description>NPA Rollout: Stores the product code</description>
        <label>Product Unique Key</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>NPA Rollout: Used to store status of Product
0 = Active
1 = Cancelled</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <description>Created as a part of product remediation</description>
        <formula>Brand__r.Supplier__r.Name</formula>
        <label>Supplier</label>
        <type>Text</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Supplier__c.object
<CustomObject>
    <description>Used by CRM. 
NPA Rollout: Used to store Suppliers.</description>
    <fields>
        <fullName>Is_B_F_Brand__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box if this Supplier record is considered a B-F brand.</description>
        <inlineHelpText>Check this box if this Supplier record is considered a B-F brand.</inlineHelpText>
        <label>Is B-F Brand?</label>
        <type>Checkbox</type>
    </fields>
    <label>Supplier</label>
    <nameField>
        <label>Supplier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Market__c</fullName>
        <description>INFOWELDERS - These text values MUST match the Market Name records&apos; text values.
NPA Rollout: Used to store the markets a user is allocated to. Multiple values can be used separated by semi-colon.</description>
        <inlineHelpText>CRM: Market at a Country level-  such as Germany, Korea, India, Japan etc.
NPA: Market at a State level-  such as Illinois, Kentucky etc.</inlineHelpText>
        <label>Market</label>
        <picklist>
            <picklistValues>
                <fullName>ALL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Germany</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Japan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Korea</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thailand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Taiwan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>India</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canada General</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

B-F Sandbox/trunk/src/classes/OrderItem_Controller.cls
/* Class Name : OrderItem_Controller
* Description: --
* Created By : --
* Created On : --
*
* Modification Log :  
* ----------------------------------------------------------------------------------------------------------------------------
* Developer       Date              Description
* ----------------------------------------------------------------------------------------------------------------------------
* Mike Levites  06-27-2011        Code for Product Remediation Check.      
* Stuff to Do:
* 1.Dynamic Look Up for Market
* 2.Fix the Product Select Statment to include the Market Value 
* 3.Select Market from current User's market
* 4. 
* 5. 
*/ 
public with sharing class OrderItem_Controller {
	private String sortDirection = 'ASC';
	private String sortExp = 'name';
	
	public Order__c myOrder { get; set; }
	public string bfBrandValue {get;set;} 
	public string ProductNameTextValue {get;set;}
	public string ProductCodeTextValue {get;set;}      
	public string bfBrandTextValue {get;set;}
	public string DescriptionTextValue {get;set;}   
 	public List<lineItemWrapper> myOrderItems {get;set;}
	//Intial ProdSelection with Strucure <wrapper>  
    public List<productWrapper> ProdSelection {get;set;}  
    public String sortExpression {
    	get { 
    		return sortExp;
    	}
    	set {
    		if (value == sortExp) {
    			sortDirection = (sortDirection == 'ASC') ? 'DESC' : 'ASC';
    		} else {
    			sortDirection = 'ASC';
    		}
    		sortExp = value;
    	}
    }
    
	public Order_Item__c  myOrderItem;
	
	public RecordType orderItemRecordType = [SELECT Id, Name FROM RecordType WHERE SObjectType = 'Order_Item__c' AND Name = 'New'];
	
	Account a;
	id OrderId;
    Id marketID = 'a06Q0000005nz0B';
    //integer myLimit = 2000;

	//Custom Wrapper class for LineItem    
    public class lineItemWrapper {
        public Order_Item__c orderItem {get; set;}
        public Product__c prod {get; set;}
    	public boolean selected {get; set;}
    	public brand__c brand {get; set;}
   	    public integer carton { 
   	    	get { return orderItem == null || orderItem.Carton__c == null ? 0 : (integer)orderItem.Carton__c; }
   	    }
		public integer unit { 
			get { return orderItem == null || orderItem.Unit__c == null ? 0 : (integer)orderItem.Unit__c; } 
		}
		public decimal discount { 
			get { return orderItem == null || orderItem.Discount__c == null ? 0 : orderItem.Discount__c; } 
		}
		public integer bonusCarton { 
			get { return orderItem == null || orderItem.Carton_Bonus__c == null ? 0 : (integer)orderItem.Carton_Bonus__c; } 
		}
		public integer bonusUnit { 
			get { return orderItem == null || orderItem.Unit_Bonus__c == null ? 0 : (integer)orderItem.Unit_Bonus__c; } 
		}
      
      	void Init() {
			selected = false;
			orderItem = new Order_Item__c();
			prod = null;
			brand = null;
      	}
//I need to exstend this....    
		public lineItemWrapper () {
			Init();
		}
    	public lineItemWrapper (Order__c o, Order_Item__c oi, Product__c a){
    		Init();
    		prod = a;
    		brand = a.Brand__r;
    		
    		orderItem = oi;
    		if (oi == null) {
    			orderItem = new Order_Item__c();
    			orderItem.RecordType = [SELECT Id, Name FROM RecordType WHERE SObjectType = 'Order_Item__c' AND Name = 'New'][0];
    			orderItem.Order__c = o.Id;
    			orderItem.Product__c = a.Id;
    		}
    	}
    }  
	//End lineItemWrapper
	
	//Custom Wrapper class for the Product List    
    public class productWrapper {
	    public Product__c prod {get; set;}
    	public boolean selected {get; set;}
    	public integer brandQTY {get;set;}    
    	public integer planBottle {get;set;}
    	public double planRebate {get;set;}  
    	public List<lineItemWrapper> myOrderItems { get; set; } 
               
		//Tass - What is the code below doing?
    	public productWrapper(Product__c a) {
    		// This code is acting as the constructor for the wrapperP class.
            prod = a;
            selected=false;
        }
    }    
	//End productWrapper


	//Public Declaration Stuff
   	public OrderItem_Controller (ApexPages.StandardController controller) {
		List<Market__c> markets = [SELECT Id FROM Market__c WHERE Name = 'Australia'];
		if (markets != null && markets.size() > 0) {
			marketID = markets[0].Id;
		}
   		
        this.myOrder = (Order__c)controller.getRecord();
        this.myOrder = [SELECT Name, RecordTypeId, RecordTypeName__c,Account__c, Account_Name__c, AccountNumber__c, Banner_Partner__c, Contact__c, Order_Date__c, Status__c, Wholesaler_Code__c, Wholesaler_Name__c, Wholesalers__c, Wholesaler_Customer_Number__c, Wholesaler_Account_Name__c FROM Order__c WHERE Id =:myOrder.Id];
	    
	    //This Builds the intial List.
      	buildProdSelection(); 
      
      	//Building my list of items
      	buildOrderItems();
    }   
	//End of Declaration Stuff    
    
 	//For Closing the Page link back to Order Item   
    public PageReference close(){
        return new PageReference('/'+myOrder.id);
    }      
	public PageReference saveAndClose() {
		saveAction();
		return close();
	}


	//Brand & String Filters
	public List<SelectOption> getBFBrandsList() {
        List<SelectOption> optionList = new List<SelectOption>();
        // Add a null option to force the user to make a selection. //
        optionList.add(new SelectOption('ALL','ALL'));
        for(Brand__c y :[Select r.Name, r.Id From Brand__c r where Supplier__r.Is_B_F_Brand__c = true ORDER BY r.Name]) 
        {
            optionList.add(new SelectOption(y.Id,y.Name));
        }
        return optionList;
    }
	//Getting Brand List - End
 
  
	//Once Filters Come in it will then be passed to the Product Selection   
 	public PageReference filterAction() {  
        buildProdSelection();
        return null;
    }    

	//Product Selection - Used for the Product Section Part of the screen.
 	void buildProdSelection() {    
        if (ProdSelection == null) { 
        	ProdSelection = new List<productWrapper>(); 
        } else {
        	ProdSelection.clear();
        }
        
		//Product Selection String       
        string myQueryString = 'Select p.VAT__c, p.Unit_Cost__c, p.Supplier__c, p.Sort_Order__c, p.RecordType.Name, p.RecordTypeId, p.ProductCode__c, p.Name, p.Market__c, p.IsActive__c, p.Id, p.Family__c, p.Description__c, p.CurrencyIsoCode, p.Competes_On_Brand__c, p.Case_Multiplier__c, p.Brand__c, p.Brand__r.Name, p.Brand_Code__c From Product__c p ';
        myQueryString += ' WHERE p.IsActive__c=true';
//        + ' and p.Market__c= +marketID+
        myQueryString += ' AND p.Brand__r.Supplier__r.Is_B_F_Brand__c = true';
        myQueryString += (marketID != null ? ' AND p.Market__c=\''+marketID+'\'' : '');
 

        if(bfBrandValue != null && bfBrandValue != 'ALL') {
            myQueryString+=' and p.Brand__c=\'' + bfBrandValue + '\'';
        }        
        if(ProductNameTextValue != null && ProductNameTextValue != '') {
            myQueryString+=' and p.Name like \'%' + ProductNameTextValue + '%\'';
        }
        if(ProductCodeTextValue != null && ProductCodeTextValue != '') {
            myQueryString+=' and p.ProductCode__c like \'%' + ProductCodeTextValue + '%\'';
        }    
        if(bfBrandTextValue != null && bfBrandTextValue != '') {
            myQueryString+=' and p.Brand__r.Name like \'%' + bfBrandTextValue + '%\'';
        }    
        if(DescriptionTextValue != null && DescriptionTextValue != '') {
            myQueryString+=' and p.Description__c like \'%' + DescriptionTextValue + '%\'';
        }     
        
        myQueryString+=' ORDER BY p.Sort_Order__c';
        myQueryString += ',p.' + sortExpression + ' ' + sortDirection;
                        
        //system.debug(myQueryString);
        
        System.debug('queryString: ' + myQueryString);
        for(Product__c pr :Database.query(myQueryString)) {
        	ProdSelection.add( new productWrapper(pr));
        }
     
        System.debug('[orderitem_controller] prodSelection.size: ' + ProdSelection.size());
    }

	// End Product Selection String 


	public PageReference saveAction(){  
        Savepoint sp = Database.setSavepoint();     
        
		// Not Sure why they use a Try Block - Ask Shroyer
		// Answer: A try block is to catch any exceptions that may occur and cater for them without breaking the page        
        try{    
        	List<Order_Item__c> orderItems = new List<Order_Item__c>();
        	Order_Item__c item;
            for(lineItemWrapper wp : myOrderItems) {
            	System.debug('wp.product: ' + wp.orderItem.Product__c + ', carton: ' + wp.orderItem.Carton__c + ', carton(sc): ' + wp.carton);
            	if (wp.carton + wp.unit + wp.bonusCarton + wp.bonusUnit + wp.discount > 0) {
            		integer totalStock = wp.carton + wp.unit;
            		integer bonusStock = wp.bonusCarton + wp.bonusUnit;
            		if (bonusStock > 0 && (wp.orderItem.Discount__c > 0 || totalStock > 0)) {
		            	for (Order_Item__c tt: orderItems) {
        		    		System.debug('[splitting bonus stock]Order item id: ' + tt.Id);
            			}
            			
            			Order_Item__c bonusOI = wp.orderItem.clone(false, true);
						System.debug('[splitting bonus stock] bonusOI.id: ' + bonusOI.Id);
						System.debug('[splitting bonus stock] orderitem.id: ' + wp.orderItem.Id);
            			wp.orderItem.Carton_Bonus__c = 0;
            			wp.orderItem.Unit_Bonus__c = 0;
            			orderItems.add(wp.orderItem);            			

						
						bonusOI.Carton__c = 0;
						bonusOI.Unit__c = 0;
						bonusOI.Discount__c = 0;
						            			
						orderItems.add(bonusOI);            			
            		} else {
            			orderItems.add(wp.orderItem);
            		}
            	} else {
            		ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'No amounts enterred against line item ' + wp.prod.Name));
            	}
            }
            
            //ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM, 'number of items to insert: ' + orderItems.size()));
            
            if (orderItems.size() > 0) {
            	for (Order_Item__c tt: orderItems) {
            		System.debug('Order item id: ' + tt.Id);
            	}
				upsert orderItems;                   	
            }
        }catch(System.DmlException insertDmlexp){
        	Database.rollback(sp);
            for (Integer i = 0; i < insertDmlexp.getNumDml(); i++) {
            	ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, insertDmlexp.getDmlMessage(i)));
            }
        }  
        
        return null;
    }    
    
    public PageReference BuildLineItems() {
    	// Use this function only for test method as buildOrderItems is private. Will remove after test method completes
    	buildOrderItems();
    	return null;
    }

	//Get Order Items
	void buildOrderItems() {
	
	 	if (myOrderItems == null) {
	 		myOrderItems = new List<lineItemWrapper>();
	 	}
	 	
		//Shroyer What does this do?	 
	 	//Set<ID> myProducts = new Set<ID>();
		//Custom Structure for myOrderItems & ID Correct?	 
		//Map<ID,Order_Item__c> orderItems = new Map<ID,Order_Item__c>();
		// This SET AND MAP lists are not required, as we will build the line item on the fly.
		for(Order_Item__c oi: [SELECT p.Product__c, p.Carton__c, p.Unit__c, p.Discount__c, p.Carton_Bonus__c, p.Unit_Bonus__c, p.RecordTypeId, p.RecordTypeName__c FROM Order_Item__c p WHERE p.Order__c =: this.myOrder.Id]) {
			List<Product__c> p = [SELECT p.VAT__c, p.Unit_Cost__c, p.Supplier__c, p.Sort_Order__c, p.RecordType.Name, p.RecordTypeId, p.ProductCode__c, p.Name, p.Market__c, p.IsActive__c, p.Id, p.Family__c, p.Description__c, p.CurrencyIsoCode, p.Competes_On_Brand__c, p.Case_Multiplier__c, p.Brand__c, p.Brand__r.Name, p.Brand_Code__c FROM Product__c p WHERE p.Id =:oi.Product__c];
			if (p != null && p.size() > 0) {
				this.myOrderItems.add(new lineItemWrapper(this.myOrder, oi, p[0]));				
			}
		}
	}


	public PageReference removeOrderItems(){
		if (this.myOrderItems == null) { return null; }
		
		integer numberOfItems = this.myOrderItems.size();

		try {
			for(integer i = numberOfItems - 1; i >= 0; i--) {
				lineItemWrapper wr = this.myOrderItems.get(i);
				if (wr.selected == true && wr.orderItem.RecordTypeName__c == 'New') {
					if (wr.orderItem.Id != null) {
						delete wr.orderItem;
					}
						
					this.myOrderItems.remove(i);					
				}
			}  
			
		} catch(System.DMLException ex) {
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, ex.getMessage()));
		}		

        return null;
    }        

    public PageReference addProducts(){
        //Apexpages.addMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM, ''));
        
		//This Fixed my Error      
     	
     	ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM, 'number of products already selected: ' + myOrderItems.size()));
    	for(productWrapper wp : ProdSelection) {
        	        	
    		if(wp.selected == true) {
    			wp.selected = false;
        		myOrderItems.add(new lineItemWrapper(this.myOrder, null, wp.prod));
        	}
    	}

        return null;
    }

	// Validation Routines
	/*
	public void validateBonusStock(Order_Item__c oi) {
		if (oi == null) { return; }
		if (oi.Discount__c == 0) { return; }
		
		if (oi.Carton_Bonus__c + oi.Unit_Bonus__c > 0) {
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'You cannot enter a Discount with Bonus Stock'));
			oi.Discount__c = 0;
		}
	} 
	*/ 
}