B-F Sandbox Full-Backup/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used by CRM.
NPA Rollout: Used to store the Market reference.</description>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>INFOWELDERS</description>
        <label>Supplier</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts (As Supplier)</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

B-F Backup Sandbox 30.4.12/src/objects/Brand__c.object
<CustomObject>
    <description>Used by CRM.
NPA Rollout: Used to store Brands.</description>
    <fields>
        <fullName>Spirit_Type__c</fullName>
        <description>Infowelders</description>
        <label>Spirit Type</label>
        <picklist>
            <picklistValues>
                <fullName>Bourbon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canadian / Blend</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scotch / Irish</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Liquers / Cordials</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rum / Gin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tequila</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vodka</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wine</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Infowelders:Used by CRM.
NPA Rollout: Used to refer to Supplier.</description>
        <label>Supplier</label>
        <referenceTo>Supplier__c</referenceTo>
        <relationshipLabel>Brands</relationshipLabel>
        <relationshipName>Brands</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Market__c.object
<CustomObject>
    <description>Used by CRM.
NPA Rollout: Used to store Markets at State Level.</description>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Product__c.object
<CustomObject>
    <description>NPA Rollout: Object for storing Products used in National Promotion application.
Product Remediation : Replicated all standard product fields here.</description>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Infowelders, NPA Rollout: Used to store the related Brand</description>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipName>Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Competes_On_Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>INFOWELDERS - Brand that a competitor product competes against.</description>
        <label>Competes On (Brand)</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipName>ProductCompete</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created as a part of product remediation</description>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>ProductsCustom</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductCode__c</fullName>
        <description>NPA Rollout: Used to store the product code of the POS item.</description>
        <externalId>true</externalId>
        <label>Product Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <description>NPA Rollout: Stores the product code</description>
        <label>Product Unique Key</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <description>Created as a part of product remediation</description>
        <formula>Brand__r.Supplier__r.Name</formula>
        <label>Supplier</label>
        <type>Text</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Promotion__c.object
<CustomObject>
    <description>Used by CRM.
NPA Rollout: Used to store Promotions.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Infowelders</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Promotions</relationshipLabel>
        <relationshipName>Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brand_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Infowelders</description>
        <label>Brand Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Promotions1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <description>INFOWELDERS</description>
        <formula>Promotion_Activity__r.Brand__r.Name</formula>
        <inlineHelpText>Brand is tied to the selected promotion activity.</inlineHelpText>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Finance_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Infowelders</description>
        <label>Finance Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Promotions2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <formula>Account__r.Market__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Market</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>INFOWELDERS</description>
        <label>Sales Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Promotion</label>
    <nameField>
        <label>Promotion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <recordTypes>
        <fullName>Agreement</fullName>
        <active>true</active>
        <label>Agreement</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

B-F Backup Sandbox 30.4.12/src/objects/Promotion_Material_Item__c.object
<CustomObject>
    <description>Used by CRM.
NPA Rollout: Used to store products added to Promotions (Promotion line items).</description>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>Product_Custom__r.Brand__r.Name</formula>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Custom__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>NPA Rollout: Used to store the related Product. /* API name need to be changed to Product__c after Product remediation*/</description>
        <label>Product Name</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Promotion Material Items</relationshipLabel>
        <relationshipName>Promotion_Material_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Infowelders</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Promotion Material Items</relationshipLabel>
        <relationshipName>Promotion_Material_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Promotion__c</fullName>
        <description>Infowelders: Used by CRM.
		NPA Rollout: Used to refer to Promotion.</description>
        <label>Promotion</label>
        <referenceTo>Promotion__c</referenceTo>
        <relationshipLabel>Promotion Material Items</relationshipLabel>
        <relationshipName>Promotion_Material_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Promotion Material Item</label>
    <nameField>
        <displayFormat>PMI-{YYYY}{00000}</displayFormat>
        <label>Promotion Material Item#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotion Material Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Supplier__c.object
<CustomObject>
    <description>Used by CRM. 
NPA Rollout: Used to store Suppliers.</description>
    <fields>
        <fullName>Is_B_F_Brand__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box if this Supplier record is considered a B-F brand.</description>
        <inlineHelpText>Check this box if this Supplier record is considered a B-F brand.</inlineHelpText>
        <label>Is B-F Brand?</label>
        <type>Checkbox</type>
    </fields>
    <label>Supplier</label>
    <nameField>
        <label>Supplier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Brand_Manager__c</fullName>
        <description>INFOWELDERS</description>
        <label>Brand Manager</label>
        <relationshipName>Users2</relationshipName>
        <restrictedAdminField>false</restrictedAdminField>
        <type>Hierarchy</type>
    </fields>
    <fields>
        <fullName>Finance_Manager__c</fullName>
        <description>INFOWELDERS</description>
        <label>Finance Manager</label>
        <relationshipName>Users1</relationshipName>
        <restrictedAdminField>false</restrictedAdminField>
        <type>Hierarchy</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <description>INFOWELDERS - These text values MUST match the Market Name records&apos; text values.
NPA Rollout: Used to store the markets a user is allocated to. Multiple values can be used separated by semi-colon.</description>
        <inlineHelpText>CRM: Market at a Country level-  such as Germany, Korea, India, Japan etc.
NPA: Market at a State level-  such as Illinois, Kentucky etc.</inlineHelpText>
        <label>Market</label>
        <picklist>
            <picklistValues>
                <fullName>ALL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Germany</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Japan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Korea</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thailand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Taiwan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>India</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canada General</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sales_Manager__c</fullName>
        <description>INFOWELDERS</description>
        <label>Sales Manager</label>
        <relationshipName>Users</relationshipName>
        <restrictedAdminField>false</restrictedAdminField>
        <type>Hierarchy</type>
    </fields>
</CustomObject>

B-F Sandbox/trunk/src/classes/Test_promotionMaterialItem_Controller.cls
@isTest
private class Test_promotionMaterialItem_Controller {

      //Assume that products and Brands are already setup.
    static testMethod void promotionMaterialItem_Controller_Coverage() {
        
  //....6/15 Levites Helper Class has User data
        INFW_TestHelper helper = new INFW_TestHelper();
        User u1 = helper.createUser();
        u1.Sales_Manager__c=userinfo.getUserId();
        u1.Finance_Manager__c=userinfo.getUserId(); 
        u1.Brand_Manager__c=userinfo.getUserId();
        Profile []p1 = [select id from Profile where Name = 'System Administrator' LIMIT 1];        
        u1.ProfileID = p1[0].id;      
        insert u1;
//....6/15 End Levites 

// Test Data for Market
        Market__c m = new Market__c();
        m.Name = 'Test Market'; 
        insert m;
 
// Test Data for Suppiler            
        Supplier__c s = new Supplier__c();
        s.Name='BF';
        s.Is_B_F_Brand__c=true; 
        insert s;

// Test Data for a New Supplier            
        Supplier__c s1 = new Supplier__c();
        s1.Name='myComp';
        s1.Is_B_F_Brand__c=false; 
        insert s1;
        
// Test Data for "BF" Brand                        
        Brand__c b = new Brand__c();
        b.Supplier__c=s.id;
        b.Spirit_Type__c='Bourbon'; 
        b.Name='John Daniels';
        insert b;
            
// Test Data for "Other" Brand
        Brand__c b1 = new Brand__c();
        b1.Supplier__c=s1.id;
        b1.Spirit_Type__c='Bourbon'; 
        b1.Name='Bob Beam';
        insert b1;    
                  
// SOQL Query for Record Type Data       
        RecordType r = [Select r.Name, r.Id From RecordType r where  r.Name = 'Wet Goods' and SobjectType = 'Product__c'];
   
// Creating "Product" List object           
        List<Product__c> pList = new List<Product__c>();
            
// Purpose of the For Loop is to create 10 Dummy BF Material's for Test Data         
        for(Integer x = 0; x<10; x++) {
            Product__c p = new Product__c();
            p.Name = 'myProduct'+x;
            //p.Supplier__c = s.id;
            p.IsActive__c=true;
            p.RecordTypeId = r.Id;
            p.ProductCode__c = 'myProduct'+x;
            p.Market__c = m.id; 
            p.Competes_On_Brand__c = b.id; 
            p.Brand__c = b1.id;
            pList.add(p);
        }
            
// Purpose of the For Loop is to create 10 Dummy Non-BF Material's for Test Data              
        for(Integer x = 0; x<10; x++)   {
            Product__c p = new Product__c();
            p.Name = 'myCompProduct'+x;
            //p.Supplier__c = s1.id;
            p.IsActive__c=true;
            p.RecordTypeId = r.Id;
            p.ProductCode__c = 'myCompProduct'+x;
            p.Market__c = m.id; 
            p.Competes_On_Brand__c = b1.id; 
            p.Brand__c = b.id;
            pList.add(p);
        }           
        insert pList;
            
 // New Account Object        
        Account a = new Account();     
        
// Running as the created Test User             
        system.runas(u1)  {   
            
// Account Creation             
            a.Name = 'Test Account';
            a.Market__c = m.Id;
            insert a;
            
// Creating Contact            
            Contact c = new Contact();
            c.AccountId = a.Id;
            c.FirstName = 'Info';
            c.LastName = 'Welders';
            insert c;
           
            recordtype[] rtype = [Select Id From RecordType where Name = 'Sales Promotion' and SobjectType = 'Promotion__c'];
   
 // Creating Promotion           
            Promotion__c prom = new Promotion__c();
            prom.Name = 'test123';
            prom.Account__c = a.id;
            prom.RecordTypeid = rtype[0].id;
            insert prom;

            ApexPages.currentPage().getParameters().put('Id', prom.Id);     
            test.startTest();
                promotionMaterialItem_Controller constructor = new promotionMaterialItem_Controller();        
                constructor.myLimit = 100; 
    
                List<SelectOption> myRecordTypeList = constructor.getrecordTypeList();
                List<SelectOption> myBrandsList = constructor.getBFBrandsList();
                Promotion_Material_Item__c PMI = new Promotion_Material_Item__c(Promotion__c = prom.Id, Product_Custom__c = pList.get(0).Id);
                insert PMI;

                promotionMaterialItem_Controller.buildProdSelection2('Jack', 'ALL', 'ALL', null);
                list<promotionMaterialItem_Controller.wrapperRemote> NewProducts = new list<promotionMaterialItem_Controller.wrapperRemote>();
                promotionMaterialItem_Controller.wrapperRemote NewProduct = new promotionMaterialItem_Controller.wrapperRemote();
                NewProduct.productid = pList.get(0).Id;
                NewProduct.promoid = PMI.Id;
                NewProducts.add(NewProduct);
                promotionMaterialItem_Controller.AddNewProduct(NewProducts, 'Agreement', prom.Id);
                promotionMaterialItem_Controller.RemoveLine(PMI.Id);
            test.stopTest();
             
        }     
    }
}