B-F Sandbox Full-Backup/src/objects/Account_Wholesaler__c.object
<CustomObject>
    <description>Wholesales Junction Object</description>
    <fields>
        <fullName>Account_Owner_ID__c</fullName>
        <formula>Account__r.OwnerId</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Owner ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Banner_Partner__c</fullName>
        <label>Banner Partner</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Wholesaler__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Wholesaler</label>
        <referenceTo>Wholesaler__c</referenceTo>
        <relationshipName>Wholesaler</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Wholesaler</label>
    <nameField>
        <displayFormat>WHSL-{0}</displayFormat>
        <label>Account Wholesaler</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Wholesalers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Banner_Group_Wholesaler_Junction__c.object
<CustomObject>
    <fields>
        <fullName>Banner_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Banner Group</label>
        <referenceTo>Banner_Groups__c</referenceTo>
        <relationshipLabel>Banner Group Wholesalers Junction</relationshipLabel>
        <relationshipName>Banner_Group_Wholesalers_Junction</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wholesaler__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Wholesaler</label>
        <referenceTo>Wholesaler__c</referenceTo>
        <relationshipLabel>Banner Group Wholesalers Junction</relationshipLabel>
        <relationshipName>Banner_Group_Wholesalers_Junction</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Banner Group Wholesaler Junction</label>
    <nameField>
        <label>Banner Group Wholesaler Junction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Banner Group Wholesalers Junction</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Wholesaler__c.object
<CustomObject>
    <description>Australia Wholesaler Object</description>
    <label>Wholesaler</label>
    <nameField>
        <label>Wholesaler</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wholesalers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/classes/Build_Rep_WholesalerBannerGroup_Index.cls
public with sharing class Build_Rep_WholesalerBannerGroup_Index {
	public void BuildIndex(string repUserName) {
		List<Banner_Group_Wholesaler_Junction__c> bwList = [SELECT Id FROM Banner_Group_Wholesaler_Junction__c];
		delete bwList;
		
		string soql = 'SELECT Id, Wholesaler__c, Banner_Partner__c, Account_Owner_Id__c, OwnerId FROM Account_Wholesaler__c ';
		if (repUserName != null && repUserName.length() > 0) {
			List<User> users = [SELECT Id FROM User WHERE UserName =:repUserName];
			if (users != null && users.size() > 0) {
				soql += ' WHERE Account_Owner_Id = \'' + users[0].Id + '\'';				
			}
		}
		
		soql += ' ORDER BY OwnerId';
		List<Account_Wholesaler__c> items = Database.query(soql);

		Set<String> combinations = null;		
		List<Banner_Group_Wholesaler_Junction__c> banList = new List<Banner_Group_Wholesaler_Junction__c>();
		Map<Id, Set<String>> uniqueKeys = new Map<Id, Set<String>>();		
		String uniqueKey = '';
		boolean keyFound = false;
		
		for(Account_Wholesaler__c aw: items) {
			uniqueKey = aw.Wholesaler__c + '-' + aw.Banner_Partner__c;
			combinations = uniqueKeys.get(aw.Account_Owner_Id__c);
			if (combinations == null) { combinations = new Set<String>(); }
			if (!combinations.contains(uniqueKey)) {
				combinations.add(uniqueKey);
				uniqueKeys.put(aw.Account_Owner_Id__c, combinations);
				
				Banner_Group_Wholesaler_Junction__c iObj = new Banner_Group_Wholesaler_Junction__c();
				//iObj.Banner_Group__c = aw.Banner_Partner__c;
				iObj.Wholesaler__c = aw.Wholesaler__c; 
				if (aw.Account_Owner_Id__c != null && aw.Account_Owner_Id__c.length() > 0) {
					iObj.OwnerId = aw.Account_Owner_Id__c;					
				} else {
					iObj.OwnerId = aw.OwnerId;
				}
				banList.add(iObj);						
			}
		}
		
		if (banList.size() > 0) {
			insert banList;
		}
	}
}