B-F Sandbox Full-Backup/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Last_Visit_Date__c</fullName>
        <description>The date that the account was last visited.</description>
        <label>Last Visit Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Outlet_Visit__c.object
<CustomObject>
    <fields>
        <fullName>Last_Visit_Date__c</fullName>
        <description>P00001 - Created by PARX to improve reporting on Last Visits</description>
        <formula>today()</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Data is Today if Visit is last visit otherwise Visit Date. This allows Last Visits of Accounts visited long ago to appear in Last Visit reports. This is useful to compare the same set of accounts again and again.</inlineHelpText>
        <label>Last Visit Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Time_Tracking__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>PARX - Jochen Schrader: Needed for a weekly report about the number of visits done by a sales rep and his possible (maximum) number of visits that can be calculated by his timetracking</description>
        <label>Time Tracking</label>
        <referenceTo>Time_Tracking__c</referenceTo>
        <relationshipLabel>Outlet Visits</relationshipLabel>
        <relationshipName>Outlet_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Outlet Visit</label>
    <nameField>
        <displayFormat>OV-{00000}</displayFormat>
        <label>Outlet Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outlet Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Time_Tracking__c.object
<CustomObject>
    <description>PARX - Jochen Schrader: P00002 Germany needs to track the times for their sales reps easily to compare this to the sums of the actual times.</description>
    <fields>
        <fullName>Number_of_possible_Visits__c</fullName>
        <description>Number of maximum or possible visits for this sales rep</description>
        <formula>Working_Days_left__c *8</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Number of possible Visits</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Staff_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>PARX - Jochen Schrader: P00002 Account that is related to Staff Member</description>
        <inlineHelpText>Account that is related to Staff Member</inlineHelpText>
        <label>Staff Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Time Tracking</relationshipLabel>
        <relationshipName>Time_Tracking</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <defaultValue>Date(Year(Today()),Month(Today()),1 )</defaultValue>
        <description>PARX - Jochen Schrader: P00002 The Start Date you are working for B-F this month.</description>
        <inlineHelpText>The Start Date you are working for B-F this month.</inlineHelpText>
        <label>StartDate</label>
        <type>Date</type>
    </fields>
    <label>Time Tracking</label>
    <nameField>
        <displayFormat>T{YYYY}{MM}-{00}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Tracking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

B-F Sandbox/trunk/src/classes/MandatoryVisitController.cls
public with sharing class MandatoryVisitController {
	
    private final ID userID;
	public Outlet_Visit__c record {get;set;}
	
	Set<ID> accountIDs {get;set;}
	list<Time_Tracking__c> timecards {get;set;} 
	public Integer outletVisitAmount {get;set;}
	
	public Double maxDays {get;set;}
	public Date startingDate {get;set;}
	public Date endingDate {get;set;}

	
	public MandatoryVisitController() {
		maxDays = 0;
		Integer actualMonth = Date.today().month();
		Integer actualYear = Date.today().year();
		
		startingDate = Date.newInstance(actualYear, actualMonth, 1);
		endingDate = Date.newInstance(actualYear, actualMonth+1, 1).addDays(-1);

		userID = System.Userinfo.getUserId();

		// a user should only be able to see his outlet visits and the visits of his fellows in the role hierachy below him!
		list<Outlet_Visit__c> ovlist=new list<Outlet_Visit__c>([Select Id, OwnerId From Outlet_Visit__c Where Last_Visit_Date__c >=: startingDate AND Last_Visit_Date__c <=: endingDate]);
		outletVisitAmount = ovlist.size();
		
		set<Id> ownerids = new set<Id>();
		for (Outlet_Visit__c ov: ovlist) {
			if (!ownerids.contains(ov.OwnerId)) ownerids.add(ov.OwnerId);
		}
		
		// hope to get the right time tracking informations with this
		for(Time_Tracking__c tt : [Select Number_of_possible_Visits__c From Time_Tracking__c Where Staff_Account__r.OwnerId IN :ownerids AND StartDate__c >=: startingDate AND StartDate__c <=: endingDate]){
			maxDays += tt.Number_of_possible_Visits__c;
		} 
	}
	
	
	public static testMethod void MainTest() {
    	MandatoryVisitController ctrl = new MandatoryVisitController();
    }
}