B-F Sandbox Full-Backup/src/objects/Account_Brand__c.object
<CustomObject>
    <description>INFOWELDERS - Brands Related to this Account</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>INFOWELDERS</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Brands</relationshipLabel>
        <relationshipName>Account_Brands</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>INFOWELDERS</description>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>Account Brands</relationshipLabel>
        <relationshipName>Account_Brands</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Depletion_Actuals__c</fullName>
        <description>INFOWELDERS - Depletion actuals for this brand at this outlet for this fiscal year as calculated based on depletion records</description>
        <inlineHelpText>Depletion actuals for this brand at this outlet for this fiscal year</inlineHelpText>
        <label>Depletion Actuals</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FY_End__c</fullName>
        <description>INFOWELDERS - The end date of the Fiscal Year for this Account Brand Record</description>
        <inlineHelpText>The end date of the Fiscal Year for this Account Brand Record</inlineHelpText>
        <label>FY End</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FY_Start__c</fullName>
        <description>INFOWELDERS - The start date of the Fiscal Year for this Account Brand Record</description>
        <inlineHelpText>The start date of the Fiscal Year for this Account Brand Record</inlineHelpText>
        <label>FY Start</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Fiscal_Year__c</fullName>
        <description>INFOWELDERS</description>
        <formula>TEXT( YEAR( FY_End__c ))</formula>
        <label>Fiscal Year</label>
        <type>Text</type>
    </fields>
    <label>Account Brand</label>
    <nameField>
        <displayFormat>AB-{0000000}</displayFormat>
        <label>Account Brands Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Brands</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

B-F Backup Sandbox 30.4.12/src/objects/Brand__c.object
<CustomObject>
    <description>Used by CRM.
NPA Rollout: Used to store Brands.</description>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

B-F Backup Sandbox 30.4.12/src/objects/Depletion__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Infowelders</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Depletions</relationshipLabel>
        <relationshipName>Depletions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Bottles__c</fullName>
        <description>Infowelders</description>
        <label>Bottles</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>Custom_Product__r.Brand__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Custom_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created for Product Remediation process</description>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Depletions</relationshipLabel>
        <relationshipName>Depletions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Month_Of_Date__c</fullName>
        <description>Infowelders</description>
        <label>Month Of Date</label>
        <type>Date</type>
    </fields>
    <label>Depletion</label>
    <nameField>
        <displayFormat>DEP-{YYYY}{000000}</displayFormat>
        <label>Depletion #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Depletions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Product__c.object
<CustomObject>
    <description>NPA Rollout: Object for storing Products used in National Promotion application.
Product Remediation : Replicated all standard product fields here.</description>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Infowelders, NPA Rollout: Used to store the related Brand</description>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipName>Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/classes/updateAccountBrandAsynch.cls
public without sharing class updateAccountBrandAsynch {

	@future (callout=true) 
	public static void updateAccountBrandAsynch(Set<ID> myIDS)
	{
		updateAccountBrand(myIDS);
	}
	public static void updateAccountBrandSynch(Set<ID> myIDS)
	{
		updateAccountBrand(myIDS);
	}	

	public static void updateAccountBrand(Set<ID> myIDS)
	{
		Map<string,Map<string,Account_Brand__c>> myABs = new Map<string,Map<string,Account_Brand__c>>();
		List<Account_Brand__c> myUpdates = new List<Account_Brand__c>();
		for(Account_Brand__c a : [Select a.Fiscal_Year__c, a.FY_Start__c, a.FY_End__c, a.Depletion_Actuals__c, a.Brand__c, a.Account__c From Account_Brand__c a where a.Account__c in: myIDS order by a.FY_Start__c])
		{
            system.debug(a);
            if(a.FY_Start__c!=null && a.FY_End__c!=null)
            {
	            a.Depletion_Actuals__c=0;
	            Map<string,Account_Brand__c> temp = myABs.get(a.Account__c+'~'+a.Brand__c);
	            if(temp==null)
	            {
	                temp = new Map<string,Account_Brand__c>(); 
	            }
	            temp.put(a.FY_Start__c.format()+'~'+a.FY_End__c.format(),a);
	            myABs.put(a.Account__c+'~'+a.Brand__c,temp);	
            }		
		}
    	List<sObject> Totals;	
    	//code updated for product remediation added custom setting to enable and disable custom product code.
    	
    	 	Totals = [Select d.Account__c Account, d.Custom_Product__r.Brand__c Brand, d.Month_Of_Date__c Month, SUM(d.Bottles__c) Amount From Depletion__c d where d.Account__c in: myIDS GROUP BY CUBE(d.Account__c, d.Custom_Product__r.Brand__c, d.Month_Of_Date__c) order by d.Month_Of_Date__c];
        for(sObject y : Totals)
        {               
            system.debug(y);
            if(
                ((string)y.get('Account')!=null && (string)y.get('Brand')!=null && (date)y.get('Month')!=null ) //need distinct list of months 
            )
            {               
                Map<string,Account_Brand__c> temp = myABs.get((string)y.get('Account')+'~'+(string)y.get('Brand'));
                if(temp==null)
                {
                    //do NOTHING 
                    continue;
                }
                //loop thru the keys and find the matching date range
                boolean foundFlag=false;
                for(string z : temp.keyset())
                {
                	string[] myDates = z.split('~');
                	if((date)y.get('Month')>=date.parse(myDates[0]) && (date)y.get('Month')<=date.parse(myDates[1]))
                	{ 
                		Account_Brand__c myVal = temp.get(z);
                		system.debug(myVal);
                		myVal.Depletion_Actuals__c = myVal.Depletion_Actuals__c+(decimal)y.get('Amount');
                		temp.put(z,myVal);
                		myABs.put((string)y.get('Account')+'~'+(string)y.get('Brand'),temp);
                		foundFlag=true;
                		break;
                	}
                }          
            }   
		} 
        for(Map<string,Account_Brand__c> t :myABs.values() )
        {
        	myUpdates.addall(t.values());
        }
    	update myUpdates;
    }

}