B-F Sandbox Full-Backup/src/objects/Configuration_to_Visit__c.object
<CustomObject>
    <description>Test object to show a way to report on visits</description>
    <fields>
        <fullName>Outlet_Visit_Item__c</fullName>
        <label>Outlet Visit Item</label>
        <referenceTo>Outlet_Visit_Item__c</referenceTo>
        <relationshipLabel>Configuration to Visits</relationshipLabel>
        <relationshipName>Configuration_to_Visits</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Outlet_Visit__c</fullName>
        <formula>HYPERLINK(&quot;/&quot;&amp; Outlet_Visit_Item__r.Outlet_Visit__r.Id , Outlet_Visit_Item__r.Outlet_Visit__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Outlet Visit</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Visit_Report_Configuration__c</fullName>
        <label>Visit Report Configuration</label>
        <referenceTo>Visit_Report_Configuration__c</referenceTo>
        <relationshipLabel>Configuration to Visits</relationshipLabel>
        <relationshipName>Configuration_to_Visits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Configuration to Visit</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Configuration to Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Market__c.object
<CustomObject>
    <description>Used by CRM.
NPA Rollout: Used to store Markets at State Level.</description>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Outlet_Visit__c.object
<CustomObject>
    <fields>
        <fullName>Visit_Date__c</fullName>
        <label>Visit Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Outlet Visit</label>
    <nameField>
        <displayFormat>OV-{00000}</displayFormat>
        <label>Outlet Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outlet Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

B-F Backup Sandbox 30.4.12/src/objects/Outlet_Visit_Item__c.object
<CustomObject>
    <fields>
        <fullName>Channel__c</fullName>
        <formula>TEXT(Outlet_Visit__r.Venue__r.Channel__c)</formula>
        <label>Channel</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Outlet_Visit__c</fullName>
        <label>Outlet Visit</label>
        <referenceTo>Outlet_Visit__c</referenceTo>
        <relationshipLabel>Outlet Visit Items</relationshipLabel>
        <relationshipName>Outlet_Visit_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Outlet Visit Item</label>
    <nameField>
        <label>Outlet Visit Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Outlet Visit Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Visit_Report_Configuration__c.object
<CustomObject>
    <description>Test Object to show a possible way to report over visits</description>
    <fields>
        <fullName>Channel__c</fullName>
        <inlineHelpText>With &quot;On&quot; only the &quot;Group&quot; Picklist will be taken into account. With &quot;Off&quot; only the Outlet Class will be used. With &quot;Both&quot; you can choose both of them.
&quot;Wholeseller&quot; will only select Visits of &quot;Wholeseller&quot; Accounts ignoring Group and Class.</inlineHelpText>
        <label>Channel</label>
        <picklist>
            <picklistValues>
                <fullName>On</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Both</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wholesaler</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <label>Group</label>
        <picklist>
            <picklistValues>
                <fullName>Convenience Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Department Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duty Free</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hyper Market</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Liquor Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supermarket</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sub Wholesalers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wholesalers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bar / Pub</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disco / Hip Hop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hotel / Resort</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Karaoke</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Night Club / Salon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Restaurant / Cafe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sports / Darts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drink</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lodging</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Slow Food</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Small Food / Bistro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Life</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dance Club</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Room Salon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Government</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Independent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Independent Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National Chain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Private</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regional Chain</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Visit Report Configurations</relationshipLabel>
        <relationshipName>Visit_Report_Configurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Period1_From__c</fullName>
        <label>Period1_From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Period1_To__c</fullName>
        <label>Period1 To</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Period2_From__c</fullName>
        <label>Period2_From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Period2_To__c</fullName>
        <label>Period2_To</label>
        <type>Date</type>
    </fields>
    <label>Visit Report Configuration</label>
    <nameField>
        <label>Visit_Report_Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visit Report Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

B-F Sandbox/trunk/src/classes/VisitReportConfigurationHandler.cls
global class VisitReportConfigurationHandler {

    static webservice string collectVisitItems(String visitreportconfigurationid) {
        string msg='';
        Visit_Report_Configuration__c vrc=[SELECT Id, Market__c, Channel__c, Group__c, Period1_From__c, Period1_To__c, Period2_From__c, Period2_To__c FROM Visit_Report_Configuration__c WHERE Id=:visitreportconfigurationid];
        delete [select id from configuration_to_visit__c WHERE Visit_Report_Configuration__c=:vrc.id];
        List<Configuration_to_Visit__c> ctovlist = new List<Configuration_To_Visit__c>();
        for (Outlet_Visit_Item__c ovi:[SELECT Id FROM Outlet_Visit_Item__c WHERE 
                        //Channel__c=:vrc.Channel__c AND Outlet_Visit__r.Market__c=:vrc.Market__C ANd
                (
                    (Outlet_Visit__r.Visit_Date__c>=:vrc.Period1_From__c AND Outlet_Visit__r.Visit_Date__c<=:vrc.Period1_To__c)
                    OR
                    (Outlet_Visit__r.Visit_Date__c>=:vrc.Period2_From__c AND Outlet_Visit__r.Visit_Date__c<=:vrc.Period2_To__c)
                )]) {
            Configuration_to_Visit__c ctov = new Configuration_to_Visit__c();
            ctov.Visit_Report_Configuration__c=vrc.id;
            ctov.Outlet_Visit_Item__c=ovi.id;
            ctovlist.add(ctov);
        }
        insert ctovlist;
        return msg;
    }
}