B-F Sandbox Full-Backup/src/objects/Internal_Order__c.object
<CustomObject>
    <description>NPA Rollout: Object for storing Internal Orders</description>
    <label>Internal Order</label>
    <nameField>
        <label>Internal Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Internal Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Promotion__c.object
<CustomObject>
    <description>Used by CRM.
NPA Rollout: Used to store Promotions.</description>
    <fields>
        <fullName>Brand_NPA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>NPA Rollout: Used to refer to the brand.</description>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>Promotions</relationshipLabel>
        <relationshipName>Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fiscal_Year__c</fullName>
        <description>NPA Rollout: Stores the Fiscal Year. Year of ( current date + 8 months) will give the fiscal year</description>
        <formula>TEXT( IF(( MONTH( Promotion_Start_Date__c  ) + 8   &lt;= 12 ), YEAR(Promotion_Start_Date__c ), YEAR(Promotion_Start_Date__c) + 1))</formula>
        <label>Fiscal Year</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Freeze_Date__c</fullName>
        <description>NPA Rollout: Stores the Freeze Date for the promotion</description>
        <label>Freeze Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>GTM_Channel_Code__c</fullName>
        <description>NPA Rollout: Stores the GTM Channel Code for the GTM Channel selected on the Promotion</description>
        <formula>LEFT( TEXT(GTM_Channel_Description__c) , (FIND(&apos;-&apos;,  TEXT( GTM_Channel_Description__c )) - 2))</formula>
        <label>GTM Channel Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GTM_Channel_Description__c</fullName>
        <description>NPA Rollout: Stores the GTM Channel</description>
        <label>GTM Channel</label>
        <picklist>
            <controllingField>Promotion_Premise__c</controllingField>
            <picklistValues>
                <fullName>10 - Off-Wholesale Club</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21 - Off-Superstore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22 - Off-Conventional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24 - Off-Wine Specialty</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>25 - Off-Beer Specialty</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30 - Off-Drug</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40 - Off-Cigarette Outlet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>51 - Off-Limited/Assrtmnt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>52 - Off-Natural/Gourmet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>53 - Off-Warehouse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>54 - Off-Superette</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>55 - Off-Supermarket</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>56 - Off-Supercenter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>60 - Off-Category Killer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>70 - Off-Convenience</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>80 - Off-Mass Merch.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>90 - Off-Extended Master</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>501 - On-Fine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>502 - On-Casual Dining</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>503 - On-Theme Restaurant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>511 - On-Neighborhood</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>512 - On-Casual Nightclub</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>513 - On-Sports Bar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>514 - On-Prem Nightclub</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>515 - On-Adult Ent.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>516 - On-Irish</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>517 - On-Premium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>518 - On-Country Western</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>520 - On-Lodging</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>530 - On-Recreation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IO_Fiscal_Tertile__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>NPA Rollout: Stores the Internal Order - Fiscal Year - Tertile combination for the Promotion</description>
        <label>IO Fiscal Tertile</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Internal_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>NPA Rollout: Stores the related Internal Order</description>
        <label>Internal Order</label>
        <referenceTo>Internal_Order__c</referenceTo>
        <relationshipLabel>Promotions</relationshipLabel>
        <relationshipName>Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mark_for_Delete__c</fullName>
        <defaultValue>false</defaultValue>
        <description>NPA Rollout: Used to mark promotions for deletion</description>
        <label>Mark for Deletion</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Premise_Indicator_Code__c</fullName>
        <description>NPA Rollout: Used to store the code corresponding to the premise selected on the promotion, for integration with SAP.</description>
        <label>Premise Indicator Code</label>
        <picklist>
            <controllingField>Promotion_Premise__c</controllingField>
            <picklistValues>
                <fullName>B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>O</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>F</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>M</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>T</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Promotion_End_Date__c</fullName>
        <description>INFOWELDERS: Used by CRM.
NPA Rollout: Used to store the promotion end date.</description>
        <label>Promotion End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Promotion_Number__c</fullName>
        <description>INFOWELDERS</description>
        <displayFormat>P-{YYYY}{00000}</displayFormat>
        <label>Promotion Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Promotion_Premise__c</fullName>
        <description>NPA Rollout: Stores the Premise for the Promotion</description>
        <label>Premise</label>
        <picklist>
            <picklistValues>
                <fullName>On &amp; Off Premise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Off Premise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Military</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Premise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transportation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Promotion_Start_Date__c</fullName>
        <description>INFOWELDERS:Used by CRM.
        NPA Rollout: Used to store the promotion start date.</description>
        <label>Promotion Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Promotion_Status__c</fullName>
        <description>NPA Rollout: Promotion Status to hold multiple status of National Promotion</description>
        <label>Promotion Status</label>
        <picklist>
            <picklistValues>
                <fullName>Created</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <description>NPA Rollout: Stores the Sales Org for the promotion</description>
        <label>Sales Org</label>
        <picklist>
            <picklistValues>
                <fullName>1000</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>North</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>East</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SouthW</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Tertile__c</fullName>
        <description>NPA Rollout: Stores the Tertile for which the Promotion applies</description>
        <formula>IF( MONTH(Promotion_Start_Date__c) &lt;5 , &apos;3rd Tertile&apos;, IF( MONTH(Promotion_Start_Date__c) &lt;9 , &apos;1st Tertile&apos;, &apos;2nd Tertile&apos;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Tertile</label>
        <type>Text</type>
    </fields>
    <label>Promotion</label>
    <nameField>
        <label>Promotion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Promotion_Clone_Fields__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>NPA Rollout: This Custom Setting is used to denote the Required attribute of fields on the Promotion Clone page. This is related to Field Set NPA_Clone_Promotion.</description>
    <fields>
        <fullName>Required_Field__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Denotes whether the field will be required on the page layout.</description>
        <label>Required Field</label>
        <type>Checkbox</type>
    </fields>
    <label>Promotion Clone Fields</label>
</CustomObject>

B-F Backup Sandbox 30.4.12/src/objects/Promotion_Material_Item__c.object
<CustomObject>
    <description>Used by CRM.
NPA Rollout: Used to store products added to Promotions (Promotion line items).</description>
    <fields>
        <fullName>Planned_Cost__c</fullName>
        <description>NPA Rollout: Stores the planned cost of the product for this promotion</description>
        <label>Planned Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_Custom__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>NPA Rollout: Used to store the related Product. /* API name need to be changed to Product__c after Product remediation*/</description>
        <label>Product Name</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Promotion Material Items</relationshipLabel>
        <relationshipName>Promotion_Material_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Description__c</fullName>
        <description>NPA Rollout: Used to fetch the product description</description>
        <label>Product Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Promotion__c</fullName>
        <description>Infowelders: Used by CRM.
		NPA Rollout: Used to refer to Promotion.</description>
        <label>Promotion</label>
        <referenceTo>Promotion__c</referenceTo>
        <relationshipLabel>Promotion Material Items</relationshipLabel>
        <relationshipName>Promotion_Material_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <description>Infowelders</description>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>NPA Rollout: Field to store the status of product for the promotion</description>
        <label>Item Status</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Unit_of_Measure__c</fullName>
        <description>NPA Rollout: Used to store the Unit of Measure for the product</description>
        <label>UoM</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Promotion Material Item</label>
    <nameField>
        <displayFormat>PMI-{YYYY}{00000}</displayFormat>
        <label>Promotion Material Item#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotion Material Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

B-F Sandbox/trunk/src/classes/NPA_CustomPromotionClone.cls
/*****************************************************************************************
 Name    : NPA_CustomPromotionClone
 Desc    : Public class to clone a promotion along with PromotionLineItems.
           a) Using Visual force the select promotion information is first copied into a new instance 
           b) All the fields of the Visual force page is populated with the selected promotion.
           c) After update of fields the new instance is saved and then lineitems from original object would be copied.
 Approach: 
            a) Controller contains one promotion instance to hold the selected promotion information.
            b) Show all the fields associated to the standard edit page layout in the clone page.
            c) Populate the fields from the new promotion instance which is not saved to Database.
            d) On click of save new promotion instance would be saved to Database with updated fields.
            e) Copy all the Lines from old promotion to the new instance.
 Modification Log : 
 ---------------------------------------------------------------------------
 Developer              Date            Description
 ---------------------------------------------------------------------------
 Achin Suman            04/11/2011      Original Version
 ******************************************************************************************/

public class NPA_CustomPromotionClone {
    public Promotion__c clonepromo {get;set;}
    // Map to store required attribute of fields displayed on the page
    public Map<String,Boolean> fieldMap {get;set;}
   /*****************************************************************************************
     Constructor
     ===========
     Method Name    :    NPA_CustomPromotionClone 
     Description    :   a) Get Promotion record details based on Id.
                         
     Arguments      :   void
     Return Type    :   void
     ******************************************************************************************/
         
    public NPA_CustomPromotionClone(ApexPages.StandardController controller) {
        clonepromo=[Select (Select Name,Promotion__c,Quantity__c,Product_Custom__c,Status__c,Planned_Cost__c,
                               Unit_of_Measure__c,Product_Description__c from Promotion_Material_Items__r),
                        p.Tertile__c, p.Sales_Org__c,p.CreatedDate , p.RecordTypeId, p.Premise_Indicator_Code__c, 
                        p.Promotion_Status__c, p.Promotion_Start_Date__c, p.Promotion_Premise__c, p.Promotion_Number__c, 
                        p.Promotion_End_Date__c, p.Name, p.Mark_for_Delete__c, p.Internal_Order__c, p.GTM_Channel_Description__c, p.GTM_Channel_Code__c, 
                        p.Freeze_Date__c, p.Fiscal_Year__c, p.Brand_NPA__c From Promotion__c p where p.Id =: controller.getId()][0];
        System.debug('The promotion is '+clonepromo);
        
        fieldMap = new Map<String,Boolean>();
        // Get all the custom setting values and populate the fields map 
        for(Promotion_Clone_Fields__C field: Promotion_Clone_Fields__C.getall().values()){
            fieldMap.put(field.Name, field.Required_Field__c);
        }
    }
   /*****************************************************************************************
     Method 
     ===========
     Method Name    :    custom_clone 
     Description    :   a) Inserts the new promotion instance and copy the lines from the old
                            promotion to new instance.
                        b) Returns the PageReference newly created record.
                         
     Arguments      :   void
     Return Type    :   PageReference
     ******************************************************************************************/
    
    public PageReference custom_clone(){
    try{
            Promotion__c clonedpromo = clonepromo.clone(false,true);
            System.debug('The new cloned is'+clonedpromo);
            clonedPromo.Promotion_Status__c = 'Created';
            insert clonedpromo;
            final String pliStatus = '0';
            List<Promotion_Material_Item__c> lineitems = new List<Promotion_Material_Item__c>();
            if(clonepromo.Promotion_Material_Items__r.size() > 0)
            {
                //lineitems = clonepromo.Promotion_Material_Items__r.clone();
                for(Promotion_Material_Item__c pmi : clonepromo.Promotion_Material_Items__r)    
                {
                    Promotion_Material_Item__c li = new Promotion_Material_Item__c(promotion__c=clonedpromo.Id,status__c=pliStatus,
                                                        Product_Custom__c=pmi.Product_Custom__c,Quantity__c=pmi.Quantity__c,
                                                        Planned_Cost__c=pmi.planned_cost__c,unit_of_measure__c=pmi.unit_of_measure__c,
                                                        Product_Description__c=pmi.Product_Description__c);
                    lineitems.add(li);
                }     
                insert lineitems;
            }
            PageReference pr = new PageReference('/'+clonedpromo.Id);
            return pr;
        }
        catch(Exception e)
        {
            System.debug('the apex messages are '+ ApexPages.getMessages().size());
            
            String errorMsg = ''; 
            ApexPages.Message myMsg;
            if(e.getMessage().contains('IO_Fiscal_Tertile__c')){
                
                errorMsg = 'Duplicate: Another Promotion exists for the selected Internal Order for the specified Tertile and Fiscal Year.' ;
                myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,errorMsg);
                ApexPages.addMessage(myMsg);
            }
            return null;    
        }
        
    }
   /*****************************************************************************************
     Method
     ===========
     Method Name    :    Cancel 
     Description    :   a) Used to return the control to the inital promotion selected without 
                            performing any operation.
     Arguments      :   void
     Return Type    :   PageReference
     ******************************************************************************************/
    
    
    public PageReference cancel(){
       PageReference pr = new PageReference('/'+clonepromo.Id);
       return pr;
    }
    
    
}