B-F Sandbox Full-Backup/src/objects/My_Links_Instructions__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Instruction__c</fullName>
        <defaultValue>&quot;Instructions are displayed here&quot;</defaultValue>
        <label>Instruction</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>My Links Instructions</label>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Quick_Link__c.object
<CustomObject>
    <description>Tab to help maintain all links surfaced by Quick Links tab</description>
    <fields>
        <fullName>Category__c</fullName>
        <description>Used to filter Quick Links</description>
        <inlineHelpText>Where should this Quick Link appear?</inlineHelpText>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>About Me</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Analytics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anywhere Access</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Building Brands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Collaboration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Diversity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Google</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Louisville</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>External__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If this is an external link, add target=&quot;_blank&quot; to the link</description>
        <inlineHelpText>Does this link need to open in a new tab?</inlineHelpText>
        <label>External?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Image_Link__c</fullName>
        <description>Stores link to image on Salesforce</description>
        <inlineHelpText>Please upload an image to the Documents tab for this Quick Link</inlineHelpText>
        <label>Image Link</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Link_Location__c</fullName>
        <description>Where does this Quick Link go?</description>
        <inlineHelpText>Where does this Quick Link go?</inlineHelpText>
        <label>Link Location</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>Text to appear below image</description>
        <inlineHelpText>Text to appear below link image</inlineHelpText>
        <label>Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Quick Link</label>
    <nameField>
        <displayFormat>QL-{00000}</displayFormat>
        <label>Quick Link Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Manage Quick Links</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/UserQuickLink__c.object
<CustomObject>
    <description>APPIRIO - Junction object between User and QuickLink objects.  Used to hold My Links quick links.</description>
    <fields>
        <fullName>Quick_Link_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quick Link ID</label>
        <referenceTo>Quick_Link__c</referenceTo>
        <relationshipName>User_Quick_Links</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UserId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>UserId</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Quick_Links</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>UserQuickLink</label>
    <nameField>
        <displayFormat>UQL-{00000}</displayFormat>
        <label>UserQuickLinks Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UserQuickLinks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

B-F Sandbox/trunk/src/classes/EverythingElseController.cls
/*************************************************************
*Name : EverythingElseController
*Created By : Akash (Appirio Off)
*Created Date : 5th july,2011
*Modified by Raj Rao on July 25, 2011
*Purpose : To control the user links page , 
            where user can add and remove his/her favourite quick links
            
*Modified by Mike Shroyer on 10/3/2011
*Purpose : Changed the getItems() method to read Quick link categories from the DB               
****************************************************************/
public with sharing class EverythingElseController {
   String category = 'All';
   Id currentUserId = UserInfo.getUserId();     
   public String selectedLink{get;set;} 
   public String imagePath{get;set;}
   My_Links_Instructions__c linksInstructions;
   Map<id,id> mpLinkUser = new Map<id,id>();
   Map<Id,Quick_Link__c> mpQuickLink = new Map<Id,Quick_Link__c>();
   public List<Quick_Link__c> QuickLinks{get;set;}
   public String linkClass{get;set;}
   public String statusMessage{get;set;}
   public String myLinks{get;set;} 
   //-------------------------------------------------//
   // Constructor 
   //-------------------------------------------------//
   public EverythingElseController() {
     queryQuickLinks();     
     mpLinkUser = queryExistingUserLinks();
     linksInstructions = getlinksInstructions(); 
     //Check if user has any favorites. If yes then display the My Links Category
     if(mpLinkUser.size()>0){
         setCategory('My Links');
         changeCategory();
     }else{
         myLinks = 'none';
     }
   }   
   
   //-------------------------------------------------//
   // Get Instructions in custom settings
   //-------------------------------------------------//
   private My_Links_Instructions__c getlinksInstructions() {
    //First check if the user has any special privileges
    My_Links_Instructions__c linksInstructions = My_Links_Instructions__c.getValues(UserInfo.getUserId());
    if(linksInstructions != null) {
      return linksInstructions;
    }
    //Check for Task Sharing applicable to a particular profile
    linksInstructions = My_Links_Instructions__c.getValues(UserInfo.getProfileId());
    if(linksInstructions != null) {
      return linksInstructions;
    }    
    //Nothing specific to user or profile, then use the org wide defaults
    return My_Links_Instructions__c.getOrgDefaults();
  }
   
   //-------------------------------------------------//
   // return the instruction string 
   //-------------------------------------------------//
   public String getInstructions() {
         if(linksInstructions != null)
       return linksInstructions.Instruction__c;
     return '';  
   }
   //-------------------------------------------------//
   // To query All quick links 
   //-------------------------------------------------//
   private void queryQuickLinks() {
     QuickLinks = new List<Quick_Link__c>();                
     QuickLinks =  [SELECT Category__c, Name__c,Image_Link__c,Link_Location__c,External__c FROM Quick_Link__c ORDER BY Name__c];     
     for(Quick_Link__c link : QuickLinks) {
       mpQuickLink.put(link.Id,link);
     }
   } 
   //-------------------------------------------------//
   // To change the category of the links to be displayed
   // based on the selection made from drop down
   //-------------------------------------------------//
   public PageReference changeCategory() {
     if(category == 'My Links') {
       showFavourites();
     }
     else if(category == 'All') {
       QuickLinks = [SELECT Category__c, Name__c,Image_Link__c,Link_Location__c,External__c FROM Quick_Link__c ORDER BY Name__c];
     }
     else {
       QuickLinks =  [SELECT Category__c, Name__c,Image_Link__c,Link_Location__c,External__c FROM Quick_Link__c Where Category__c Includes (:category) ORDER BY Name__c];
     }
     return null;
   }
   //-------------------------------------------------//
   // To populate the category drop down    
   // to be displayed on the page
   //-------------------------------------------------//

	public List<SelectOption> getItems() {
		List<SelectOption> options = new List<SelectOption>();
		Map<String,String> uniqueOptions = new Map<String,String>();
		
		//Get all values from the DB
		for (Quick_Link__c q : [select Category__c From Quick_Link__c where Category__c <> null]) {
			//split the multi-select options and put into map
  			String[] temp = q.Category__c.split(';');
  			for(String s : temp) {
    			uniqueOptions.put(s,s);
			}	
		}		
		
		//Get the values from the Map and sort them
		List<String> sortedOptions = uniqueOptions.values();
		sortedOptions.sort();
		
		//Add values to list of Select Options
		options.add(new SelectOption('All','All'));
		for (String s : sortedOptions) {
			options.add(new SelectOption(s,s));
		}
		
		return options;
	}   
   //-------------------------------------------------//
   // To query all the user links to be displayed on the page    
   // for initialiing the page
   //-------------------------------------------------//
   private Map<id,id> queryExistingUserLinks() {
     Map<id,id> mpLinkUser = new Map<id,id>();     
     for(UserQuickLink__c link : [select id,Quick_Link_ID__c,UserId__c from UserQuickLink__c where UserId__c = :currentUserId]) {
       mpLinkUser.put(link.Quick_Link_ID__c,currentUserId);
     }
     return mpLinkUser;
   }         
           
   //-------------------------------------------------//
   // Returns the current chosen category      
   //-------------------------------------------------//
   public String getCategory() {
     return category;
   }
   //-------------------------------------------------//
   // Sets the current category      
   //-------------------------------------------------//
   public void setCategory(String s) {
     this.category = s;
   }
   //-------------------------------------------------//
   // To insert new User favourite link if it does not already exists      
   //-------------------------------------------------//
   public PageReference createUserLinks() {     
     statusMessage = 'Quick Link already exists in My Links';
     imagePath = '/img/msg_icons/warning24.png';
     if(!mpLinkUser.containsKey(selectedLink)) {
       UserQuickLink__c userLink = new UserQuickLink__c(UserId__c = currentUserId,Quick_Link_ID__c = selectedLink);
       try { 
         insert userLink;  
         mpLinkUser.put(selectedLink,currentUserId);
         statusMessage = 'Quick Link has been added to My Favs';
         imagePath = '/img/msg_icons/confirm24.png';
       }
       catch(DMLException de) {
         ApexPages.addMessages(de);
       }
     }     
     return null;
   }
   //-------------------------------------------------//
   // To populate the list of user favourite links
   // to be displayed on the page       
   //-------------------------------------------------//
   public PageReference showFavourites() {      
     QuickLinks = new List<Quick_Link__c>();
   /*  for(Id linkId : mpLinkUser.keySet()) {
       QuickLinks.add(mpQuickLink.get(linkId));
     }*/
     QuickLinks = [SELECT Category__c, Name__c,Image_Link__c,Link_Location__c,External__c FROM Quick_Link__c where Id IN :mpLinkUser.keySet() ORDER BY Name__c];
     linkClass = 'linkimg';
     return null;
   }
   //-------------------------------------------------//
   // To delete the selected link from user favourite link    
   //-------------------------------------------------//
   public PageReference deleteFavourites() {
     category = 'My Links';
     try {
       delete [select id from UserQuickLink__c where UserId__c = :currentUserId AND Quick_Link_ID__c = :selectedLink];
       mpLinkUser.remove(selectedLink);
     }
     catch(DMLException de) {
       ApexPages.addMessages(de);
     }
     showFavourites();
     return null;
   }
}