B-F Sandbox Full-Backup/src/objects/News__c.object
<CustomObject>
    <description>Post News</description>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <length>32000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Breaking_News__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>When you check this field, it will place a banner across the top with a link to this story.</inlineHelpText>
        <label>Breaking News</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Content__c</fullName>
        <description>Enter content</description>
        <inlineHelpText>Enter content</inlineHelpText>
        <label>Content</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>External_URL__c</fullName>
        <description>Enter External URL.</description>
        <inlineHelpText>Enter External URL. No entry required if pointing to this document.</inlineHelpText>
        <label>External URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Featured__c</fullName>
        <defaultValue>false</defaultValue>
        <description>criteria for Featured section of NewsHome VF Page</description>
        <inlineHelpText>Check this field if you wish this article to show in the Featured section of the News Page</inlineHelpText>
        <label>Featured</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <description>Select the Category of the news article.</description>
        <inlineHelpText>Select the Category of the news article.</inlineHelpText>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Company</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Story of the Day</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Video of the Day</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Travel Alert</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Thumbnail_URL__c</fullName>
        <label>Thumbnail URL</label>
        <type>Url</type>
    </fields>
    <label>Manage News</label>
    <nameField>
        <displayFormat>News-{000000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Manage News</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

B-F Backup Sandbox 30.4.12/src/objects/news_settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Article_List__c</fullName>
        <description>The number of articles that will be returned on the News Home page</description>
        <label>Article List</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Brand_News_Chatter__c</fullName>
        <label>Brand News Chatter</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_News_Chatter__c</fullName>
        <label>Company News Chatter</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Employee_News_Chatter__c</fullName>
        <label>Employee News Chatter</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EtQ_Chatter__c</fullName>
        <label>EtQ Chatter</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expenses_Chatter__c</fullName>
        <label>Expenses Chatter</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Footer__c</fullName>
        <label>Footer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Industry_News_Chatter__c</fullName>
        <label>Industry News Chatter</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoice_Processing_Chatter__c</fullName>
        <label>Invoice Processing Chatter</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>News_Exchange_Chatter__c</fullName>
        <label>News Exchange Chatter</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Page_Title__c</fullName>
        <label>Page Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Story_of_the_Day_Chatter__c</fullName>
        <label>Story of the Day Chatter</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Travel_Chatter__c</fullName>
        <label>Travel Chatter</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Video_of_the_Day_Chatter__c</fullName>
        <label>Video of the Day Chatter</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>News Settings</label>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Stock_Data__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>List of Stock Quotes for scheduled APEX to gather</description>
    <label>Stock Data</label>
</CustomObject>

B-F Backup Sandbox 30.4.12/src/classes/displayNewsController.cls
public class displayNewsController {
    public String redirectChatterGroup { get; set; }
    public DateTime StockUpdatedDate { get; set; }

    String newsSection = ApexPages.currentPage().getParameters().get('section'); 
    String chatterGroup = '';
    
    public String getNewsCategory() {
        return ApexPages.currentPage().getParameters().get('section');
    }
    
    public List<Stock_Data__c> getStockData() {
    	List<Stock_Data__c> returnList = new List<Stock_Data__c>(); 	
	    List<Stock_Data__c> stockData = Stock_Data__c.getall().values();
        
        for (Stock_Data__c stock : stockData) {
            returnList.add(stock);
        }
        
        StockUpdatedDate = stockData.get(0).LastModifiedDate; 
        return returnList;
    }
    
    public double getArticleList() {
       	return news_settings__c.getInstance().Article_List__c;
    }  
    public Integer articleLimit = getArticleList().intValue();
    
    public String getPageTitle() {
        return news_settings__c.getInstance().Page_Title__c;
    }
    
    public String getFooter() {
        return news_settings__c.getInstance().Footer__c;
    }   

    public String getBrandNewsChatter() {
        return news_settings__c.getInstance().Brand_News_Chatter__c;
    }     
    
    public String getEmployeeNewsChatter() {
        return news_settings__c.getInstance().Employee_News_Chatter__c;
    }     

    public String getCompanyNewsChatter() {
        return news_settings__c.getInstance().Company_News_Chatter__c;
    }     

    public String getIndustryNewsChatter() {
        return news_settings__c.getInstance().Industry_News_Chatter__c;
    }     

    public String getNewsExchangeChatter() {
        return news_settings__c.getInstance().News_Exchange_Chatter__c;
    }     

    public String getStoryoftheDayChatter() {
        return news_settings__c.getInstance().Story_of_the_Day_Chatter__c;
    }     
 
     public String getVideooftheDayChatter() {
        return news_settings__c.getInstance().Video_of_the_Day_Chatter__c;
    }     
    
    public String getTravelChatter() {
        return news_settings__c.getInstance().Travel_Chatter__c;
    }  
        
    public String getExpensesChatter() {
        return news_settings__c.getInstance().Expenses_Chatter__c;
    }     

/* public String getStockChatter() {
      return news_settings__c.getInstance().Stock_Chatter__c;
   }    
*/
    public String getInvoiceProcessingChatter() {
        return news_settings__c.getInstance().Invoice_Processing_Chatter__c;
    }     
    
    public String getEtQChatter() {
        return news_settings__c.getInstance().EtQ_Chatter__c;
    }     
    
    public List<News__c> getCompanyNews() {
        return [SELECT id, name__c,external_url__c, CreatedDate FROM News__c WHERE Group__c = :'Company' ORDER BY LastModifiedDate Desc limit :articleLimit];
   }
   
    public List<News__c> getAllSectionNews() {
        return [SELECT id, name__c,external_url__c, LastModifiedDate FROM News__c WHERE Group__c = :newsSection ORDER BY LastModifiedDate Desc];
   }   

   public List<News__c> getBrandNews() {
        return [SELECT id, name__c,external_url__c, CreatedDate FROM News__c WHERE Group__c = :'Brands' ORDER BY LastModifiedDate Desc limit :articleLimit];
   }
   
   public List<News__c> getEmployeeNews() {
        return [SELECT id, name__c,external_url__c, CreatedDate FROM News__c WHERE Group__c = :'Employee' ORDER BY LastModifiedDate Desc limit :articleLimit];
   }   

    public List<News__c> getIndustryNews() {
        return [SELECT id, name__c,external_url__c, CreatedDate FROM News__c WHERE Group__c = :'Industry' ORDER BY LastModifiedDate Desc limit :articleLimit];
   }  
   
   public List<News__c> getFeatured() {
        return [SELECT id, name__c,external_url__c FROM News__c WHERE Featured__c = true ORDER BY LastModifiedDate Desc limit :articleLimit];
   }  

   public News__c getBreakingNews() {
   		List<News__c> breakingNews = [SELECT id, name__c,external_url__c FROM News__c WHERE Breaking_News__c = true ORDER BY LastModifiedDate Desc limit 1];
   		
   		if (breakingNews.isEmpty()) { 
        	return null;
   		} else {
   			return breakingNews.get(0);
   		}
   }  
   
   public News__c getStoryOfTheDay() {
        return [SELECT id, name__c,external_url__c,thumbnail_url__c FROM News__c WHERE Group__c = :'Story of the Day' ORDER BY LastModifiedDate Desc limit 1];
   }

   public News__c getVideoOfTheDay() {
        return [SELECT id, name__c,external_url__c,thumbnail_url__c FROM News__c WHERE Group__c = :'Video of the Day' ORDER BY LastModifiedDate Desc limit 1];
   }          

   public List<News__c> getTravelAlert() {
        return [SELECT id, name__c,external_url__c FROM News__c WHERE Group__c = :'Travel Alert' ORDER BY LastModifiedDate Desc];
   }   
       
    public News__c getNewsPost() {
        return [SELECT id, name__c, source__c,content__c,Body__c,createddate FROM News__c WHERE id = :ApexPages.currentPage().getParameters().get('id')];
    }

    public String getCheckSotDMember(){
        return checkForChatterMembership(getStoryoftheDayChatter());
    }
    
    public String getCheckVotDMember(){
        return checkForChatterMembership(getVideooftheDayChatter());
    }
    
    public String getCheckNewsExchangeMember(){
        return checkForChatterMembership(getNewsExchangeChatter());
    }
    
    public String getCheckBrandMember(){
        return checkForChatterMembership(getBrandNewsChatter());
    }
    
    public String getCheckCompanyMember(){
        return checkForChatterMembership(getCompanyNewsChatter());
    }
    
    public String getCheckEmployeeMember(){
        return checkForChatterMembership(getEmployeeNewsChatter());
    }   

    public String getCheckIndustryMember(){
        return checkForChatterMembership(getIndustryNewsChatter());
    }    
    
    public String getCheckTravelMember(){
        return checkForChatterMembership(getTravelChatter());
    }     
    
    public String getCheckExpensesMember(){
        return checkForChatterMembership(getExpensesChatter());
    }         
    
/*    public String getCheckStockMember(){
        return checkForChatterMembership(getStockChatter());
    }
*/    
    public String getCheckInvoiceProcessingMember(){
        return checkForChatterMembership(getInvoiceProcessingChatter());
    }
    
    public String getCheckEtQMember(){
        return checkForChatterMembership(getEtQChatter());
    }
    
    public String checkForChatterMembership(ID cg) {
        String currentUser = UserInfo.getUserId();
        String grpMemberId;
        String showHideJoinLink;
        List<CollaborationGroupMember> oM = [SELECT MemberId FROM CollaborationGroupMember WHERE CollaborationGroupId = :cg];
        for(CollaborationGroupMember grpM : oM){
            grpMemberId = grpM.MemberId ;
            if(grpMemberId.equals(currentUser)){
                showHideJoinLink ='display:none';                
                //showHideJoinLink ='';             
            }
        }
        return showHideJoinLink;
    }
    
 
        public PageReference redirectChatterGroup() {
            String selectedChatterGroup = getChatterGroup(); 
            PageReference pageRef = new PageReference('/_ui/core/chatter/groups/GroupProfilePage?g='+selectedChatterGroup);
            pageRef.setRedirect(true);
            return pageRef;
        }
                
        public String getChatterGroup() {
            return chatterGroup;
        }

        public void setChatterGroup(String s) {
            this.chatterGroup = s;
        }

}