B-F Sandbox Full-Backup/src/objects/Outlet_Visit__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Outlet (Account)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Outlet Visits</relationshipLabel>
        <relationshipName>Outlet_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Competitor_Activity__c</fullName>
        <label>Competitor Activity</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Met_With__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Met With (Contact)</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Outlet Visits</relationshipLabel>
        <relationshipName>Outlet_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Visit_Comments__c</fullName>
        <label>Visit Comments</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Visit_Date__c</fullName>
        <label>Visit Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Outlet Visit</label>
    <nameField>
        <displayFormat>OV-{00000}</displayFormat>
        <label>Outlet Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outlet Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

B-F Sandbox/trunk/src/classes/mobileOutletVisit_Controller.cls
public with sharing class mobileOutletVisit_Controller {
    
    public mobileOutletVisit_Controller()
    {

    } 

    public List<Outlet_Visit__c> getRecentOVs() 
    {
        List<Outlet_Visit__c> optionList = new List<Outlet_Visit__c>();
        // Add a null option to force the user to make a selection. //
        //optionList.add(new SelectOption('None','--Please Choose--'));
        return [Select o.Visit_Date__c, o.Visit_Comments__c, o.SystemModstamp, o.OwnerId, o.Name, o.Met_With__c, o.LastModifiedDate, o.LastModifiedById, o.IsDeleted, o.Id, o.CurrencyIsoCode, o.CreatedDate, o.CreatedById, o.Competitor_Activity__c, o.Account__c, o.Account__r.Name From Outlet_Visit__c o where o.CreatedById =: userinfo.getUserId() and 
        (
        	(o.CreatedDate >=: date.today().adddays(-1) and o.CreatedDate <=: date.today().adddays(1)) 
        	or 
        	(
        		o.LastModifiedById  =: userinfo.getUserId() and 
        		(o.LastModifiedDate >=: date.today().adddays(-1) and o.LastModifiedDate <=: date.today().adddays(2))
        	)
        )];
    }   
    

}