B-F Sandbox Full-Backup/src/objects/Outlet_Visit__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Outlet (Account)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Outlet Visits</relationshipLabel>
        <relationshipName>Outlet_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Outlet Visit</label>
    <nameField>
        <displayFormat>OV-{00000}</displayFormat>
        <label>Outlet Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outlet Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

B-F Backup Sandbox 30.4.12/src/objects/Outlet_Visit_Item__c.object
<CustomObject>
    <fields>
        <fullName>Available__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Infowelders</description>
        <label>Available</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Outlet_Visit__c</fullName>
        <label>Outlet Visit</label>
        <referenceTo>Outlet_Visit__c</referenceTo>
        <relationshipLabel>Outlet Visit Items</relationshipLabel>
        <relationshipName>Outlet_Visit_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Outlet Visit Items</relationshipLabel>
        <relationshipName>Outlet_Visit_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shelf__c</fullName>
        <description>Infowelders</description>
        <label>Shelf</label>
        <picklist>
            <picklistValues>
                <fullName>1. Shelf from Bottom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2. Shelf from Bottom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3. Shelf from Bottom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4. Shelf from Bottom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5. Shelf from Bottom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6. Shelf from Bottom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7. europalette</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7. Shelf from Bottom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8. Shelf from Bottom</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Outlet Visit Item</label>
    <nameField>
        <label>Outlet Visit Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Outlet Visit Items</pluralLabel>
    <recordTypes>
        <fullName>Germany</fullName>
        <active>true</active>
        <label>Germany</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Product__c.object
<CustomObject>
    <description>NPA Rollout: Object for storing Products used in National Promotion application.
Product Remediation : Replicated all standard product fields here.</description>
    <fields>
        <fullName>Product__c</fullName>
        <description>NPA Rollout: Stores the product code</description>
        <label>Product Unique Key</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <recordTypes>
        <fullName>Wet_Goods</fullName>
        <active>true</active>
        <label>Wet Goods</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Store_Check__c.object
<CustomObject>
    <description>A store check is a controll visit by the sales manager after his sales rep has just left the outlet and entered his outlet visit data.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Store Checks</relationshipLabel>
        <relationshipName>Store_Checks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Addit_notes_comments_about_cust_acc__c</fullName>
        <label>Addit. notes/comments about cust./acc.</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>All_pricing_labels_available__c</fullName>
        <defaultValue>false</defaultValue>
        <label>All pricing labels available?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>B_F_listing_complete_realized_practiced__c</fullName>
        <defaultValue>false</defaultValue>
        <label>B-F listing complete realized/practiced?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Data_maintenance_in_SF_complete_correct__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Data maintenance in SF complete/correct?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Gaps_in_shelf_closed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Gaps in shelf closed..?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Gift_promo_packs_addit_avail_in_shelf__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Gift/promo packs addit. avail. in shelf?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Gift_promo_packs_in_shelf_available__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Gift/promo packs in shelf available?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>JD_Cola_Ginger_avail_as_in_multi_pack__c</fullName>
        <defaultValue>false</defaultValue>
        <label>JD&amp;Cola/Ginger avail. as/in multi pack?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>JD_Cola_Ginger_avail_as_single_can__c</fullName>
        <defaultValue>false</defaultValue>
        <label>JD &amp; Cola/Ginger avail. as single can?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>JD_Cola_Ginger_avail_in_chiller_cab__c</fullName>
        <defaultValue>false</defaultValue>
        <label>JD &amp; Cola/Ginger avail. in chiller cab.?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>JD_Cola_Ginger_available_in_shelf__c</fullName>
        <defaultValue>false</defaultValue>
        <label>JD &amp; Cola/Ginger available in shelf?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>JD_Cola_Ginger_available_in_tray__c</fullName>
        <defaultValue>false</defaultValue>
        <label>JD &amp; Cola/Ginger available in tray?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Last_Outlet_Visit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Last Outlet Visit</label>
        <referenceTo>Outlet_Visit__c</referenceTo>
        <relationshipLabel>Store Checks</relationshipLabel>
        <relationshipName>Store_Checks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Visit_SR__c</fullName>
        <label>Last Visit SR</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Location_first_SCP__c</fullName>
        <description>Location of the target article/product</description>
        <label>Location</label>
        <picklist>
            <picklistValues>
                <fullName>Store front</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(shelf) End cap</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spirit department</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chiller cabinet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check out area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Isle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Food section</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Notes_Comment_about_shelf_situation__c</fullName>
        <label>Notes/Comment about shelf situation</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Product_first_SCP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Store Checks</relationshipLabel>
        <relationshipName>Store_Checks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_second_SCP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Store Checks (Product)</relationshipLabel>
        <relationshipName>Store_Checks1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_third_SCP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Store Checks (Product)</relationshipLabel>
        <relationshipName>Store_Checks2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rating_Grade__c</fullName>
        <label>Rating/Grade</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Remarks_after_discussion__c</fullName>
        <label>Remarks after discussion</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SC_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SC By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Stores_Check</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SC_Date__c</fullName>
        <label>SC Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>SR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SR</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Stores_Check1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_campaign_labels_tended__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sales campaign labels tended?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Targ_for_follow_up_visit_maintained_SF__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Targ. for follow up visit maintained/SF?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>enough_products_in_the_shelf_available__c</fullName>
        <defaultValue>false</defaultValue>
        <label>enough products in the shelf available?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>sales_campaign_with_2_pl_realized__c</fullName>
        <defaultValue>false</defaultValue>
        <label>sales campaign with 2. pl. realized?</label>
        <type>Checkbox</type>
    </fields>
    <label>Store Check</label>
    <nameField>
        <displayFormat>{YYYYMM}-{00000}</displayFormat>
        <label>Store Check Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store Checks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/Store_Check_Item__c.object
<CustomObject>
    <fields>
        <fullName>Outlet_Visit_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Outlet Visit Item</label>
        <referenceTo>Outlet_Visit_Item__c</referenceTo>
        <relationshipLabel>Store Check Items</relationshipLabel>
        <relationshipName>Store_Check_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Store Check Items</relationshipLabel>
        <relationshipName>Store_Check_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Store_Check__c</fullName>
        <label>Store Check</label>
        <referenceTo>Store_Check__c</referenceTo>
        <relationshipLabel>Store Check Items</relationshipLabel>
        <relationshipName>Store_Check_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Store Check Item</label>
    <nameField>
        <displayFormat>SCI-{0000}</displayFormat>
        <label>Store Check Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store Check Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

B-F Sandbox/trunk/src/classes/StoreCheckController.cls
/* Class Name : StoreCheckController
* Description: Controller that loads and saves all data referring to StoreCheck records
* Created By : Germany Consultant
* Created On : 05/03/12
*
* Modification Log :  
* ----------------------------------------------------------------------------------------------------------------------------
* Developer       		Date			Description
* ----------------------------------------------------------------------------------------------------------------------------
* Michael Mickiewicz 	05/03/2012		Create the whole business logic for the Store Check Interface. Including field-level-
*										access, read-only mode and new-record-mode. 
*/ 
public with sharing class StoreCheckController {
    
    public ID recordID {get;set;}
    public Account a {get;set;}
    public Store_Check__c record {get;set;}
    public Outlet_Visit__c lastVisitedOutletVisit {get;set;}
    public Boolean isReadOnly {get;set;}	//Necessary to identify, if interface is in read-only of read-write mode
    public list<Product__c> products {get;set;}
    public list<Store_Check_Item__c> sci_header {get;set;} //Required as a dummy list for fixed-table-header-workaround
    public list<Store_Check_Item__c> selected_sci {get;set;}
    public list<Outlet_Visit_Item__c> lastOVIs {get;set;}
    
    private Boolean isNewRecord;	//Necessary to identify, if interface is opened in new or edit mode
    
    
    public StoreCheckController(ApexPages.StandardController ctrl){
        isReadOnly = false;
        recordID = ctrl.getRecord().ID;
        isNewRecord = false;
        
        //Branch for distinction if interface is in new or in edit mode
        if(recordID == null) {
            record = new Store_Check__c(Account__c = ((Store_Check__c)ctrl.getRecord()).Account__c);
            isNewRecord = true;
        } else {
            record = [Select ID, 
                        Account__c, 
                        Last_Visit_SR__c,  
                        Last_Outlet_Visit__c,
                        SR__c, 
                        SC_By__c, 
                        SC_Date__c, 
                        Rating_Grade__c,
                        Notes_Comment_about_shelf_situation__c, 
                        All_pricing_labels_available__c, 
                        sales_campaign_with_2_pl_realized__c,
                        Sales_campaign_labels_tended__c, 
                        Gaps_in_shelf_closed__c, 
                        enough_products_in_the_shelf_available__c,
                        Gift_promo_packs_in_shelf_available__c,
                        Gift_promo_packs_addit_avail_in_shelf__c, 
                        JD_Cola_Ginger_available_in_shelf__c,
                        JD_Cola_Ginger_avail_in_chiller_cab__c,
                        JD_Cola_Ginger_available_in_tray__c,
                        JD_Cola_Ginger_avail_as_single_can__c,
                        JD_Cola_Ginger_avail_as_in_multi_pack__c,
                        B_F_listing_complete_realized_practiced__c,
                        Data_maintenance_in_SF_complete_correct__c,
                        Targ_for_follow_up_visit_maintained_SF__c,
                        Remarks_after_discussion__c,
                        Addit_notes_comments_about_cust_acc__c,
                        Product_first_SCP__c,
                        Product_second_SCP__c,
                        Product_third_SCP__c,
                        Location_first_SCP__c,
                        Location_second_SCP__c,
                        Location_third_SCP__c,
                        Ground_Area_First_SCP__c,
                        Ground_Area_Second_SCP__c,
                        Ground_Area_Third_SCP__c,
                        Space_First_SCP__c,
                        Space_Second_SCP__c,
                        Space_Third_SCP__c,
                        Number_of_bottles_display_First_SCP__c,
                        Number_of_bottles_display_Second_SCP__c,
                        Number_of_bottles_display_Third_SCP__c,
                        Notes_comments_about_secondary_placement__c
                    From Store_Check__c 
                    Where ID = :recordID limit 1];
        }
        
        //Query all needed account information
        a = [Select ID, Billingcity, Billingstreet, Market__c From Account Where ID = :record.Account__c limit 1];
        
        //Query LAST outlet visit information
        list<Outlet_Visit__c> ovs;
        if(isNewRecord) 
            ovs = [Select Id, Name, Met_With__c, Visit_Date__c, Visit_Comments__c, OwnerId  From Outlet_Visit__c Where Last_Visit__c = true and Account__c = :record.Account__c limit 1];
        else
            ovs = [Select Id, Name, Met_With__c, Visit_Date__c, Visit_Comments__c, OwnerId  From Outlet_Visit__c Where Id = :record.Last_Outlet_Visit__c limit 1];
        
        if(ovs.size() > 0) {
            lastVisitedOutletVisit = ovs.get(0);
            if(isNewRecord) {
                record.Last_Outlet_Visit__c = lastVisitedOutletVisit.Id;
                record.SR__c = lastVisitedOutletVisit.OwnerId;
                record.Last_Visit_SR__c = lastVisitedOutletVisit.Visit_Date__c;
            }
            lastOVIs = [Select Id, Available__c, Bottle_Price_Special__c, Bottle_Price__c, Facing__c, Shelf__c, Custom_Product__c, Product__r.Name From Outlet_Visit_Item__c Where Available__c = true and Outlet_Visit__c = :lastVisitedOutletVisit.ID];
        }   
        
 		//Filling list for pageblocktable of outlet visit items
        sci_header = new list<Store_Check_Item__c>();
        if(recordID != null)
            selected_sci = [Select Product__c, Product__r.Name, Price__c, Special_Price__c, Facings_shelf__c, OOS_with__c, Shelf_from_bottom__c, Store_Check__c From Store_Check_Item__c Where Store_Check__c = :recordID];
        else {
            selected_sci = new list<Store_Check_Item__c>();
            for(Outlet_Visit_Item__c ovi : [Select Id, Available__c, Bottle_Price_Special__c, Bottle_Price__c, Facing__c, Shelf__c, Custom_Product__c, Product__r.Name, Product__c From Outlet_Visit_Item__c Where Outlet_Visit__c = :record.Last_Outlet_Visit__c AND Available__c = true]) {
                selected_sci.add(new Store_Check_Item__c(Product__c = ovi.Custom_Product__c, Outlet_Visit_Item__c = ovi.Id));
            }
        }
        
        if (!Schema.sObjectType.Store_Check_Item__c.fields.Facings_GAM__c.isUpdateable() && !Schema.sObjectType.Store_Check_Item__c.fields.Facings_shelf__c.isUpdateable() && !Schema.sObjectType.Store_Check_Item__c.fields.OOS_with__c.isUpdateable() && !Schema.sObjectType.Store_Check_Item__c.fields.Shelf_from_bottom__c.isUpdateable()){
              isReadOnly = true;
        }
        
        set<ID> selectedProductIDs = new set<ID>();
        for(Store_Check_Item__c sci : selected_sci)
            if(!selectedProductIDs.contains(sci.Product__c))
                selectedProductIDs.add(sci.Product__c);
                
        products = [Select ID, Name From Product__c Where RecordType.Name = 'Wet Goods' AND ID NOT IN :selectedProductIDs AND Market__c = :a.Market__c order by Name asc];
        
        if(selected_sci == null)
            selected_sci = new list<Store_Check_Item__c>();
    }
    

    public PageReference selectItem() {
        String id = ApexPages.currentPage().getParameters().get('productID');
        
        Integer i = 0;
        
        for(Product__c p : products){ 
            if(p.ID == id)
                break;
            i++;
        }
        
        products.remove(i);
        Outlet_Visit_Item__c ovi;
        
        for(Outlet_Visit_Item__c o : [Select Id, Available__c, Bottle_Price_Special__c, Bottle_Price__c, Facing__c, Shelf__c, Custom_Product__c, Product__r.Name, Product__c From Outlet_Visit_Item__c Where Product__c = :id AND  Outlet_Visit__c = :record.Last_Outlet_Visit__c limit 1])
            ovi = o;
            
        if(id != null && id != '') {
            Store_Check_Item__c sci = new Store_Check_Item__c(Product__c = id, Store_Check__c = recordID);
            if(ovi != null)
                sci.Outlet_Visit_item__c = ovi.Id;
            selected_sci.add(sci);
        }
        
        return null;
    }
    
    
    public PageReference deselectItem() {
        String id = ApexPages.currentPage().getParameters().get('productID');
        system.debug(id);
        Integer i = 0;
        
        for(Store_Check_Item__c sci : selected_sci) {
            if(sci.Product__c == id)
                break;
            i++;
        }
        
        if(i < selected_sci.size()) {
            selected_sci.remove(i);
            set<ID> selectedProductIDs = new set<ID>();
            for(Store_Check_Item__c sci : selected_sci)
                if(!selectedProductIDs.contains(sci.Product__c))
                    selectedProductIDs.add(sci.Product__c);
            
            products = [Select ID, Name From Product__c Where RecordType.Name = 'Wet Goods' AND ID NOT IN :selectedProductIDs order by Name asc];
        
        } else
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, Label.sc_error_sc_not_found));
        
        return null;
    }
    
    
    public PageReference save() {
        
        try{
            upsert record; 
            recordID = record.ID;
            
        }catch(Exception e) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, Label.sc_error_sc_cannot_be_updated));
            return null;
        }
        try{
            if(selected_sci.size() > 0) {
                for(Store_Check_Item__c item : selected_sci)
                    if(item.Store_Check__c == null)
                        item.Store_Check__c = recordID;
                upsert selected_sci;
            }
        }catch(Exception e) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, Label.sc_error_sci_cannot_be_saved));
            return null;
        }
        
        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Info, Label.sc_info_saved));
        return cancel();
    }
    
    
    public PageReference cancel() {
        return new PageReference('/'+record.Account__c);
    }
    
    
    
    
    public static testMethod void MainTest() {
    	RecordType rt = [Select ID From RecordType Where sObjectType = 'Product__c' AND DeveloperName = 'Wet_Goods' limit 1]; 
    	
        Market__c market = new Market__c(Market_Code__c = 'GER', Name = 'Germany', Off_Channel__c = '2', On_Channel__c = '3');
        insert market;
        
    	Account account1 = new Account(Name = 'Test Account 1', Market__c = market.Id, Channel__c = 'Off', BillingCountry = 'DE');
        insert account1;
    
    	Brand__c brand1 = new Brand__c(Name = 'Jack Daniel\'s');
    	insert brand1;
    	
        Brand__c brand2 = new Brand__c(Name = 'Herradura');
        insert brand2;
        
        Product__c product1 = new Product__c(Brand__c = brand1.ID, RecordTypeID = rt.ID, Market__c = market.Id);
        insert product1;
                
        Product__c product2 = new Product__c(Brand__c = brand2.ID, RecordTypeID = rt.ID, Market__c = market.Id);
        insert product2; 
        
        Store_Check__c obj = new Store_Check__c(Account__c = account1.Id);
        insert obj;
        
        ApexPages.StandardController stdCtrl = new ApexPages.StandardController(obj);
        StoreCheckController ctrl = new StoreCheckController(stdCtrl);
        
        ID productID = ctrl.products.get(ctrl.products.size()-1).Id;
        ApexPages.currentPage().getParameters().put('ProductID', productID);
        ctrl.selectItem();
       
        ctrl.save();
        
        ctrl = new StoreCheckController(stdCtrl);
        ApexPages.currentPage().getParameters().put('ProductID', productID);
        ctrl.deselectItem();
        
        ctrl.cancel();
        
        obj = new Store_Check__c(Account__c = account1.Id);
        
        stdCtrl = new ApexPages.StandardController(obj);
        ctrl = new StoreCheckController(stdCtrl);
    }
}