B-F Sandbox Full-Backup/src/objects/Product_Launch__c.object
<CustomObject>
    <fields>
        <fullName>Survey_Date__c</fullName>
        <label>Survey Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sync__c</fullName>
        <defaultValue>true</defaultValue>
        <description>This Flag will be updates via Workflow when date are manipulated via workflow</description>
        <label>Sync</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Week__c</fullName>
        <label>Visits</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Product Launch</label>
    <nameField>
        <displayFormat>PL-{0}</displayFormat>
        <label>Product Launch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Launch</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

B-F Backup Sandbox 30.4.12/src/objects/Product_Launch_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Counter__c</fullName>
        <label>Counter</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Launch__c</fullName>
        <label>Product Launch</label>
        <referenceTo>Product_Launch__c</referenceTo>
        <relationshipLabel>Product Launch Details</relationshipLabel>
        <relationshipName>Product_Launch_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Survey_Date__c</fullName>
        <label>Survey Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Week__c</fullName>
        <label>Week</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <label>Product Launch Detail</label>
    <nameField>
        <displayFormat>PLD-{0}</displayFormat>
        <label>Product Launch Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Launch Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/classes/reorderProductLaunchDetails.cls
public with sharing class reorderProductLaunchDetails {




public Id myDelete(Id myRecord) {
string dummy;	

	
	
List<Product_Launch_Detail__c> reorder = [SELECT Id, Counter__c, week__c,Survey_Date__c FROM Product_Launch_Detail__c where Product_Launch__c =:myRecord ORDER BY Survey_Date__c ASC];

Integer i = 1;

for(Product_Launch_Detail__c FL1 : reorder){



FL1.Counter__c = i;
FL1.Week__c = 'Week'+i; 	
	
i = i + 1;

}

update(reorder);

Product_Launch__c updateVisit = [Select Week__c from Product_Launch__c where Id =:myRecord];

updateVisit.Week__c = i-1; 

update(updateVisit);

return dummy;

}
								
public Id myUpdate(Id myRecord) {
string jtest;	

//Getting List of Product Launch Details
List<Product_Launch_Detail__c> reorder = [SELECT Id, Counter__c, week__c,Survey_Date__c,Product_Launch__c FROM Product_Launch_Detail__c where Product_Launch__c =:myRecord ORDER BY Survey_Date__c ASC];


//Loop through the List
for(Product_Launch_Detail__c FL1 : reorder){

//Checking the Sync Flag
Product_Launch__c myFlag = [SELECT Id, sync__c FROM Product_Launch__c where Id = :fL1.Product_Launch__c limit 1];


	
//Chacking to see if the Sync Flag is unchecked
if (myFlag.sync__c == false){

//Setting the Flag to True
myFlag.sync__c = true;

//My Counter	
Integer x = 1;

//This loop realigns the records based of of the Survey Date
for(Product_Launch_Detail__c FL2 : reorder){

//New Values
FL2.Counter__c = x;
FL2.Week__c = 'Week'+x; 	

//Increase the Counter	
x = x + 1;

}
//This update prevents the update from becoming recursive
update(myFlag);

//Update the Product Launch Detail records
update(reorder);
//update(myFlag);
}

break;
}

return jtest;	
}
	
	

}