B-F Sandbox Full-Backup/src/objects/Promotion__c.object
<CustomObject>
    <description>Used by CRM.
NPA Rollout: Used to store Promotions.</description>
    <fields>
        <fullName>Brand_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Infowelders</description>
        <label>Brand Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Promotions1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Finance_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Infowelders</description>
        <label>Finance Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Promotions2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>INFOWELDERS</description>
        <label>Sales Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Promotion</label>
    <nameField>
        <label>Promotion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

B-F Backup Sandbox 30.4.12/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Brand_Manager__c</fullName>
        <description>INFOWELDERS</description>
        <label>Brand Manager</label>
        <relationshipName>Users2</relationshipName>
        <restrictedAdminField>false</restrictedAdminField>
        <type>Hierarchy</type>
    </fields>
    <fields>
        <fullName>Finance_Manager__c</fullName>
        <description>INFOWELDERS</description>
        <label>Finance Manager</label>
        <relationshipName>Users1</relationshipName>
        <restrictedAdminField>false</restrictedAdminField>
        <type>Hierarchy</type>
    </fields>
    <fields>
        <fullName>Sales_Manager__c</fullName>
        <description>INFOWELDERS</description>
        <label>Sales Manager</label>
        <relationshipName>Users</relationshipName>
        <restrictedAdminField>false</restrictedAdminField>
        <type>Hierarchy</type>
    </fields>
</CustomObject>

B-F Backup Sandbox 30.4.12/src/classes/promotionHelperClass.cls
global with sharing class promotionHelperClass
{
    webservice static void setPromotionUserLookups(ID[] promIds)
    {
        Set<ID> ownerIds = new Set<ID>();
        Map<ID,Promotion__c> mapProm = new Map<ID,Promotion__c>([Select Id, OwnerId from Promotion__c where Id in: promIds]);
    for(Promotion__c p : mapProm.values())
        {
            ownerIds.add(p.OwnerId);
        }
        
        Map<ID,User> mapUser = new Map<ID,User>([Select Id, Brand_Manager__c, Finance_Manager__c, Sales_Manager__c from User where Id in: ownerIds]);
        for(Promotion__c p : mapProm.values())
        {
            User u = mapUser.get(p.OwnerId);  
            if(u==null){continue;}
            p.Brand_Manager__c = u.Brand_Manager__c;
            p.Finance_Manager__c = u.Finance_Manager__c;
            p.Sales_Manager__c = u.Sales_Manager__c;            
        }
        update mapProm.values();
    }

	public static void calculateAccountBrandTotals(Set<ID> myIDS)
	{
		try{
			SYNCHcalculateAccountBrandTotals(myIDS);
     	}catch(AsyncException e){
			ASYNCHcalculateAccountBrandTotals(myIDS);
		}
	}
	
	@future (callout=true) 
	public static void ASYNCHcalculateAccountBrandTotals(Set<ID> myIDS)
	{

	}		
	public static void SYNCHcalculateAccountBrandTotals(Set<ID> myIDS)
	{

	}		
}