B-F Sandbox Full-Backup/src/objects/Quick_Link__c.object
<CustomObject>
    <description>Tab to help maintain all links surfaced by Quick Links tab</description>
    <fields>
        <fullName>Category__c</fullName>
        <description>Used to filter Quick Links</description>
        <inlineHelpText>Where should this Quick Link appear?</inlineHelpText>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>About Me</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Analytics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anywhere Access</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Building Brands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Collaboration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Diversity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Google</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Louisville</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Image_Link__c</fullName>
        <description>Stores link to image on Salesforce</description>
        <inlineHelpText>Please upload an image to the Documents tab for this Quick Link</inlineHelpText>
        <label>Image Link</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Link_Location__c</fullName>
        <description>Where does this Quick Link go?</description>
        <inlineHelpText>Where does this Quick Link go?</inlineHelpText>
        <label>Link Location</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>Text to appear below image</description>
        <inlineHelpText>Text to appear below link image</inlineHelpText>
        <label>Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Quick Link</label>
    <nameField>
        <displayFormat>QL-{00000}</displayFormat>
        <label>Quick Link Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Manage Quick Links</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

B-F Sandbox Full-Backup/src/objects/UserQuickLink__c.object
<CustomObject>
    <description>APPIRIO - Junction object between User and QuickLink objects.  Used to hold My Links quick links.</description>
    <fields>
        <fullName>Quick_Link_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quick Link ID</label>
        <referenceTo>Quick_Link__c</referenceTo>
        <relationshipName>User_Quick_Links</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UserId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>UserId</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Quick_Links</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>UserQuickLink</label>
    <nameField>
        <displayFormat>UQL-{00000}</displayFormat>
        <label>UserQuickLinks Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UserQuickLinks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

B-F Backup Sandbox 30.4.12/src/classes/Test_EverythingElseController.cls
/*************************************************************
*Name : Test_BF_UsersMustFollowManagerJob
*Created By : Akash (Appirio Off)
*Created Date : 1st july,2011
*Purpose : Tests EverythingElseController (controller for quick link)
****************************************************************/
@isTest
private class Test_EverythingElseController {

    static testMethod void myUnitTest() {
    	  
        Test.startTest();
        Quick_Link__c quickLink1 = new Quick_Link__c(
        Image_Link__c = 'http://www.google.com',
        Link_Location__c = 'http://www.google.com',
        Name__c = 'test',
        Category__c = 'Google'
        );
        insert quickLink1;
        Quick_Link__c quickLink2 = new Quick_Link__c(
        Image_Link__c = 'http://www.google.com',
        Link_Location__c = 'http://www.google.com',
        Name__c = 'test',
        Category__c = 'Google'
        );        
        insert quickLink2;
        UserQuickLink__c userLink = new UserQuickLink__c(UserId__c = UserInfo.getUserId() ,Quick_Link_ID__c = quickLink2.Id); 
        insert userLink;
        EverythingElseController everyThing = new EverythingElseController();
        everyThing.getItems();
        everyThing.setCategory('All');        
        system.assertEquals('All',everyThing.getCategory());
        everyThing.selectedLink = quickLink1.Id;
        everyThing.createUserLinks();
        List<UserQuickLink__c> lstUserLink = [select id from UserQuickLink__c where Quick_Link_ID__c = :quickLink1.Id And UserId__c = :UserInfo.getUserId()];
        system.assert(lstUserLink.size() > 0);
        everyThing.showFavourites();
        everyThing.selectedLink = quickLink1.Id;
        everyThing.deleteFavourites();  
        everyThing.changeCategory();
        Test.stopTest();
    }
}