B-F Sandbox Full-Backup/src/objects/SOD__c.object
<CustomObject>
    <description>Used for SOD Certification</description>
    <fields>
        <fullName>Certified_Complete__c</fullName>
        <label>Certified Complete?</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Compliance_Method__c</fullName>
        <label>Compliance Method</label>
        <picklist>
            <picklistValues>
                <fullName>Included</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mailed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Faxed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>UniqueID__c</fullName>
        <description>Unique Identifier to prevent duplicates</description>
        <label>UniqueID</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Certification Records</label>
    <nameField>
        <label>SOX Contact</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certification Records</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

B-F Backup Sandbox 30.4.12/src/classes/test_certificationCheck.cls
/**********************************************************************************
* Class Name  : test_certificationCheck
* Description : This test class is to cover certificationCheck class
*
*    
* Modification Log :  
* ----------------------------------------------------------------------------------
* Developer                                 Date             Description
* ----------------------------------------------------------------------------------
* Fayas Mansoor(Deloitte Consulting)      28/05/2011          Created
************************************************************************************/

@isTest
Private class test_certificationCheck
{
    static testMethod void classTest(){
        // test data preparation
        SOD__c testData=new SOD__c();
        testData.Certified_Complete__c='No';
        testData.Compliance_Method__c='Included';
        testData.UniqueID__c='asdasdqwe123123';
        //inserting testdata 
        Database.insert(testData);
        
        Test.starttest();
        certificationCheck.checkCertification(testData.id);
        Test.stoptest();
        
    }
}