B-F Sandbox Full-Backup/src/objects/SOD__c.object
<CustomObject>
    <description>Used for SOD Certification</description>
    <fields>
        <fullName>Certified_Complete__c</fullName>
        <label>Certified Complete?</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Compliance_Method__c</fullName>
        <label>Compliance Method</label>
        <picklist>
            <picklistValues>
                <fullName>Included</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mailed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Faxed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Certification Records</label>
    <nameField>
        <label>SOX Contact</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certification Records</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

B-F Sandbox/trunk/src/classes/certificationCheck.cls
global class certificationCheck{   
    Webservice static boolean checkCertification(String recordId){
    List<Attachment> att = [Select Id from Attachment where ParentId =: recordId limit 1];
    SOD__c cert = [Select Certified_Complete__c,Compliance_Method__c from SOD__c where Id =: recordId];

        // check if attachment exists or Compliance Method not null
        if(att.size() > 0 || cert.Compliance_Method__c != null){
            //update Certified_Complete field value to Yes           
            if(cert.Certified_Complete__c != 'Yes'){
                    cert.Certified_Complete__c = 'Yes';
                    update cert;
            }           
            return true;
        }else{
            return false;
        }       
    }
}