B-F Sandbox Full-Backup/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>LastTransactionStatus__c</fullName>
        <label>LastTransactionStatus</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Wombat_Sync_Session_ID__c</fullName>
        <label>Wombat_Sync_Session_ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
</CustomObject>

B-F Sandbox Full-Backup/src/classes/wombat_UpdateSessionStatus.cls
@RestResource(urlMapping='/Wombat/Status/*')
global class wombat_UpdateSessionStatus {
	@HttpPost
	global static wombat_Sync_Object updateSessionStatus(String sessionID, String userID, Integer status) {
		wombat_Sync_Object wso = new Wombat_Sync_Object();
		wso.Success = true; 
		
		try {
			User u = [SELECT LastTransactionStatus__c FROM User WHERE Id = :userID LIMIT 1];
			if (u != null) {
				u.Wombat_Sync_Session_ID__c = sessionID;
				u.LastTransactionStatus__c = status;
				update u;
			}			
		} catch(Exception ex) {
			wso.Success = false;
			wso.Messages.add(ex.getMessage());
		}
		
		return wso;
	}
}